// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gofiber/fiber/v2"
	"github.com/oapi-codegen/runtime"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Account defines model for Account.
type Account struct {
	Bank     Bank       `json:"bank"`
	ClosedAt *time.Time `json:"closed_at,omitempty"`
	Id       string     `json:"id"`
	Name     string     `json:"name"`
	OpenedAt time.Time  `json:"opened_at"`
}

// AccountCreateRequest defines model for AccountCreateRequest.
type AccountCreateRequest struct {
	BankId   string    `json:"bank_id"`
	Name     string    `json:"name"`
	OpenedAt time.Time `json:"opened_at"`
}

// AccountCreateResponse defines model for AccountCreateResponse.
type AccountCreateResponse struct {
	Ids []string `json:"ids"`
}

// AccountDeleteResponse defines model for AccountDeleteResponse.
type AccountDeleteResponse struct {
	Id      string `json:"id"`
	Message string `json:"message"`
}

// Bank defines model for Bank.
type Bank struct {
	ApiImportEnabled bool   `json:"api_import_enabled"`
	CsvImportEnabled bool   `json:"csv_import_enabled"`
	FixedProducts    *bool  `json:"fixed_products,omitempty"`
	Id               string `json:"id"`
	Name             string `json:"name"`
}

// Category defines model for Category.
type Category struct {
	CreatedAt time.Time      `json:"created_at"`
	Id        string         `json:"id"`
	Name      string         `json:"name"`
	Rules     []CategoryRule `json:"rules"`
}

// CategoryAddRuleRequest defines model for CategoryAddRuleRequest.
type CategoryAddRuleRequest struct {
	CategoryId *string `json:"category_id,omitempty"`
	Rule       *string `json:"rule,omitempty"`
}

// CategoryAddRuleResponse defines model for CategoryAddRuleResponse.
type CategoryAddRuleResponse struct {
	Id     string `json:"id"`
	RuleId string `json:"rule_id"`
}

// CategoryCreateRequest defines model for CategoryCreateRequest.
type CategoryCreateRequest struct {
	Name string `json:"name"`
}

// CategoryCreateResponse defines model for CategoryCreateResponse.
type CategoryCreateResponse struct {
	Id string `json:"id"`
}

// CategoryDeleteResponse defines model for CategoryDeleteResponse.
type CategoryDeleteResponse struct {
	Id      string `json:"id"`
	Message string `json:"message"`
}

// CategoryEditRuleRequest defines model for CategoryEditRuleRequest.
type CategoryEditRuleRequest struct {
	CategoryId *string `json:"category_id,omitempty"`
	Rule       *string `json:"rule,omitempty"`
	RuleId     *string `json:"rule_id,omitempty"`
}

// CategoryEditRuleResponse defines model for CategoryEditRuleResponse.
type CategoryEditRuleResponse struct {
	Id     string `json:"id"`
	RuleId string `json:"rule_id"`
}

// CategoryRule defines model for CategoryRule.
type CategoryRule struct {
	Account Account `json:"account"`
	Id      string  `json:"id"`
	Rule    string  `json:"rule"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

// LoginResponse defines model for LoginResponse.
type LoginResponse struct {
	Id    string `json:"id"`
	Token string `json:"token"`
}

// NotAuthorized defines model for NotAuthorized.
type NotAuthorized struct {
	Message *string `json:"message,omitempty"`
}

// NotFound defines model for NotFound.
type NotFound struct {
	Message *string `json:"message,omitempty"`
}

// SignupRequest defines model for SignupRequest.
type SignupRequest struct {
	Email    *string `json:"email,omitempty"`
	Password *string `json:"password,omitempty"`
}

// SignupResponse defines model for SignupResponse.
type SignupResponse struct {
	Message string `json:"message"`
}

// Transaction defines model for Transaction.
type Transaction struct {
	Account     Account   `json:"account"`
	Amount      float32   `json:"amount"`
	Category    *Category `json:"category,omitempty"`
	CreatedAt   time.Time `json:"created_at"`
	Date        time.Time `json:"date"`
	Description string    `json:"description"`
	Id          string    `json:"id"`
}

// TransactionCreateRequest defines model for TransactionCreateRequest.
type TransactionCreateRequest struct {
	AccountId   string  `json:"account_id"`
	Amount      float32 `json:"amount"`
	CategoryId  string  `json:"category_id"`
	Description string  `json:"description"`
}

// TransactionCreateResponse defines model for TransactionCreateResponse.
type TransactionCreateResponse struct {
	Id string `json:"id"`
}

// TransactionDeleteResponse defines model for TransactionDeleteResponse.
type TransactionDeleteResponse struct {
	Id      string `json:"id"`
	Message string `json:"message"`
}

// User defines model for User.
type User struct {
	CreatedAt time.Time `json:"created_at"`
	Email     string    `json:"email"`
	Id        string    `json:"id"`
}

// GetUserIdTransactionsParams defines parameters for GetUserIdTransactions.
type GetUserIdTransactionsParams struct {
	AccountId *string `form:"account_id,omitempty" json:"account_id,omitempty"`
}

// PostLoginJSONRequestBody defines body for PostLogin for application/json ContentType.
type PostLoginJSONRequestBody = LoginRequest

// PostSignupJSONRequestBody defines body for PostSignup for application/json ContentType.
type PostSignupJSONRequestBody = SignupRequest

// PostUserIdAccountsJSONRequestBody defines body for PostUserIdAccounts for application/json ContentType.
type PostUserIdAccountsJSONRequestBody = AccountCreateRequest

// PostUserIdCategoriesJSONRequestBody defines body for PostUserIdCategories for application/json ContentType.
type PostUserIdCategoriesJSONRequestBody = CategoryCreateRequest

// PostUserIdCategoriesCategoryIdRulesJSONRequestBody defines body for PostUserIdCategoriesCategoryIdRules for application/json ContentType.
type PostUserIdCategoriesCategoryIdRulesJSONRequestBody = CategoryAddRuleRequest

// PatchUserIdCategoriesCategoryIdRulesRuleIdJSONRequestBody defines body for PatchUserIdCategoriesCategoryIdRulesRuleId for application/json ContentType.
type PatchUserIdCategoriesCategoryIdRulesRuleIdJSONRequestBody = CategoryEditRuleRequest

// PostUserIdTransactionsJSONRequestBody defines body for PostUserIdTransactions for application/json ContentType.
type PostUserIdTransactionsJSONRequestBody = TransactionCreateRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /banks)
	GetBanks(c *fiber.Ctx) error

	// (POST /login)
	PostLogin(c *fiber.Ctx) error

	// (POST /signup)
	PostSignup(c *fiber.Ctx) error

	// (GET /user/{id})
	GetUserId(c *fiber.Ctx, id string) error

	// (GET /user/{id}/accounts)
	GetUserIdAccounts(c *fiber.Ctx, id string) error

	// (POST /user/{id}/accounts)
	PostUserIdAccounts(c *fiber.Ctx, id string) error

	// (DELETE /user/{id}/accounts/{account_id})
	DeleteUserIdAccountsAccountId(c *fiber.Ctx, id string, accountId string) error

	// (GET /user/{id}/accounts/{account_id})
	GetUserIdAccountsAccountId(c *fiber.Ctx, id string, accountId string) error

	// (GET /user/{id}/categories)
	GetUserIdCategories(c *fiber.Ctx, id string) error

	// (POST /user/{id}/categories)
	PostUserIdCategories(c *fiber.Ctx, id string) error

	// (DELETE /user/{id}/categories/{category_id})
	DeleteUserIdCategoriesCategoryId(c *fiber.Ctx, id string, categoryId string) error

	// (GET /user/{id}/categories/{category_id})
	GetUserIdCategoriesCategoryId(c *fiber.Ctx, id string, categoryId string) error

	// (POST /user/{id}/categories/{category_id}/rules)
	PostUserIdCategoriesCategoryIdRules(c *fiber.Ctx, id string, categoryId string) error

	// (DELETE /user/{id}/categories/{category_id}/rules/{rule_id})
	DeleteUserIdCategoriesCategoryIdRulesRuleId(c *fiber.Ctx, id string, categoryId string, ruleId string) error

	// (PATCH /user/{id}/categories/{category_id}/rules/{rule_id})
	PatchUserIdCategoriesCategoryIdRulesRuleId(c *fiber.Ctx, id string, categoryId string, ruleId string) error

	// (GET /user/{id}/transactions)
	GetUserIdTransactions(c *fiber.Ctx, id string, params GetUserIdTransactionsParams) error

	// (POST /user/{id}/transactions)
	PostUserIdTransactions(c *fiber.Ctx, id string) error

	// (DELETE /user/{id}/transactions/{transaction_id})
	DeleteUserIdTransactionsTransactionId(c *fiber.Ctx, id string, transactionId string) error
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

type MiddlewareFunc fiber.Handler

// GetBanks operation middleware
func (siw *ServerInterfaceWrapper) GetBanks(c *fiber.Ctx) error {

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.GetBanks(c)
}

// PostLogin operation middleware
func (siw *ServerInterfaceWrapper) PostLogin(c *fiber.Ctx) error {

	return siw.Handler.PostLogin(c)
}

// PostSignup operation middleware
func (siw *ServerInterfaceWrapper) PostSignup(c *fiber.Ctx) error {

	return siw.Handler.PostSignup(c)
}

// GetUserId operation middleware
func (siw *ServerInterfaceWrapper) GetUserId(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.GetUserId(c, id)
}

// GetUserIdAccounts operation middleware
func (siw *ServerInterfaceWrapper) GetUserIdAccounts(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.GetUserIdAccounts(c, id)
}

// PostUserIdAccounts operation middleware
func (siw *ServerInterfaceWrapper) PostUserIdAccounts(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.PostUserIdAccounts(c, id)
}

// DeleteUserIdAccountsAccountId operation middleware
func (siw *ServerInterfaceWrapper) DeleteUserIdAccountsAccountId(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	// ------------- Path parameter "account_id" -------------
	var accountId string

	err = runtime.BindStyledParameterWithOptions("simple", "account_id", c.Params("account_id"), &accountId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter account_id: %w", err).Error())
	}

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.DeleteUserIdAccountsAccountId(c, id, accountId)
}

// GetUserIdAccountsAccountId operation middleware
func (siw *ServerInterfaceWrapper) GetUserIdAccountsAccountId(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	// ------------- Path parameter "account_id" -------------
	var accountId string

	err = runtime.BindStyledParameterWithOptions("simple", "account_id", c.Params("account_id"), &accountId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter account_id: %w", err).Error())
	}

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.GetUserIdAccountsAccountId(c, id, accountId)
}

// GetUserIdCategories operation middleware
func (siw *ServerInterfaceWrapper) GetUserIdCategories(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.GetUserIdCategories(c, id)
}

// PostUserIdCategories operation middleware
func (siw *ServerInterfaceWrapper) PostUserIdCategories(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.PostUserIdCategories(c, id)
}

// DeleteUserIdCategoriesCategoryId operation middleware
func (siw *ServerInterfaceWrapper) DeleteUserIdCategoriesCategoryId(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	// ------------- Path parameter "category_id" -------------
	var categoryId string

	err = runtime.BindStyledParameterWithOptions("simple", "category_id", c.Params("category_id"), &categoryId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter category_id: %w", err).Error())
	}

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.DeleteUserIdCategoriesCategoryId(c, id, categoryId)
}

// GetUserIdCategoriesCategoryId operation middleware
func (siw *ServerInterfaceWrapper) GetUserIdCategoriesCategoryId(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	// ------------- Path parameter "category_id" -------------
	var categoryId string

	err = runtime.BindStyledParameterWithOptions("simple", "category_id", c.Params("category_id"), &categoryId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter category_id: %w", err).Error())
	}

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.GetUserIdCategoriesCategoryId(c, id, categoryId)
}

// PostUserIdCategoriesCategoryIdRules operation middleware
func (siw *ServerInterfaceWrapper) PostUserIdCategoriesCategoryIdRules(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	// ------------- Path parameter "category_id" -------------
	var categoryId string

	err = runtime.BindStyledParameterWithOptions("simple", "category_id", c.Params("category_id"), &categoryId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter category_id: %w", err).Error())
	}

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.PostUserIdCategoriesCategoryIdRules(c, id, categoryId)
}

// DeleteUserIdCategoriesCategoryIdRulesRuleId operation middleware
func (siw *ServerInterfaceWrapper) DeleteUserIdCategoriesCategoryIdRulesRuleId(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	// ------------- Path parameter "category_id" -------------
	var categoryId string

	err = runtime.BindStyledParameterWithOptions("simple", "category_id", c.Params("category_id"), &categoryId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter category_id: %w", err).Error())
	}

	// ------------- Path parameter "rule_id" -------------
	var ruleId string

	err = runtime.BindStyledParameterWithOptions("simple", "rule_id", c.Params("rule_id"), &ruleId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter rule_id: %w", err).Error())
	}

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.DeleteUserIdCategoriesCategoryIdRulesRuleId(c, id, categoryId, ruleId)
}

// PatchUserIdCategoriesCategoryIdRulesRuleId operation middleware
func (siw *ServerInterfaceWrapper) PatchUserIdCategoriesCategoryIdRulesRuleId(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	// ------------- Path parameter "category_id" -------------
	var categoryId string

	err = runtime.BindStyledParameterWithOptions("simple", "category_id", c.Params("category_id"), &categoryId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter category_id: %w", err).Error())
	}

	// ------------- Path parameter "rule_id" -------------
	var ruleId string

	err = runtime.BindStyledParameterWithOptions("simple", "rule_id", c.Params("rule_id"), &ruleId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter rule_id: %w", err).Error())
	}

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.PatchUserIdCategoriesCategoryIdRulesRuleId(c, id, categoryId, ruleId)
}

// GetUserIdTransactions operation middleware
func (siw *ServerInterfaceWrapper) GetUserIdTransactions(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetUserIdTransactionsParams

	var query url.Values
	query, err = url.ParseQuery(string(c.Request().URI().QueryString()))
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for query string: %w", err).Error())
	}

	// ------------- Optional query parameter "account_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "account_id", query, &params.AccountId)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter account_id: %w", err).Error())
	}

	return siw.Handler.GetUserIdTransactions(c, id, params)
}

// PostUserIdTransactions operation middleware
func (siw *ServerInterfaceWrapper) PostUserIdTransactions(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.PostUserIdTransactions(c, id)
}

// DeleteUserIdTransactionsTransactionId operation middleware
func (siw *ServerInterfaceWrapper) DeleteUserIdTransactionsTransactionId(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	// ------------- Path parameter "transaction_id" -------------
	var transactionId string

	err = runtime.BindStyledParameterWithOptions("simple", "transaction_id", c.Params("transaction_id"), &transactionId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter transaction_id: %w", err).Error())
	}

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.DeleteUserIdTransactionsTransactionId(c, id, transactionId)
}

// FiberServerOptions provides options for the Fiber server.
type FiberServerOptions struct {
	BaseURL     string
	Middlewares []MiddlewareFunc
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router fiber.Router, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, FiberServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router fiber.Router, si ServerInterface, options FiberServerOptions) {
	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	for _, m := range options.Middlewares {
		router.Use(fiber.Handler(m))
	}

	router.Get(options.BaseURL+"/banks", wrapper.GetBanks)

	router.Post(options.BaseURL+"/login", wrapper.PostLogin)

	router.Post(options.BaseURL+"/signup", wrapper.PostSignup)

	router.Get(options.BaseURL+"/user/:id", wrapper.GetUserId)

	router.Get(options.BaseURL+"/user/:id/accounts", wrapper.GetUserIdAccounts)

	router.Post(options.BaseURL+"/user/:id/accounts", wrapper.PostUserIdAccounts)

	router.Delete(options.BaseURL+"/user/:id/accounts/:account_id", wrapper.DeleteUserIdAccountsAccountId)

	router.Get(options.BaseURL+"/user/:id/accounts/:account_id", wrapper.GetUserIdAccountsAccountId)

	router.Get(options.BaseURL+"/user/:id/categories", wrapper.GetUserIdCategories)

	router.Post(options.BaseURL+"/user/:id/categories", wrapper.PostUserIdCategories)

	router.Delete(options.BaseURL+"/user/:id/categories/:category_id", wrapper.DeleteUserIdCategoriesCategoryId)

	router.Get(options.BaseURL+"/user/:id/categories/:category_id", wrapper.GetUserIdCategoriesCategoryId)

	router.Post(options.BaseURL+"/user/:id/categories/:category_id/rules", wrapper.PostUserIdCategoriesCategoryIdRules)

	router.Delete(options.BaseURL+"/user/:id/categories/:category_id/rules/:rule_id", wrapper.DeleteUserIdCategoriesCategoryIdRulesRuleId)

	router.Patch(options.BaseURL+"/user/:id/categories/:category_id/rules/:rule_id", wrapper.PatchUserIdCategoriesCategoryIdRulesRuleId)

	router.Get(options.BaseURL+"/user/:id/transactions", wrapper.GetUserIdTransactions)

	router.Post(options.BaseURL+"/user/:id/transactions", wrapper.PostUserIdTransactions)

	router.Delete(options.BaseURL+"/user/:id/transactions/:transaction_id", wrapper.DeleteUserIdTransactionsTransactionId)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xa33OjthP/Vzz6fh9pcNp78lOTtOmkc725yeWmD5mMR4G1rQtIRBLXcz387x0JMMIW",
	"IBLjH5m8JBhW2tXuZz+7Aq1QwOKEUaBSoMkKiWABMdaXF0HAUirVZcJZAlwS0A8eMX1S///PYYYm6H9+",
	"NYVfjPcvlUzmoSBiAsIp1tPMGI/VFQqxhJ8kiQF5SC4TQBMkJCd0roaQUMlu3aY4BusDlgDtpSLzEIfn",
	"lHAI0eRe6Stm9/KlmVM+rEezx28QSKWwcMwVByzhFp5TEA1emnasBX7gOInUs6sFBE+Ezkel173dL9RY",
	"41QvutcyRcKogO11kjD/JyEW1sUWNzDneGlxvmhT/htE0K7cqjIGIfDcBhdb7Etpmx2XBdbranFCpiRO",
	"GJdToPgxAtOMR8YiwFSjX3x3kpuRHxBOE87CNJDCLtMvLVowbjHKs63I5o4rLGHO+HLbJYGGybCZztMI",
	"6mBro6DS1ts0AgccGg6qllLqbPPFRRgqFY1EEBRyTWSgNNTJ4A5EwKzp3G1Ez0xRyu2G2RxUSre5o4MW",
	"t6nvD84C4OqxE4G56O7lhO2Ftqk4OCOVhvweErkf3HWgxMHCg4PytljrBo1XHU4bkZQluZmxSlc6WIvX",
	"9V0Pshn9kc0JbQwrxJhEVisSLMQ/jDv4LZ/DGNFiRs/YSfYEtNuCXMxryrZPTF6kcsE4+TevmXXdRjYF",
	"jCovqREjXA1xIs9PTF6zlLormGlpp7m/kDlNk+4oVtmXCuC/Fj/PAhbbEtEMcTVyfbeXZU2BdaaqNpa6",
	"45gKHEjC6C7yDsflgEITTeNH4LrHMloSl3ZAj3lBs6Ie9pAGEXCSlOt3a32sfBEXdFERhzl3YVdtSR3x",
	"6CjQhZ6mqlFFYo2/8/HYa45L00QbHqrQ/BeJnjpbAcNKw0emzroGR58M0DgYWg7eO3wVwHfTujdXIWdk",
	"l0WoFbmZhwQEKSdy+UUlcm7xJWAOXFUIvdPWv65Lu//8+w55+YsMvYXST6s1LKRMUKYmJnTGtK1EauBd",
	"E4ppAKM7joMn4KOLzzfIQ9+BC41RdH42PhuXG3GcEDRBv+hbipflQlvmq921vpqDdqdyNFbBvwlVrwvy",
	"Ugsof+Qw0MI/j8dFrZGQZxdOkogEeqT/TeQ5klOZ8waofAezsfHZzD30kQg5YrNRbnrmoQ/jD72saTNi",
	"XWMtiquSasYZTe7rEb5/yB6UgB+pjkTjlwmLcz8zIXXTgnK0gZCXLFzubCm1vizLclC/IogOugqmsAVN",
	"CYz4WkJF7XwvUftKjT7rQGjRcBC6kWnHQ97sDASIeo83MCI22jaLg5TEKE2GBIXRlHciIw+S6mr9FQmz",
	"Nk5Udekm1DzKcQwSuNAsoLJdc2v5cmZSbPnWtUTyFDzD/s268zBgRHQ1tblBAN8Iwn4yRCumPUl1HSC/",
	"6KlEd6QuSskjjJhTaTS2Fl3VsRA9jYB6LVS4p9Dtnmat31sGZlv7xw8neLww6/xVtafRZBnq3cJ2LPNd",
	"RD2axf9hONSzTlLbgR0HIds/Gh1ZTpe6+6W1Gx+/w6BG7qcf+DpVFK83im17OySuKtlTLdLmG7uuKl3K",
	"vpUyvYfw7b5Q2z8BDlypG779uWHkxQnor4x3jc7luopqacs+qbr+dvQ4uLrhs+qxZfha+S6r9jsamhn/",
	"LcTfjTv89akW95pQ4eVWDz4N0AxXcDaO4Oyp4myeuWkFbRrBCIchhLuvPjmC/FVxEOJV1UjjSf05BSqy",
	"z1aeBzk2Uts6DtOJlzyI4UEYT1nat6fFMlhYCEzdfkfcfhlx83TYniixP8YhJCcD8Tody+rDvsN+/M6U",
	"HhDnzynwZcPrmQPv580zQQ5bekP8rezqhwbBQKTSeHhoYFZpPqDjDJdX5LS/Mn716avMKBvX+6xvdcuP",
	"phVqPgt1hPlv6u9VJbLsvwAAAP//wHVqRVY1AAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
