// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gofiber/fiber/v2"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Defines values for PeriodUnit.
const (
	PeriodUnitDay   PeriodUnit = "day"
	PeriodUnitMonth PeriodUnit = "month"
	PeriodUnitWeek  PeriodUnit = "week"
	PeriodUnitYear  PeriodUnit = "year"
)

// Defines values for SummaryInterval.
const (
	SummaryIntervalDay   SummaryInterval = "day"
	SummaryIntervalMonth SummaryInterval = "month"
	SummaryIntervalWeek  SummaryInterval = "week"
	SummaryIntervalYear  SummaryInterval = "year"
)

// Defines values for TimePeriod.
const (
	All   TimePeriod = "all"
	Month TimePeriod = "month"
	Week  TimePeriod = "week"
	Year  TimePeriod = "year"
	Ytd   TimePeriod = "ytd"
)

// Account defines model for Account.
type Account struct {
	Bank     Bank       `json:"bank"`
	ClosedAt *time.Time `json:"closed_at,omitempty"`
	Id       string     `json:"id"`
	Name     string     `json:"name"`
	OpenedAt time.Time  `json:"opened_at"`
}

// AccountCreateRequest defines model for AccountCreateRequest.
type AccountCreateRequest struct {
	BankId   string    `json:"bank_id"`
	Name     string    `json:"name"`
	OpenedAt time.Time `json:"opened_at"`
}

// AccountCreateResponse defines model for AccountCreateResponse.
type AccountCreateResponse struct {
	Id string `json:"id"`
}

// AccountDeleteResponse defines model for AccountDeleteResponse.
type AccountDeleteResponse struct {
	Id      string `json:"id"`
	Message string `json:"message"`
}

// AccountEditRequest defines model for AccountEditRequest.
type AccountEditRequest struct {
	BankId   *string    `json:"bank_id,omitempty"`
	ClosedAt *time.Time `json:"closed_at,omitempty"`
	Name     *string    `json:"name,omitempty"`
	OpenedAt *time.Time `json:"opened_at,omitempty"`
}

// AccountEditResponse defines model for AccountEditResponse.
type AccountEditResponse struct {
	Id string `json:"id"`
}

// AccountSummary defines model for AccountSummary.
type AccountSummary struct {
	Account Account `json:"account"`
	Balance float32 `json:"balance"`
}

// AllAccountSummary defines model for AllAccountSummary.
type AllAccountSummary struct {
	Accounts []AccountSummary `json:"accounts"`
	Total    float32          `json:"total"`
}

// BalanceDatapoint defines model for BalanceDatapoint.
type BalanceDatapoint struct {
	Balance float32   `json:"balance"`
	Date    time.Time `json:"date"`
}

// BalanceSummary defines model for BalanceSummary.
type BalanceSummary struct {
	Accounts []BalanceSummaryAccount `json:"accounts"`
	Total    []BalanceDatapoint      `json:"total"`
}

// BalanceSummaryAccount defines model for BalanceSummaryAccount.
type BalanceSummaryAccount struct {
	Account Account            `json:"account"`
	Balance []BalanceDatapoint `json:"balance"`
}

// Bank defines model for Bank.
type Bank struct {
	ApiImportEnabled bool   `json:"api_import_enabled"`
	CsvImportEnabled bool   `json:"csv_import_enabled"`
	FixedProducts    *bool  `json:"fixed_products,omitempty"`
	Id               string `json:"id"`
	Name             string `json:"name"`
	ShortName        string `json:"short_name"`
}

// BudgetTransaction defines model for BudgetTransaction.
type BudgetTransaction struct {
	Amount      float32             `json:"amount"`
	Category    *Category           `json:"category,omitempty"`
	CreatedAt   time.Time           `json:"created_at"`
	DeletedAt   *time.Time          `json:"deleted_at,omitempty"`
	Description *string             `json:"description,omitempty"`
	EndsOn      *openapi_types.Date `json:"ends_on,omitempty"`
	Id          string              `json:"id"`
	RepeatEvery float32             `json:"repeat_every"`
	RepeatUntil PeriodUnit          `json:"repeat_until"`
	StartsOn    openapi_types.Date  `json:"starts_on"`
}

// BudgetTransactionCreateRequest defines model for BudgetTransactionCreateRequest.
type BudgetTransactionCreateRequest struct {
	Amount      float32             `json:"amount"`
	CategoryId  *string             `json:"category_id,omitempty"`
	Description *string             `json:"description,omitempty"`
	EndsOn      *openapi_types.Date `json:"ends_on,omitempty"`
	RepeatEvery float32             `json:"repeat_every"`
	RepeatUntil PeriodUnit          `json:"repeat_until"`
	StartsOn    openapi_types.Date  `json:"starts_on"`
}

// BudgetTransactionCreateResponse defines model for BudgetTransactionCreateResponse.
type BudgetTransactionCreateResponse struct {
	Id string `json:"id"`
}

// BudgetTransactionDeleteResponse defines model for BudgetTransactionDeleteResponse.
type BudgetTransactionDeleteResponse struct {
	Id      string `json:"id"`
	Message string `json:"message"`
}

// BudgetTransactionEditRequest defines model for BudgetTransactionEditRequest.
type BudgetTransactionEditRequest struct {
	Amount        float32             `json:"amount"`
	CategoryId    *string             `json:"category_id,omitempty"`
	Description   *string             `json:"description,omitempty"`
	EffectiveFrom openapi_types.Date  `json:"effective_from"`
	EndsOn        *openapi_types.Date `json:"ends_on,omitempty"`
	RepeatEvery   float32             `json:"repeat_every"`
	RepeatUntil   PeriodUnit          `json:"repeat_until"`
}

// BudgetTransactionEditResponse defines model for BudgetTransactionEditResponse.
type BudgetTransactionEditResponse struct {
	Id string `json:"id"`
}

// Category defines model for Category.
type Category struct {
	CreatedAt time.Time      `json:"created_at"`
	Id        string         `json:"id"`
	Name      string         `json:"name"`
	Rules     []CategoryRule `json:"rules"`
}

// CategoryAddRuleRequest defines model for CategoryAddRuleRequest.
type CategoryAddRuleRequest struct {
	AccountId   *string `json:"account_id,omitempty"`
	Description *string `json:"description,omitempty"`
	Rule        *string `json:"rule,omitempty"`
}

// CategoryAddRuleResponse defines model for CategoryAddRuleResponse.
type CategoryAddRuleResponse struct {
	Id string `json:"id"`
}

// CategoryBudget defines model for CategoryBudget.
type CategoryBudget struct {
	Amount      float32             `json:"amount"`
	Category    Category            `json:"category"`
	CreatedAt   time.Time           `json:"created_at"`
	DeletedAt   *time.Time          `json:"deleted_at,omitempty"`
	EndsOn      *openapi_types.Date `json:"ends_on,omitempty"`
	Id          string              `json:"id"`
	RepeatEvery float32             `json:"repeat_every"`
	RepeatUntil PeriodUnit          `json:"repeat_until"`
	StartsOn    openapi_types.Date  `json:"starts_on"`
}

// CategoryBudgetCreateRequest defines model for CategoryBudgetCreateRequest.
type CategoryBudgetCreateRequest struct {
	Amount      float32             `json:"amount"`
	CategoryId  string              `json:"category_id"`
	EndsOn      *openapi_types.Date `json:"ends_on,omitempty"`
	RepeatEvery float32             `json:"repeat_every"`
	RepeatUntil PeriodUnit          `json:"repeat_until"`
	StartsOn    openapi_types.Date  `json:"starts_on"`
}

// CategoryBudgetCreateResponse defines model for CategoryBudgetCreateResponse.
type CategoryBudgetCreateResponse struct {
	Id string `json:"id"`
}

// CategoryBudgetDeleteResponse defines model for CategoryBudgetDeleteResponse.
type CategoryBudgetDeleteResponse struct {
	Id      string `json:"id"`
	Message string `json:"message"`
}

// CategoryBudgetEditRequest defines model for CategoryBudgetEditRequest.
type CategoryBudgetEditRequest struct {
	Amount        float32             `json:"amount"`
	CategoryId    *string             `json:"category_id,omitempty"`
	EffectiveFrom openapi_types.Date  `json:"effective_from"`
	EndsOn        *openapi_types.Date `json:"ends_on,omitempty"`
	RepeatEvery   float32             `json:"repeat_every"`
	RepeatUntil   PeriodUnit          `json:"repeat_until"`
}

// CategoryBudgetEditResponse defines model for CategoryBudgetEditResponse.
type CategoryBudgetEditResponse struct {
	Id string `json:"id"`
}

// CategoryCreateRequest defines model for CategoryCreateRequest.
type CategoryCreateRequest struct {
	Name string `json:"name"`
}

// CategoryCreateResponse defines model for CategoryCreateResponse.
type CategoryCreateResponse struct {
	Id string `json:"id"`
}

// CategoryDeleteResponse defines model for CategoryDeleteResponse.
type CategoryDeleteResponse struct {
	Id      string `json:"id"`
	Message string `json:"message"`
}

// CategoryEditRequest defines model for CategoryEditRequest.
type CategoryEditRequest struct {
	Name string `json:"name"`
}

// CategoryEditResponse defines model for CategoryEditResponse.
type CategoryEditResponse struct {
	Id string `json:"id"`
}

// CategoryEditRuleRequest defines model for CategoryEditRuleRequest.
type CategoryEditRuleRequest struct {
	AccountId   *string `json:"account_id,omitempty"`
	Description *string `json:"description,omitempty"`
	Rule        *string `json:"rule,omitempty"`
}

// CategoryEditRuleResponse defines model for CategoryEditRuleResponse.
type CategoryEditRuleResponse struct {
	Id string `json:"id"`
}

// CategoryRule defines model for CategoryRule.
type CategoryRule struct {
	Account     Account `json:"account"`
	Description *string `json:"description,omitempty"`
	Id          string  `json:"id"`
	Rule        string  `json:"rule"`
}

// CategorySpendingSeries defines model for CategorySpendingSeries.
type CategorySpendingSeries struct {
	Amounts  []SpendingDatapoint `json:"amounts"`
	Category *Category           `json:"category,omitempty"`
}

// CategorySpendingSummary defines model for CategorySpendingSummary.
type CategorySpendingSummary struct {
	Categories []CategorySpendingSeries `json:"categories"`
}

// CategorySummary defines model for CategorySummary.
type CategorySummary struct {
	Category   *Category `json:"category,omitempty"`
	Percentage float32   `json:"percentage"`
	Total      float32   `json:"total"`
}

// Conflict defines model for Conflict.
type Conflict struct {
	Message string `json:"message"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

// LoginResponse defines model for LoginResponse.
type LoginResponse struct {
	Id        string `json:"id"`
	MasterKey string `json:"master_key"`
	Salt      string `json:"salt"`
	Token     string `json:"token"`
}

// NotAuthorized defines model for NotAuthorized.
type NotAuthorized struct {
	Message *string `json:"message,omitempty"`
}

// NotFound defines model for NotFound.
type NotFound struct {
	Message *string `json:"message,omitempty"`
}

// PeriodUnit defines model for PeriodUnit.
type PeriodUnit string

// SignupRequest defines model for SignupRequest.
type SignupRequest struct {
	Email     string `json:"email"`
	MasterKey string `json:"master_key"`
	Password  string `json:"password"`
	Salt      string `json:"salt"`
}

// SignupResponse defines model for SignupResponse.
type SignupResponse struct {
	Message string `json:"message"`
}

// SpendingDatapoint defines model for SpendingDatapoint.
type SpendingDatapoint struct {
	Amount float32   `json:"amount"`
	Date   time.Time `json:"date"`
}

// SummaryInterval defines model for SummaryInterval.
type SummaryInterval string

// TimePeriod defines model for TimePeriod.
type TimePeriod string

// TotalsSummary defines model for TotalsSummary.
type TotalsSummary struct {
	Income   float32 `json:"income"`
	Net      float32 `json:"net"`
	Outgoing float32 `json:"outgoing"`
}

// Transaction defines model for Transaction.
type Transaction struct {
	Account     Account            `json:"account"`
	Amount      float32            `json:"amount"`
	Category    *Category          `json:"category,omitempty"`
	CreatedAt   time.Time          `json:"created_at"`
	Date        openapi_types.Date `json:"date"`
	Description string             `json:"description"`
	Id          string             `json:"id"`
}

// TransactionBulkCreateRequest defines model for TransactionBulkCreateRequest.
type TransactionBulkCreateRequest struct {
	Hash         string                     `json:"hash"`
	Transactions []TransactionCreateRequest `json:"transactions"`
}

// TransactionBulkDeleteRequest defines model for TransactionBulkDeleteRequest.
type TransactionBulkDeleteRequest struct {
	Cancel *bool  `json:"cancel,omitempty"`
	Hash   string `json:"hash"`
}

// TransactionBulkFinaliseRequest defines model for TransactionBulkFinaliseRequest.
type TransactionBulkFinaliseRequest struct {
	Hash string `json:"hash"`
}

// TransactionBulkResponse defines model for TransactionBulkResponse.
type TransactionBulkResponse struct {
	Message string `json:"message"`
}

// TransactionCreateRequest defines model for TransactionCreateRequest.
type TransactionCreateRequest struct {
	AccountId   string             `json:"account_id"`
	Amount      float32            `json:"amount"`
	CategoryId  *string            `json:"category_id,omitempty"`
	Date        openapi_types.Date `json:"date"`
	Description string             `json:"description"`
}

// TransactionCreateResponse defines model for TransactionCreateResponse.
type TransactionCreateResponse struct {
	Id string `json:"id"`
}

// TransactionDeleteResponse defines model for TransactionDeleteResponse.
type TransactionDeleteResponse struct {
	Id      string `json:"id"`
	Message string `json:"message"`
}

// TransactionEditRequest defines model for TransactionEditRequest.
type TransactionEditRequest struct {
	AccountId   *string             `json:"account_id,omitempty"`
	Amount      *float32            `json:"amount,omitempty"`
	CategoryId  *string             `json:"category_id,omitempty"`
	Date        *openapi_types.Date `json:"date,omitempty"`
	Description *string             `json:"description,omitempty"`
}

// TransactionEditResponse defines model for TransactionEditResponse.
type TransactionEditResponse struct {
	Id string `json:"id"`
}

// TransactionsResponse defines model for TransactionsResponse.
type TransactionsResponse struct {
	Cursor       *string       `json:"cursor,omitempty"`
	Transactions []Transaction `json:"transactions"`
}

// User defines model for User.
type User struct {
	CreatedAt time.Time `json:"created_at"`
	Email     string    `json:"email"`
	Id        string    `json:"id"`
}

// GetUserIdSummaryBalanceParams defines parameters for GetUserIdSummaryBalance.
type GetUserIdSummaryBalanceParams struct {
	Interval  *SummaryInterval    `form:"interval,omitempty" json:"interval,omitempty"`
	StartDate *openapi_types.Date `form:"start_date,omitempty" json:"start_date,omitempty"`
	EndDate   *openapi_types.Date `form:"end_date,omitempty" json:"end_date,omitempty"`
}

// GetUserIdSummaryCategoriesParams defines parameters for GetUserIdSummaryCategories.
type GetUserIdSummaryCategoriesParams struct {
	StartDate *openapi_types.Date `form:"start_date,omitempty" json:"start_date,omitempty"`
	EndDate   *openapi_types.Date `form:"end_date,omitempty" json:"end_date,omitempty"`
}

// GetUserIdSummaryCategoriesSpendingParams defines parameters for GetUserIdSummaryCategoriesSpending.
type GetUserIdSummaryCategoriesSpendingParams struct {
	Interval  *SummaryInterval    `form:"interval,omitempty" json:"interval,omitempty"`
	StartDate *openapi_types.Date `form:"start_date,omitempty" json:"start_date,omitempty"`
	EndDate   *openapi_types.Date `form:"end_date,omitempty" json:"end_date,omitempty"`
}

// GetUserIdSummaryTotalsParams defines parameters for GetUserIdSummaryTotals.
type GetUserIdSummaryTotalsParams struct {
	StartDate *openapi_types.Date `form:"start_date,omitempty" json:"start_date,omitempty"`
	EndDate   *openapi_types.Date `form:"end_date,omitempty" json:"end_date,omitempty"`
}

// GetUserIdTransactionsParams defines parameters for GetUserIdTransactions.
type GetUserIdTransactionsParams struct {
	AccountId  *string             `form:"account_id,omitempty" json:"account_id,omitempty"`
	CategoryId *string             `form:"category_id,omitempty" json:"category_id,omitempty"`
	Period     *TimePeriod         `form:"period,omitempty" json:"period,omitempty"`
	StartDate  *openapi_types.Date `form:"start_date,omitempty" json:"start_date,omitempty"`
	EndDate    *openapi_types.Date `form:"end_date,omitempty" json:"end_date,omitempty"`
	Cursor     *string             `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit      *int                `form:"limit,omitempty" json:"limit,omitempty"`
}

// PostLoginJSONRequestBody defines body for PostLogin for application/json ContentType.
type PostLoginJSONRequestBody = LoginRequest

// PostSignupJSONRequestBody defines body for PostSignup for application/json ContentType.
type PostSignupJSONRequestBody = SignupRequest

// PostUserIdAccountsJSONRequestBody defines body for PostUserIdAccounts for application/json ContentType.
type PostUserIdAccountsJSONRequestBody = AccountCreateRequest

// PatchUserIdAccountsAccountIdJSONRequestBody defines body for PatchUserIdAccountsAccountId for application/json ContentType.
type PatchUserIdAccountsAccountIdJSONRequestBody = AccountEditRequest

// PostUserIdBudgetTransactionsJSONRequestBody defines body for PostUserIdBudgetTransactions for application/json ContentType.
type PostUserIdBudgetTransactionsJSONRequestBody = BudgetTransactionCreateRequest

// PatchUserIdBudgetTransactionsBudgetTransactionIdJSONRequestBody defines body for PatchUserIdBudgetTransactionsBudgetTransactionId for application/json ContentType.
type PatchUserIdBudgetTransactionsBudgetTransactionIdJSONRequestBody = BudgetTransactionEditRequest

// PostUserIdCategoriesJSONRequestBody defines body for PostUserIdCategories for application/json ContentType.
type PostUserIdCategoriesJSONRequestBody = CategoryCreateRequest

// PatchUserIdCategoriesCategoryIdJSONRequestBody defines body for PatchUserIdCategoriesCategoryId for application/json ContentType.
type PatchUserIdCategoriesCategoryIdJSONRequestBody = CategoryEditRequest

// PostUserIdCategoriesCategoryIdRulesJSONRequestBody defines body for PostUserIdCategoriesCategoryIdRules for application/json ContentType.
type PostUserIdCategoriesCategoryIdRulesJSONRequestBody = CategoryAddRuleRequest

// PatchUserIdCategoriesCategoryIdRulesRuleIdJSONRequestBody defines body for PatchUserIdCategoriesCategoryIdRulesRuleId for application/json ContentType.
type PatchUserIdCategoriesCategoryIdRulesRuleIdJSONRequestBody = CategoryEditRuleRequest

// PostUserIdCategoryBudgetsJSONRequestBody defines body for PostUserIdCategoryBudgets for application/json ContentType.
type PostUserIdCategoryBudgetsJSONRequestBody = CategoryBudgetCreateRequest

// PatchUserIdCategoryBudgetsCategoryBudgetIdJSONRequestBody defines body for PatchUserIdCategoryBudgetsCategoryBudgetId for application/json ContentType.
type PatchUserIdCategoryBudgetsCategoryBudgetIdJSONRequestBody = CategoryBudgetEditRequest

// PostUserIdTransactionsJSONRequestBody defines body for PostUserIdTransactions for application/json ContentType.
type PostUserIdTransactionsJSONRequestBody = TransactionCreateRequest

// PostUserIdTransactionsBulkJSONRequestBody defines body for PostUserIdTransactionsBulk for application/json ContentType.
type PostUserIdTransactionsBulkJSONRequestBody = TransactionBulkCreateRequest

// PostUserIdTransactionsBulkDeleteJSONRequestBody defines body for PostUserIdTransactionsBulkDelete for application/json ContentType.
type PostUserIdTransactionsBulkDeleteJSONRequestBody = TransactionBulkDeleteRequest

// PostUserIdTransactionsBulkFinaliseJSONRequestBody defines body for PostUserIdTransactionsBulkFinalise for application/json ContentType.
type PostUserIdTransactionsBulkFinaliseJSONRequestBody = TransactionBulkFinaliseRequest

// PatchUserIdTransactionsTransactionIdJSONRequestBody defines body for PatchUserIdTransactionsTransactionId for application/json ContentType.
type PatchUserIdTransactionsTransactionIdJSONRequestBody = TransactionEditRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /banks)
	GetBanks(c *fiber.Ctx) error

	// (POST /login)
	PostLogin(c *fiber.Ctx) error

	// (POST /signup)
	PostSignup(c *fiber.Ctx) error

	// (GET /user/{id})
	GetUserId(c *fiber.Ctx, id string) error

	// (GET /user/{id}/accounts)
	GetUserIdAccounts(c *fiber.Ctx, id string) error

	// (POST /user/{id}/accounts)
	PostUserIdAccounts(c *fiber.Ctx, id string) error

	// (DELETE /user/{id}/accounts/{account_id})
	DeleteUserIdAccountsAccountId(c *fiber.Ctx, id string, accountId string) error

	// (GET /user/{id}/accounts/{account_id})
	GetUserIdAccountsAccountId(c *fiber.Ctx, id string, accountId string) error

	// (PATCH /user/{id}/accounts/{account_id})
	PatchUserIdAccountsAccountId(c *fiber.Ctx, id string, accountId string) error

	// (GET /user/{id}/budget-transactions)
	GetUserIdBudgetTransactions(c *fiber.Ctx, id string) error

	// (POST /user/{id}/budget-transactions)
	PostUserIdBudgetTransactions(c *fiber.Ctx, id string) error

	// (DELETE /user/{id}/budget-transactions/{budget_transaction_id})
	DeleteUserIdBudgetTransactionsBudgetTransactionId(c *fiber.Ctx, id string, budgetTransactionId string) error

	// (GET /user/{id}/budget-transactions/{budget_transaction_id})
	GetUserIdBudgetTransactionsBudgetTransactionId(c *fiber.Ctx, id string, budgetTransactionId string) error

	// (PATCH /user/{id}/budget-transactions/{budget_transaction_id})
	PatchUserIdBudgetTransactionsBudgetTransactionId(c *fiber.Ctx, id string, budgetTransactionId string) error

	// (GET /user/{id}/categories)
	GetUserIdCategories(c *fiber.Ctx, id string) error

	// (POST /user/{id}/categories)
	PostUserIdCategories(c *fiber.Ctx, id string) error

	// (DELETE /user/{id}/categories/{category_id})
	DeleteUserIdCategoriesCategoryId(c *fiber.Ctx, id string, categoryId string) error

	// (GET /user/{id}/categories/{category_id})
	GetUserIdCategoriesCategoryId(c *fiber.Ctx, id string, categoryId string) error

	// (PATCH /user/{id}/categories/{category_id})
	PatchUserIdCategoriesCategoryId(c *fiber.Ctx, id string, categoryId string) error

	// (POST /user/{id}/categories/{category_id}/rules)
	PostUserIdCategoriesCategoryIdRules(c *fiber.Ctx, id string, categoryId string) error

	// (DELETE /user/{id}/categories/{category_id}/rules/{rule_id})
	DeleteUserIdCategoriesCategoryIdRulesRuleId(c *fiber.Ctx, id string, categoryId string, ruleId string) error

	// (PATCH /user/{id}/categories/{category_id}/rules/{rule_id})
	PatchUserIdCategoriesCategoryIdRulesRuleId(c *fiber.Ctx, id string, categoryId string, ruleId string) error

	// (GET /user/{id}/category-budgets)
	GetUserIdCategoryBudgets(c *fiber.Ctx, id string) error

	// (POST /user/{id}/category-budgets)
	PostUserIdCategoryBudgets(c *fiber.Ctx, id string) error

	// (DELETE /user/{id}/category-budgets/{category_budget_id})
	DeleteUserIdCategoryBudgetsCategoryBudgetId(c *fiber.Ctx, id string, categoryBudgetId string) error

	// (GET /user/{id}/category-budgets/{category_budget_id})
	GetUserIdCategoryBudgetsCategoryBudgetId(c *fiber.Ctx, id string, categoryBudgetId string) error

	// (PATCH /user/{id}/category-budgets/{category_budget_id})
	PatchUserIdCategoryBudgetsCategoryBudgetId(c *fiber.Ctx, id string, categoryBudgetId string) error

	// (GET /user/{id}/summary/accounts)
	GetUserIdSummaryAccounts(c *fiber.Ctx, id string) error

	// (GET /user/{id}/summary/balance)
	GetUserIdSummaryBalance(c *fiber.Ctx, id string, params GetUserIdSummaryBalanceParams) error

	// (GET /user/{id}/summary/categories)
	GetUserIdSummaryCategories(c *fiber.Ctx, id string, params GetUserIdSummaryCategoriesParams) error

	// (GET /user/{id}/summary/categories/spending)
	GetUserIdSummaryCategoriesSpending(c *fiber.Ctx, id string, params GetUserIdSummaryCategoriesSpendingParams) error

	// (GET /user/{id}/summary/totals)
	GetUserIdSummaryTotals(c *fiber.Ctx, id string, params GetUserIdSummaryTotalsParams) error

	// (GET /user/{id}/transactions)
	GetUserIdTransactions(c *fiber.Ctx, id string, params GetUserIdTransactionsParams) error

	// (POST /user/{id}/transactions)
	PostUserIdTransactions(c *fiber.Ctx, id string) error

	// (POST /user/{id}/transactions/bulk)
	PostUserIdTransactionsBulk(c *fiber.Ctx, id string) error

	// (POST /user/{id}/transactions/bulk/delete)
	PostUserIdTransactionsBulkDelete(c *fiber.Ctx, id string) error

	// (POST /user/{id}/transactions/bulk/finalise)
	PostUserIdTransactionsBulkFinalise(c *fiber.Ctx, id string) error

	// (DELETE /user/{id}/transactions/{transaction_id})
	DeleteUserIdTransactionsTransactionId(c *fiber.Ctx, id string, transactionId string) error

	// (GET /user/{id}/transactions/{transaction_id})
	GetUserIdTransactionsTransactionId(c *fiber.Ctx, id string, transactionId string) error

	// (PATCH /user/{id}/transactions/{transaction_id})
	PatchUserIdTransactionsTransactionId(c *fiber.Ctx, id string, transactionId string) error
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

type MiddlewareFunc fiber.Handler

// GetBanks operation middleware
func (siw *ServerInterfaceWrapper) GetBanks(c *fiber.Ctx) error {

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.GetBanks(c)
}

// PostLogin operation middleware
func (siw *ServerInterfaceWrapper) PostLogin(c *fiber.Ctx) error {

	return siw.Handler.PostLogin(c)
}

// PostSignup operation middleware
func (siw *ServerInterfaceWrapper) PostSignup(c *fiber.Ctx) error {

	return siw.Handler.PostSignup(c)
}

// GetUserId operation middleware
func (siw *ServerInterfaceWrapper) GetUserId(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.GetUserId(c, id)
}

// GetUserIdAccounts operation middleware
func (siw *ServerInterfaceWrapper) GetUserIdAccounts(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.GetUserIdAccounts(c, id)
}

// PostUserIdAccounts operation middleware
func (siw *ServerInterfaceWrapper) PostUserIdAccounts(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.PostUserIdAccounts(c, id)
}

// DeleteUserIdAccountsAccountId operation middleware
func (siw *ServerInterfaceWrapper) DeleteUserIdAccountsAccountId(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	// ------------- Path parameter "account_id" -------------
	var accountId string

	err = runtime.BindStyledParameterWithOptions("simple", "account_id", c.Params("account_id"), &accountId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter account_id: %w", err).Error())
	}

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.DeleteUserIdAccountsAccountId(c, id, accountId)
}

// GetUserIdAccountsAccountId operation middleware
func (siw *ServerInterfaceWrapper) GetUserIdAccountsAccountId(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	// ------------- Path parameter "account_id" -------------
	var accountId string

	err = runtime.BindStyledParameterWithOptions("simple", "account_id", c.Params("account_id"), &accountId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter account_id: %w", err).Error())
	}

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.GetUserIdAccountsAccountId(c, id, accountId)
}

// PatchUserIdAccountsAccountId operation middleware
func (siw *ServerInterfaceWrapper) PatchUserIdAccountsAccountId(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	// ------------- Path parameter "account_id" -------------
	var accountId string

	err = runtime.BindStyledParameterWithOptions("simple", "account_id", c.Params("account_id"), &accountId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter account_id: %w", err).Error())
	}

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.PatchUserIdAccountsAccountId(c, id, accountId)
}

// GetUserIdBudgetTransactions operation middleware
func (siw *ServerInterfaceWrapper) GetUserIdBudgetTransactions(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.GetUserIdBudgetTransactions(c, id)
}

// PostUserIdBudgetTransactions operation middleware
func (siw *ServerInterfaceWrapper) PostUserIdBudgetTransactions(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.PostUserIdBudgetTransactions(c, id)
}

// DeleteUserIdBudgetTransactionsBudgetTransactionId operation middleware
func (siw *ServerInterfaceWrapper) DeleteUserIdBudgetTransactionsBudgetTransactionId(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	// ------------- Path parameter "budget_transaction_id" -------------
	var budgetTransactionId string

	err = runtime.BindStyledParameterWithOptions("simple", "budget_transaction_id", c.Params("budget_transaction_id"), &budgetTransactionId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter budget_transaction_id: %w", err).Error())
	}

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.DeleteUserIdBudgetTransactionsBudgetTransactionId(c, id, budgetTransactionId)
}

// GetUserIdBudgetTransactionsBudgetTransactionId operation middleware
func (siw *ServerInterfaceWrapper) GetUserIdBudgetTransactionsBudgetTransactionId(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	// ------------- Path parameter "budget_transaction_id" -------------
	var budgetTransactionId string

	err = runtime.BindStyledParameterWithOptions("simple", "budget_transaction_id", c.Params("budget_transaction_id"), &budgetTransactionId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter budget_transaction_id: %w", err).Error())
	}

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.GetUserIdBudgetTransactionsBudgetTransactionId(c, id, budgetTransactionId)
}

// PatchUserIdBudgetTransactionsBudgetTransactionId operation middleware
func (siw *ServerInterfaceWrapper) PatchUserIdBudgetTransactionsBudgetTransactionId(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	// ------------- Path parameter "budget_transaction_id" -------------
	var budgetTransactionId string

	err = runtime.BindStyledParameterWithOptions("simple", "budget_transaction_id", c.Params("budget_transaction_id"), &budgetTransactionId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter budget_transaction_id: %w", err).Error())
	}

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.PatchUserIdBudgetTransactionsBudgetTransactionId(c, id, budgetTransactionId)
}

// GetUserIdCategories operation middleware
func (siw *ServerInterfaceWrapper) GetUserIdCategories(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.GetUserIdCategories(c, id)
}

// PostUserIdCategories operation middleware
func (siw *ServerInterfaceWrapper) PostUserIdCategories(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.PostUserIdCategories(c, id)
}

// DeleteUserIdCategoriesCategoryId operation middleware
func (siw *ServerInterfaceWrapper) DeleteUserIdCategoriesCategoryId(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	// ------------- Path parameter "category_id" -------------
	var categoryId string

	err = runtime.BindStyledParameterWithOptions("simple", "category_id", c.Params("category_id"), &categoryId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter category_id: %w", err).Error())
	}

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.DeleteUserIdCategoriesCategoryId(c, id, categoryId)
}

// GetUserIdCategoriesCategoryId operation middleware
func (siw *ServerInterfaceWrapper) GetUserIdCategoriesCategoryId(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	// ------------- Path parameter "category_id" -------------
	var categoryId string

	err = runtime.BindStyledParameterWithOptions("simple", "category_id", c.Params("category_id"), &categoryId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter category_id: %w", err).Error())
	}

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.GetUserIdCategoriesCategoryId(c, id, categoryId)
}

// PatchUserIdCategoriesCategoryId operation middleware
func (siw *ServerInterfaceWrapper) PatchUserIdCategoriesCategoryId(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	// ------------- Path parameter "category_id" -------------
	var categoryId string

	err = runtime.BindStyledParameterWithOptions("simple", "category_id", c.Params("category_id"), &categoryId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter category_id: %w", err).Error())
	}

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.PatchUserIdCategoriesCategoryId(c, id, categoryId)
}

// PostUserIdCategoriesCategoryIdRules operation middleware
func (siw *ServerInterfaceWrapper) PostUserIdCategoriesCategoryIdRules(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	// ------------- Path parameter "category_id" -------------
	var categoryId string

	err = runtime.BindStyledParameterWithOptions("simple", "category_id", c.Params("category_id"), &categoryId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter category_id: %w", err).Error())
	}

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.PostUserIdCategoriesCategoryIdRules(c, id, categoryId)
}

// DeleteUserIdCategoriesCategoryIdRulesRuleId operation middleware
func (siw *ServerInterfaceWrapper) DeleteUserIdCategoriesCategoryIdRulesRuleId(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	// ------------- Path parameter "category_id" -------------
	var categoryId string

	err = runtime.BindStyledParameterWithOptions("simple", "category_id", c.Params("category_id"), &categoryId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter category_id: %w", err).Error())
	}

	// ------------- Path parameter "rule_id" -------------
	var ruleId string

	err = runtime.BindStyledParameterWithOptions("simple", "rule_id", c.Params("rule_id"), &ruleId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter rule_id: %w", err).Error())
	}

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.DeleteUserIdCategoriesCategoryIdRulesRuleId(c, id, categoryId, ruleId)
}

// PatchUserIdCategoriesCategoryIdRulesRuleId operation middleware
func (siw *ServerInterfaceWrapper) PatchUserIdCategoriesCategoryIdRulesRuleId(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	// ------------- Path parameter "category_id" -------------
	var categoryId string

	err = runtime.BindStyledParameterWithOptions("simple", "category_id", c.Params("category_id"), &categoryId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter category_id: %w", err).Error())
	}

	// ------------- Path parameter "rule_id" -------------
	var ruleId string

	err = runtime.BindStyledParameterWithOptions("simple", "rule_id", c.Params("rule_id"), &ruleId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter rule_id: %w", err).Error())
	}

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.PatchUserIdCategoriesCategoryIdRulesRuleId(c, id, categoryId, ruleId)
}

// GetUserIdCategoryBudgets operation middleware
func (siw *ServerInterfaceWrapper) GetUserIdCategoryBudgets(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.GetUserIdCategoryBudgets(c, id)
}

// PostUserIdCategoryBudgets operation middleware
func (siw *ServerInterfaceWrapper) PostUserIdCategoryBudgets(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.PostUserIdCategoryBudgets(c, id)
}

// DeleteUserIdCategoryBudgetsCategoryBudgetId operation middleware
func (siw *ServerInterfaceWrapper) DeleteUserIdCategoryBudgetsCategoryBudgetId(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	// ------------- Path parameter "category_budget_id" -------------
	var categoryBudgetId string

	err = runtime.BindStyledParameterWithOptions("simple", "category_budget_id", c.Params("category_budget_id"), &categoryBudgetId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter category_budget_id: %w", err).Error())
	}

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.DeleteUserIdCategoryBudgetsCategoryBudgetId(c, id, categoryBudgetId)
}

// GetUserIdCategoryBudgetsCategoryBudgetId operation middleware
func (siw *ServerInterfaceWrapper) GetUserIdCategoryBudgetsCategoryBudgetId(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	// ------------- Path parameter "category_budget_id" -------------
	var categoryBudgetId string

	err = runtime.BindStyledParameterWithOptions("simple", "category_budget_id", c.Params("category_budget_id"), &categoryBudgetId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter category_budget_id: %w", err).Error())
	}

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.GetUserIdCategoryBudgetsCategoryBudgetId(c, id, categoryBudgetId)
}

// PatchUserIdCategoryBudgetsCategoryBudgetId operation middleware
func (siw *ServerInterfaceWrapper) PatchUserIdCategoryBudgetsCategoryBudgetId(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	// ------------- Path parameter "category_budget_id" -------------
	var categoryBudgetId string

	err = runtime.BindStyledParameterWithOptions("simple", "category_budget_id", c.Params("category_budget_id"), &categoryBudgetId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter category_budget_id: %w", err).Error())
	}

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.PatchUserIdCategoryBudgetsCategoryBudgetId(c, id, categoryBudgetId)
}

// GetUserIdSummaryAccounts operation middleware
func (siw *ServerInterfaceWrapper) GetUserIdSummaryAccounts(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.GetUserIdSummaryAccounts(c, id)
}

// GetUserIdSummaryBalance operation middleware
func (siw *ServerInterfaceWrapper) GetUserIdSummaryBalance(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetUserIdSummaryBalanceParams

	var query url.Values
	query, err = url.ParseQuery(string(c.Request().URI().QueryString()))
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for query string: %w", err).Error())
	}

	// ------------- Optional query parameter "interval" -------------

	err = runtime.BindQueryParameter("form", true, false, "interval", query, &params.Interval)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter interval: %w", err).Error())
	}

	// ------------- Optional query parameter "start_date" -------------

	err = runtime.BindQueryParameter("form", true, false, "start_date", query, &params.StartDate)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter start_date: %w", err).Error())
	}

	// ------------- Optional query parameter "end_date" -------------

	err = runtime.BindQueryParameter("form", true, false, "end_date", query, &params.EndDate)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter end_date: %w", err).Error())
	}

	return siw.Handler.GetUserIdSummaryBalance(c, id, params)
}

// GetUserIdSummaryCategories operation middleware
func (siw *ServerInterfaceWrapper) GetUserIdSummaryCategories(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetUserIdSummaryCategoriesParams

	var query url.Values
	query, err = url.ParseQuery(string(c.Request().URI().QueryString()))
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for query string: %w", err).Error())
	}

	// ------------- Optional query parameter "start_date" -------------

	err = runtime.BindQueryParameter("form", true, false, "start_date", query, &params.StartDate)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter start_date: %w", err).Error())
	}

	// ------------- Optional query parameter "end_date" -------------

	err = runtime.BindQueryParameter("form", true, false, "end_date", query, &params.EndDate)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter end_date: %w", err).Error())
	}

	return siw.Handler.GetUserIdSummaryCategories(c, id, params)
}

// GetUserIdSummaryCategoriesSpending operation middleware
func (siw *ServerInterfaceWrapper) GetUserIdSummaryCategoriesSpending(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetUserIdSummaryCategoriesSpendingParams

	var query url.Values
	query, err = url.ParseQuery(string(c.Request().URI().QueryString()))
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for query string: %w", err).Error())
	}

	// ------------- Optional query parameter "interval" -------------

	err = runtime.BindQueryParameter("form", true, false, "interval", query, &params.Interval)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter interval: %w", err).Error())
	}

	// ------------- Optional query parameter "start_date" -------------

	err = runtime.BindQueryParameter("form", true, false, "start_date", query, &params.StartDate)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter start_date: %w", err).Error())
	}

	// ------------- Optional query parameter "end_date" -------------

	err = runtime.BindQueryParameter("form", true, false, "end_date", query, &params.EndDate)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter end_date: %w", err).Error())
	}

	return siw.Handler.GetUserIdSummaryCategoriesSpending(c, id, params)
}

// GetUserIdSummaryTotals operation middleware
func (siw *ServerInterfaceWrapper) GetUserIdSummaryTotals(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetUserIdSummaryTotalsParams

	var query url.Values
	query, err = url.ParseQuery(string(c.Request().URI().QueryString()))
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for query string: %w", err).Error())
	}

	// ------------- Optional query parameter "start_date" -------------

	err = runtime.BindQueryParameter("form", true, false, "start_date", query, &params.StartDate)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter start_date: %w", err).Error())
	}

	// ------------- Optional query parameter "end_date" -------------

	err = runtime.BindQueryParameter("form", true, false, "end_date", query, &params.EndDate)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter end_date: %w", err).Error())
	}

	return siw.Handler.GetUserIdSummaryTotals(c, id, params)
}

// GetUserIdTransactions operation middleware
func (siw *ServerInterfaceWrapper) GetUserIdTransactions(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetUserIdTransactionsParams

	var query url.Values
	query, err = url.ParseQuery(string(c.Request().URI().QueryString()))
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for query string: %w", err).Error())
	}

	// ------------- Optional query parameter "account_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "account_id", query, &params.AccountId)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter account_id: %w", err).Error())
	}

	// ------------- Optional query parameter "category_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "category_id", query, &params.CategoryId)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter category_id: %w", err).Error())
	}

	// ------------- Optional query parameter "period" -------------

	err = runtime.BindQueryParameter("form", true, false, "period", query, &params.Period)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter period: %w", err).Error())
	}

	// ------------- Optional query parameter "start_date" -------------

	err = runtime.BindQueryParameter("form", true, false, "start_date", query, &params.StartDate)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter start_date: %w", err).Error())
	}

	// ------------- Optional query parameter "end_date" -------------

	err = runtime.BindQueryParameter("form", true, false, "end_date", query, &params.EndDate)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter end_date: %w", err).Error())
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameter("form", true, false, "cursor", query, &params.Cursor)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter cursor: %w", err).Error())
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", query, &params.Limit)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter limit: %w", err).Error())
	}

	return siw.Handler.GetUserIdTransactions(c, id, params)
}

// PostUserIdTransactions operation middleware
func (siw *ServerInterfaceWrapper) PostUserIdTransactions(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.PostUserIdTransactions(c, id)
}

// PostUserIdTransactionsBulk operation middleware
func (siw *ServerInterfaceWrapper) PostUserIdTransactionsBulk(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.PostUserIdTransactionsBulk(c, id)
}

// PostUserIdTransactionsBulkDelete operation middleware
func (siw *ServerInterfaceWrapper) PostUserIdTransactionsBulkDelete(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.PostUserIdTransactionsBulkDelete(c, id)
}

// PostUserIdTransactionsBulkFinalise operation middleware
func (siw *ServerInterfaceWrapper) PostUserIdTransactionsBulkFinalise(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.PostUserIdTransactionsBulkFinalise(c, id)
}

// DeleteUserIdTransactionsTransactionId operation middleware
func (siw *ServerInterfaceWrapper) DeleteUserIdTransactionsTransactionId(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	// ------------- Path parameter "transaction_id" -------------
	var transactionId string

	err = runtime.BindStyledParameterWithOptions("simple", "transaction_id", c.Params("transaction_id"), &transactionId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter transaction_id: %w", err).Error())
	}

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.DeleteUserIdTransactionsTransactionId(c, id, transactionId)
}

// GetUserIdTransactionsTransactionId operation middleware
func (siw *ServerInterfaceWrapper) GetUserIdTransactionsTransactionId(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	// ------------- Path parameter "transaction_id" -------------
	var transactionId string

	err = runtime.BindStyledParameterWithOptions("simple", "transaction_id", c.Params("transaction_id"), &transactionId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter transaction_id: %w", err).Error())
	}

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.GetUserIdTransactionsTransactionId(c, id, transactionId)
}

// PatchUserIdTransactionsTransactionId operation middleware
func (siw *ServerInterfaceWrapper) PatchUserIdTransactionsTransactionId(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	// ------------- Path parameter "transaction_id" -------------
	var transactionId string

	err = runtime.BindStyledParameterWithOptions("simple", "transaction_id", c.Params("transaction_id"), &transactionId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter transaction_id: %w", err).Error())
	}

	c.Context().SetUserValue(BearerAuthScopes, []string{})

	return siw.Handler.PatchUserIdTransactionsTransactionId(c, id, transactionId)
}

// FiberServerOptions provides options for the Fiber server.
type FiberServerOptions struct {
	BaseURL     string
	Middlewares []MiddlewareFunc
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router fiber.Router, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, FiberServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router fiber.Router, si ServerInterface, options FiberServerOptions) {
	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	for _, m := range options.Middlewares {
		router.Use(fiber.Handler(m))
	}

	router.Get(options.BaseURL+"/banks", wrapper.GetBanks)

	router.Post(options.BaseURL+"/login", wrapper.PostLogin)

	router.Post(options.BaseURL+"/signup", wrapper.PostSignup)

	router.Get(options.BaseURL+"/user/:id", wrapper.GetUserId)

	router.Get(options.BaseURL+"/user/:id/accounts", wrapper.GetUserIdAccounts)

	router.Post(options.BaseURL+"/user/:id/accounts", wrapper.PostUserIdAccounts)

	router.Delete(options.BaseURL+"/user/:id/accounts/:account_id", wrapper.DeleteUserIdAccountsAccountId)

	router.Get(options.BaseURL+"/user/:id/accounts/:account_id", wrapper.GetUserIdAccountsAccountId)

	router.Patch(options.BaseURL+"/user/:id/accounts/:account_id", wrapper.PatchUserIdAccountsAccountId)

	router.Get(options.BaseURL+"/user/:id/budget-transactions", wrapper.GetUserIdBudgetTransactions)

	router.Post(options.BaseURL+"/user/:id/budget-transactions", wrapper.PostUserIdBudgetTransactions)

	router.Delete(options.BaseURL+"/user/:id/budget-transactions/:budget_transaction_id", wrapper.DeleteUserIdBudgetTransactionsBudgetTransactionId)

	router.Get(options.BaseURL+"/user/:id/budget-transactions/:budget_transaction_id", wrapper.GetUserIdBudgetTransactionsBudgetTransactionId)

	router.Patch(options.BaseURL+"/user/:id/budget-transactions/:budget_transaction_id", wrapper.PatchUserIdBudgetTransactionsBudgetTransactionId)

	router.Get(options.BaseURL+"/user/:id/categories", wrapper.GetUserIdCategories)

	router.Post(options.BaseURL+"/user/:id/categories", wrapper.PostUserIdCategories)

	router.Delete(options.BaseURL+"/user/:id/categories/:category_id", wrapper.DeleteUserIdCategoriesCategoryId)

	router.Get(options.BaseURL+"/user/:id/categories/:category_id", wrapper.GetUserIdCategoriesCategoryId)

	router.Patch(options.BaseURL+"/user/:id/categories/:category_id", wrapper.PatchUserIdCategoriesCategoryId)

	router.Post(options.BaseURL+"/user/:id/categories/:category_id/rules", wrapper.PostUserIdCategoriesCategoryIdRules)

	router.Delete(options.BaseURL+"/user/:id/categories/:category_id/rules/:rule_id", wrapper.DeleteUserIdCategoriesCategoryIdRulesRuleId)

	router.Patch(options.BaseURL+"/user/:id/categories/:category_id/rules/:rule_id", wrapper.PatchUserIdCategoriesCategoryIdRulesRuleId)

	router.Get(options.BaseURL+"/user/:id/category-budgets", wrapper.GetUserIdCategoryBudgets)

	router.Post(options.BaseURL+"/user/:id/category-budgets", wrapper.PostUserIdCategoryBudgets)

	router.Delete(options.BaseURL+"/user/:id/category-budgets/:category_budget_id", wrapper.DeleteUserIdCategoryBudgetsCategoryBudgetId)

	router.Get(options.BaseURL+"/user/:id/category-budgets/:category_budget_id", wrapper.GetUserIdCategoryBudgetsCategoryBudgetId)

	router.Patch(options.BaseURL+"/user/:id/category-budgets/:category_budget_id", wrapper.PatchUserIdCategoryBudgetsCategoryBudgetId)

	router.Get(options.BaseURL+"/user/:id/summary/accounts", wrapper.GetUserIdSummaryAccounts)

	router.Get(options.BaseURL+"/user/:id/summary/balance", wrapper.GetUserIdSummaryBalance)

	router.Get(options.BaseURL+"/user/:id/summary/categories", wrapper.GetUserIdSummaryCategories)

	router.Get(options.BaseURL+"/user/:id/summary/categories/spending", wrapper.GetUserIdSummaryCategoriesSpending)

	router.Get(options.BaseURL+"/user/:id/summary/totals", wrapper.GetUserIdSummaryTotals)

	router.Get(options.BaseURL+"/user/:id/transactions", wrapper.GetUserIdTransactions)

	router.Post(options.BaseURL+"/user/:id/transactions", wrapper.PostUserIdTransactions)

	router.Post(options.BaseURL+"/user/:id/transactions/bulk", wrapper.PostUserIdTransactionsBulk)

	router.Post(options.BaseURL+"/user/:id/transactions/bulk/delete", wrapper.PostUserIdTransactionsBulkDelete)

	router.Post(options.BaseURL+"/user/:id/transactions/bulk/finalise", wrapper.PostUserIdTransactionsBulkFinalise)

	router.Delete(options.BaseURL+"/user/:id/transactions/:transaction_id", wrapper.DeleteUserIdTransactionsTransactionId)

	router.Get(options.BaseURL+"/user/:id/transactions/:transaction_id", wrapper.GetUserIdTransactionsTransactionId)

	router.Patch(options.BaseURL+"/user/:id/transactions/:transaction_id", wrapper.PatchUserIdTransactionsTransactionId)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xd3XPbuBH/VzRsH5nIuV4f6qfGuaaTzs1NJnGmD5mMBiZXEk4kwACgL65H/3sHACl+",
	"gSRAkzSl80tiW/jYjx92Fx+7evQCGieUABHcu370eLCHGKkf3wYBTYmQPyaMJsAEBvXBHSIH+f9fGWy9",
	"a+8v62KIddZ/fSPbHH0viCiHcIPUMFvKYvmTFyIBrwSOwfM98ZCAd+1xwTDZyS44lG0bfyYoBuMHNAHi",
	"NMXR9xh8TzGD0Lv+KufLRvc1a+Uhv51607vfIRBywkww7xggAZ/gewq8RUqbHl7gB4qTSH72bg/BAZPd",
	"Kpe6Pz6jJR43imknNnlCCYcmn0YWmyLumOEXiMB5Bt+LgXO0A6vZi9YddPwrxGKQOgeAfD4EdHM7nVY/",
	"p3GM2ENzaFTYlS4LkovhKBEbIRKUNU3S+A5YgyJ0El3exUhgFFnSqEUhIOaW1OYDFnJHjCH9OxUosmaB",
	"e3kPEwc3mrtfkEAJxWYb3SYyX+FloAlRXbulm9E2nmirA5Zg0Sphl2ELGTZGrPGuh/cLBvq5b3WhT1oD",
	"07Bnt3ZuMt9fYyfBGxwnlIkNEHQXQdl63FEaASLKUPJ7q3Zb/APCTcJomAYaKc02rmEC38tpWz7uCAlK",
	"/YwM+CbujaJLwx2IW4YIR4HAlBjkGOeoaCzaAAnYUb2guvT+Lm8n+yjX7eaYQuWMXfvwgOEk56nxOZCQ",
	"b/RnlQEdoj8GCSCxgXvQImjIJ2uQEoGjPhl9BIZp+IVgpRcuEBOW9JlwkimtRkKN5PI0FcVYIaUn1Cxg",
	"cwon3lxd+e0gagtkxlRkXWMFaf5CtOesOCddTRBZNeZ69si5QVFnDD0fTrdbCAS+h82W0dgKrouD9jCw",
	"1jh30NkEeH1X8lnVQYd4JleHz9II7KPMnNZPaQS9sVI5Piixks/ZJYu3YSinaF8jOgwbinxJgFlf/RRN",
	"iACNuYsJeC47oDlJforYpooI98Dmp0EO47IClzK3/jhhjFktk1uEZw9gquS4Ri8DwfgSnbRHJyaFTAjD",
	"HgNkd1ygWtnMMiEji1lJnWtoJHlODgs1wbLCtIKkCfn+lNH11NPKPv7bgqJWsTRPXU7HlapTF1OfEyAh",
	"JrvPwDKGTIbdfquQj9dxtjokfDWaVG7HWdthe0YFHrARqkmtb0tUmqmT4h5KncL9BFgARFTtV+HbLG9c",
	"8nP90mhGDijZRjgw2AJrG9plPn+lO0xazQ3ECEfGJZMgzv+gzGLp6zFKPTrIcPUiiAtgmwM8mI/eUSSM",
	"Hwh6AGK54HXbylzZyCY+fqPibSr2lOH/6UuGVpUFlEiJyx4rVHSxukr9jYr3NCX2E2xVa6uxS9HW9aMX",
	"whalUopeTInYy1iKpLG+kpOC+APgIIWTffgAiJXkUkj8M96RNOnHWXEvnXJg/8x+fR3Q2BRy9ui/A6Ot",
	"4OgDry0QcobbED3K4m16BJeTjqffx2aDG0nTBvcDEcDutTkssKSxMwxJtzgGjdHqmKpDMahpON97EMqH",
	"R5F5aGmReaurwCSgsdnkEzCLmKZiR+Xovd4gG7zURY9qkm33XZ5z0LSEwzATFIdc+VnGoqXTiyKgK4/t",
	"5xT0HCuVVHGTRoeebd0e8b3ZIRXD2EdMrRd1fTGTIqM2qQVz+VavhbkAkQCqC32LIg6+4RK9RRAmOi0I",
	"e48JijB3lvvA6SY26g73r92bwfGuvcZZneaHH7XDRMMitBTSBNvTJV15Wl92nh0o+lmdVrW8fYIgZZyy",
	"SUx2/7uvPvP8hQMb54qzfZtn7U/zQLnTX8qwG4KUYfHwWUpEU3wDiAGT2yb1glD99j6n+z//vZVhtmot",
	"fYj6tOBhL0TiHeXAmGypohULtX+QToEEsLplKDgAW739+MHzvXtgXAHRe/P66vVV/rgVJdi79v6m/iSD",
	"fbFXlK3vEDmon7JbRCloJDXyIfSuvX+DuFENpDw0hFTjn66usg2YAL3WUJJEOFA9179zvRA0Jhwe1umX",
	"7TXM1BeY9yvmYkW3K0360fd+vvrZiZouIk4bT8PExT6zrGfv+mtVw1+/Hb/JButIbvkVfik3CPcj5UKd",
	"CngabcDFDQ0fRmOlcvBxPGpQP0GJFnNlVsakNNlgxU4tpNbezKK1L6R0+PBMaFFw4GrD3I0HvameCBDV",
	"I4qJEVE7HjAISLZYpcmUoCidVPUiQysp5cDWjzg8dtlE6Zc+hMqOMhSDAMaVFZCrXdnW/BHLtXYdhS8R",
	"LAW/RH/d73ybUCPKm5rEwIHVlDDPClETE0ejelLQuvzevVtTb4un/4vTmEsShI13zJqeh0L9DlM4k+rG",
	"N7PGLLaJra05pcwKHgNX3fqx2Icd9ZmI3D82dan3lVVtZv9PY0N94yCVzfgyDLI5S29hazqf221Z29nj",
	"FxhUjPslKD5BItgbDLr881krfzI/UT7rmsdLVI6cLgB1VQd1p963vaqfXnVbpMbT/fONFZvZcBZRo+60",
	"KgntUgLIGTU7vonoyVeb2Fz0ZWC54ujpC3n9qP+4Kf3RJf5sgqHxlzn9kZGZxcQlfUlxyzUjBjLGDF9f",
	"UPQUFF0ybvqj38vEzgyeb8YwuTuP82LhW/W+1QfO3QbxXdH2XKPm8vuuvmA5b3spIfIM6hvfQJjzjCa2",
	"DC1pR3YYGbwA14+lpyrWsW6h1ZyWOR1LNZNyGaFIS0bX0lb4afIxY9YXNHTkB12E/vtjzzPGwHT+Y8a4",
	"0phkeRHos/Nc61PhEPuIpEDqJ9X5zw7XWpWTmRBbr2TSCdo0ghUKQwjHj300gtaP8r+nxkIKT/KfczCC",
	"5tEyMSzOpTYyqnvxktWKeRaLJymdxdf+mRE3sQOf3yS6YxxCfDYQN5rjh1f6uND+RCgrNnL+x0JZmS2X",
	"wyEtKxcfaH1SM7lYp1utpupUM61YYwUmJw3KBfuP8ejK6x5Y0IAiBih8WMEPzAVfbSlbBeX6Fk9ZzaUQ",
	"K7sOcI+sckRWf30WP3fiYXFhkbEylzMAZ94GZjRMcBb1ghkHx3OJKLGOoi8DKVM71Wc4yTLUkjs/pF6G",
	"V+e6qIdDVkz1qxT4uaUzNb9spOM5aSad4SdSuXhL3xZhJd3s2yK8KZ8rVL8XxPQwQLcYIoUJLez3VNeu",
	"zEfJC+n4thmGtQI8rSOrAq2bLHu/GLu3NKx5NCCh+1jfzGhyeWSRsVu5rJ9vA9z6/TsdVm7RcDsHUKx5",
	"Vv5qADryylneDGFAvVpiJyiytiuBY1hxVQPxxSAtBXuqZKO9MdL1xKaEWLVimQFYH1RZsRUi4SovLLbS",
	"XOT258XsdKreLVFm6kSKFkYrmVvOvat3IM7dE12Mz9YMlOr3LRkGbbLSBYEGiCnCMRaVjqcyaX8v6i9J",
	"q7pThQim3BwYix8ZrMft5SU8nWmq03MlOTmlN92OkddUSWi6S6ODzYuYasZAdDhPzTYrSM6n3UphQ+Pr",
	"+egwTuJaQ8Hr4ibFVc/6tuB8tV0tqbkwbWu1jKnobVaoc4iq8yKf56vsepnShak7V85ICn8cmIRa1vsz",
	"pX0tNFfQKdf0uUO324myS1/gYVVb9JIA0X8RegGgmNT7zHj36ZAXeq6IPB6P/w8AAP//guE3Er+EAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
