// generated with @7nohe/openapi-react-query-codegen@2.0.0-beta.3 

import { type Options } from "@hey-api/client-fetch";
import { UseQueryResult } from "@tanstack/react-query";
import { deleteUserByIdAccountsByAccountId, deleteUserByIdBudgetTransactionsByBudgetTransactionId, deleteUserByIdCategoriesByCategoryId, deleteUserByIdCategoriesByCategoryIdRulesByRuleId, deleteUserByIdCategoryBudgetsByCategoryBudgetId, deleteUserByIdTransactionsByTransactionId, getBanks, getUserById, getUserByIdAccounts, getUserByIdAccountsByAccountId, getUserByIdBudgetTransactions, getUserByIdBudgetTransactionsByBudgetTransactionId, getUserByIdCategories, getUserByIdCategoriesByCategoryId, getUserByIdCategoryBudgets, getUserByIdCategoryBudgetsByCategoryBudgetId, getUserByIdSummaryAccounts, getUserByIdSummaryBalance, getUserByIdSummaryCategories, getUserByIdSummaryTotals, getUserByIdTransactions, getUserByIdTransactionsByTransactionId, patchUserByIdAccountsByAccountId, patchUserByIdBudgetTransactionsByBudgetTransactionId, patchUserByIdCategoriesByCategoryId, patchUserByIdCategoriesByCategoryIdRulesByRuleId, patchUserByIdCategoryBudgetsByCategoryBudgetId, patchUserByIdTransactionsByTransactionId, postLogin, postSignup, postUserByIdAccounts, postUserByIdBudgetTransactions, postUserByIdCategories, postUserByIdCategoriesByCategoryIdRules, postUserByIdCategoryBudgets, postUserByIdTransactions, postUserByIdTransactionsBulk, postUserByIdTransactionsBulkDelete, postUserByIdTransactionsBulkFinalise } from "../requests/services.gen";
export type GetBanksDefaultResponse = Awaited<ReturnType<typeof getBanks>>["data"];
export type GetBanksQueryResult<TData = GetBanksDefaultResponse, TError = unknown> = UseQueryResult<TData, TError>;
export const useGetBanksKey = "GetBanks";
export const UseGetBanksKeyFn = (clientOptions: Options<unknown, true> = {}, queryKey?: Array<unknown>) => [useGetBanksKey, ...(queryKey ?? [clientOptions])];
export type GetUserByIdDefaultResponse = Awaited<ReturnType<typeof getUserById>>["data"];
export type GetUserByIdQueryResult<TData = GetUserByIdDefaultResponse, TError = unknown> = UseQueryResult<TData, TError>;
export const useGetUserByIdKey = "GetUserById";
export const UseGetUserByIdKeyFn = (clientOptions: Options<unknown, true>, queryKey?: Array<unknown>) => [useGetUserByIdKey, ...(queryKey ?? [clientOptions])];
export type GetUserByIdAccountsDefaultResponse = Awaited<ReturnType<typeof getUserByIdAccounts>>["data"];
export type GetUserByIdAccountsQueryResult<TData = GetUserByIdAccountsDefaultResponse, TError = unknown> = UseQueryResult<TData, TError>;
export const useGetUserByIdAccountsKey = "GetUserByIdAccounts";
export const UseGetUserByIdAccountsKeyFn = (clientOptions: Options<unknown, true>, queryKey?: Array<unknown>) => [useGetUserByIdAccountsKey, ...(queryKey ?? [clientOptions])];
export type GetUserByIdAccountsByAccountIdDefaultResponse = Awaited<ReturnType<typeof getUserByIdAccountsByAccountId>>["data"];
export type GetUserByIdAccountsByAccountIdQueryResult<TData = GetUserByIdAccountsByAccountIdDefaultResponse, TError = unknown> = UseQueryResult<TData, TError>;
export const useGetUserByIdAccountsByAccountIdKey = "GetUserByIdAccountsByAccountId";
export const UseGetUserByIdAccountsByAccountIdKeyFn = (clientOptions: Options<unknown, true>, queryKey?: Array<unknown>) => [useGetUserByIdAccountsByAccountIdKey, ...(queryKey ?? [clientOptions])];
export type GetUserByIdTransactionsDefaultResponse = Awaited<ReturnType<typeof getUserByIdTransactions>>["data"];
export type GetUserByIdTransactionsQueryResult<TData = GetUserByIdTransactionsDefaultResponse, TError = unknown> = UseQueryResult<TData, TError>;
export const useGetUserByIdTransactionsKey = "GetUserByIdTransactions";
export const UseGetUserByIdTransactionsKeyFn = (clientOptions: Options<unknown, true>, queryKey?: Array<unknown>) => [useGetUserByIdTransactionsKey, ...(queryKey ?? [clientOptions])];
export type GetUserByIdTransactionsByTransactionIdDefaultResponse = Awaited<ReturnType<typeof getUserByIdTransactionsByTransactionId>>["data"];
export type GetUserByIdTransactionsByTransactionIdQueryResult<TData = GetUserByIdTransactionsByTransactionIdDefaultResponse, TError = unknown> = UseQueryResult<TData, TError>;
export const useGetUserByIdTransactionsByTransactionIdKey = "GetUserByIdTransactionsByTransactionId";
export const UseGetUserByIdTransactionsByTransactionIdKeyFn = (clientOptions: Options<unknown, true>, queryKey?: Array<unknown>) => [useGetUserByIdTransactionsByTransactionIdKey, ...(queryKey ?? [clientOptions])];
export type GetUserByIdCategoriesDefaultResponse = Awaited<ReturnType<typeof getUserByIdCategories>>["data"];
export type GetUserByIdCategoriesQueryResult<TData = GetUserByIdCategoriesDefaultResponse, TError = unknown> = UseQueryResult<TData, TError>;
export const useGetUserByIdCategoriesKey = "GetUserByIdCategories";
export const UseGetUserByIdCategoriesKeyFn = (clientOptions: Options<unknown, true>, queryKey?: Array<unknown>) => [useGetUserByIdCategoriesKey, ...(queryKey ?? [clientOptions])];
export type GetUserByIdCategoriesByCategoryIdDefaultResponse = Awaited<ReturnType<typeof getUserByIdCategoriesByCategoryId>>["data"];
export type GetUserByIdCategoriesByCategoryIdQueryResult<TData = GetUserByIdCategoriesByCategoryIdDefaultResponse, TError = unknown> = UseQueryResult<TData, TError>;
export const useGetUserByIdCategoriesByCategoryIdKey = "GetUserByIdCategoriesByCategoryId";
export const UseGetUserByIdCategoriesByCategoryIdKeyFn = (clientOptions: Options<unknown, true>, queryKey?: Array<unknown>) => [useGetUserByIdCategoriesByCategoryIdKey, ...(queryKey ?? [clientOptions])];
export type GetUserByIdSummaryAccountsDefaultResponse = Awaited<ReturnType<typeof getUserByIdSummaryAccounts>>["data"];
export type GetUserByIdSummaryAccountsQueryResult<TData = GetUserByIdSummaryAccountsDefaultResponse, TError = unknown> = UseQueryResult<TData, TError>;
export const useGetUserByIdSummaryAccountsKey = "GetUserByIdSummaryAccounts";
export const UseGetUserByIdSummaryAccountsKeyFn = (clientOptions: Options<unknown, true>, queryKey?: Array<unknown>) => [useGetUserByIdSummaryAccountsKey, ...(queryKey ?? [clientOptions])];
export type GetUserByIdSummaryCategoriesDefaultResponse = Awaited<ReturnType<typeof getUserByIdSummaryCategories>>["data"];
export type GetUserByIdSummaryCategoriesQueryResult<TData = GetUserByIdSummaryCategoriesDefaultResponse, TError = unknown> = UseQueryResult<TData, TError>;
export const useGetUserByIdSummaryCategoriesKey = "GetUserByIdSummaryCategories";
export const UseGetUserByIdSummaryCategoriesKeyFn = (clientOptions: Options<unknown, true>, queryKey?: Array<unknown>) => [useGetUserByIdSummaryCategoriesKey, ...(queryKey ?? [clientOptions])];
export type GetUserByIdSummaryBalanceDefaultResponse = Awaited<ReturnType<typeof getUserByIdSummaryBalance>>["data"];
export type GetUserByIdSummaryBalanceQueryResult<TData = GetUserByIdSummaryBalanceDefaultResponse, TError = unknown> = UseQueryResult<TData, TError>;
export const useGetUserByIdSummaryBalanceKey = "GetUserByIdSummaryBalance";
export const UseGetUserByIdSummaryBalanceKeyFn = (clientOptions: Options<unknown, true>, queryKey?: Array<unknown>) => [useGetUserByIdSummaryBalanceKey, ...(queryKey ?? [clientOptions])];
export type GetUserByIdSummaryTotalsDefaultResponse = Awaited<ReturnType<typeof getUserByIdSummaryTotals>>["data"];
export type GetUserByIdSummaryTotalsQueryResult<TData = GetUserByIdSummaryTotalsDefaultResponse, TError = unknown> = UseQueryResult<TData, TError>;
export const useGetUserByIdSummaryTotalsKey = "GetUserByIdSummaryTotals";
export const UseGetUserByIdSummaryTotalsKeyFn = (clientOptions: Options<unknown, true>, queryKey?: Array<unknown>) => [useGetUserByIdSummaryTotalsKey, ...(queryKey ?? [clientOptions])];
export type GetUserByIdBudgetTransactionsDefaultResponse = Awaited<ReturnType<typeof getUserByIdBudgetTransactions>>["data"];
export type GetUserByIdBudgetTransactionsQueryResult<TData = GetUserByIdBudgetTransactionsDefaultResponse, TError = unknown> = UseQueryResult<TData, TError>;
export const useGetUserByIdBudgetTransactionsKey = "GetUserByIdBudgetTransactions";
export const UseGetUserByIdBudgetTransactionsKeyFn = (clientOptions: Options<unknown, true>, queryKey?: Array<unknown>) => [useGetUserByIdBudgetTransactionsKey, ...(queryKey ?? [clientOptions])];
export type GetUserByIdBudgetTransactionsByBudgetTransactionIdDefaultResponse = Awaited<ReturnType<typeof getUserByIdBudgetTransactionsByBudgetTransactionId>>["data"];
export type GetUserByIdBudgetTransactionsByBudgetTransactionIdQueryResult<TData = GetUserByIdBudgetTransactionsByBudgetTransactionIdDefaultResponse, TError = unknown> = UseQueryResult<TData, TError>;
export const useGetUserByIdBudgetTransactionsByBudgetTransactionIdKey = "GetUserByIdBudgetTransactionsByBudgetTransactionId";
export const UseGetUserByIdBudgetTransactionsByBudgetTransactionIdKeyFn = (clientOptions: Options<unknown, true>, queryKey?: Array<unknown>) => [useGetUserByIdBudgetTransactionsByBudgetTransactionIdKey, ...(queryKey ?? [clientOptions])];
export type GetUserByIdCategoryBudgetsDefaultResponse = Awaited<ReturnType<typeof getUserByIdCategoryBudgets>>["data"];
export type GetUserByIdCategoryBudgetsQueryResult<TData = GetUserByIdCategoryBudgetsDefaultResponse, TError = unknown> = UseQueryResult<TData, TError>;
export const useGetUserByIdCategoryBudgetsKey = "GetUserByIdCategoryBudgets";
export const UseGetUserByIdCategoryBudgetsKeyFn = (clientOptions: Options<unknown, true>, queryKey?: Array<unknown>) => [useGetUserByIdCategoryBudgetsKey, ...(queryKey ?? [clientOptions])];
export type GetUserByIdCategoryBudgetsByCategoryBudgetIdDefaultResponse = Awaited<ReturnType<typeof getUserByIdCategoryBudgetsByCategoryBudgetId>>["data"];
export type GetUserByIdCategoryBudgetsByCategoryBudgetIdQueryResult<TData = GetUserByIdCategoryBudgetsByCategoryBudgetIdDefaultResponse, TError = unknown> = UseQueryResult<TData, TError>;
export const useGetUserByIdCategoryBudgetsByCategoryBudgetIdKey = "GetUserByIdCategoryBudgetsByCategoryBudgetId";
export const UseGetUserByIdCategoryBudgetsByCategoryBudgetIdKeyFn = (clientOptions: Options<unknown, true>, queryKey?: Array<unknown>) => [useGetUserByIdCategoryBudgetsByCategoryBudgetIdKey, ...(queryKey ?? [clientOptions])];
export type PostLoginMutationResult = Awaited<ReturnType<typeof postLogin>>;
export const usePostLoginKey = "PostLogin";
export const UsePostLoginKeyFn = (mutationKey?: Array<unknown>) => [usePostLoginKey, ...(mutationKey ?? [])];
export type PostSignupMutationResult = Awaited<ReturnType<typeof postSignup>>;
export const usePostSignupKey = "PostSignup";
export const UsePostSignupKeyFn = (mutationKey?: Array<unknown>) => [usePostSignupKey, ...(mutationKey ?? [])];
export type PostUserByIdAccountsMutationResult = Awaited<ReturnType<typeof postUserByIdAccounts>>;
export const usePostUserByIdAccountsKey = "PostUserByIdAccounts";
export const UsePostUserByIdAccountsKeyFn = (mutationKey?: Array<unknown>) => [usePostUserByIdAccountsKey, ...(mutationKey ?? [])];
export type PostUserByIdTransactionsMutationResult = Awaited<ReturnType<typeof postUserByIdTransactions>>;
export const usePostUserByIdTransactionsKey = "PostUserByIdTransactions";
export const UsePostUserByIdTransactionsKeyFn = (mutationKey?: Array<unknown>) => [usePostUserByIdTransactionsKey, ...(mutationKey ?? [])];
export type PostUserByIdTransactionsBulkMutationResult = Awaited<ReturnType<typeof postUserByIdTransactionsBulk>>;
export const usePostUserByIdTransactionsBulkKey = "PostUserByIdTransactionsBulk";
export const UsePostUserByIdTransactionsBulkKeyFn = (mutationKey?: Array<unknown>) => [usePostUserByIdTransactionsBulkKey, ...(mutationKey ?? [])];
export type PostUserByIdTransactionsBulkFinaliseMutationResult = Awaited<ReturnType<typeof postUserByIdTransactionsBulkFinalise>>;
export const usePostUserByIdTransactionsBulkFinaliseKey = "PostUserByIdTransactionsBulkFinalise";
export const UsePostUserByIdTransactionsBulkFinaliseKeyFn = (mutationKey?: Array<unknown>) => [usePostUserByIdTransactionsBulkFinaliseKey, ...(mutationKey ?? [])];
export type PostUserByIdTransactionsBulkDeleteMutationResult = Awaited<ReturnType<typeof postUserByIdTransactionsBulkDelete>>;
export const usePostUserByIdTransactionsBulkDeleteKey = "PostUserByIdTransactionsBulkDelete";
export const UsePostUserByIdTransactionsBulkDeleteKeyFn = (mutationKey?: Array<unknown>) => [usePostUserByIdTransactionsBulkDeleteKey, ...(mutationKey ?? [])];
export type PostUserByIdCategoriesMutationResult = Awaited<ReturnType<typeof postUserByIdCategories>>;
export const usePostUserByIdCategoriesKey = "PostUserByIdCategories";
export const UsePostUserByIdCategoriesKeyFn = (mutationKey?: Array<unknown>) => [usePostUserByIdCategoriesKey, ...(mutationKey ?? [])];
export type PostUserByIdCategoriesByCategoryIdRulesMutationResult = Awaited<ReturnType<typeof postUserByIdCategoriesByCategoryIdRules>>;
export const usePostUserByIdCategoriesByCategoryIdRulesKey = "PostUserByIdCategoriesByCategoryIdRules";
export const UsePostUserByIdCategoriesByCategoryIdRulesKeyFn = (mutationKey?: Array<unknown>) => [usePostUserByIdCategoriesByCategoryIdRulesKey, ...(mutationKey ?? [])];
export type PostUserByIdBudgetTransactionsMutationResult = Awaited<ReturnType<typeof postUserByIdBudgetTransactions>>;
export const usePostUserByIdBudgetTransactionsKey = "PostUserByIdBudgetTransactions";
export const UsePostUserByIdBudgetTransactionsKeyFn = (mutationKey?: Array<unknown>) => [usePostUserByIdBudgetTransactionsKey, ...(mutationKey ?? [])];
export type PostUserByIdCategoryBudgetsMutationResult = Awaited<ReturnType<typeof postUserByIdCategoryBudgets>>;
export const usePostUserByIdCategoryBudgetsKey = "PostUserByIdCategoryBudgets";
export const UsePostUserByIdCategoryBudgetsKeyFn = (mutationKey?: Array<unknown>) => [usePostUserByIdCategoryBudgetsKey, ...(mutationKey ?? [])];
export type PatchUserByIdAccountsByAccountIdMutationResult = Awaited<ReturnType<typeof patchUserByIdAccountsByAccountId>>;
export const usePatchUserByIdAccountsByAccountIdKey = "PatchUserByIdAccountsByAccountId";
export const UsePatchUserByIdAccountsByAccountIdKeyFn = (mutationKey?: Array<unknown>) => [usePatchUserByIdAccountsByAccountIdKey, ...(mutationKey ?? [])];
export type PatchUserByIdTransactionsByTransactionIdMutationResult = Awaited<ReturnType<typeof patchUserByIdTransactionsByTransactionId>>;
export const usePatchUserByIdTransactionsByTransactionIdKey = "PatchUserByIdTransactionsByTransactionId";
export const UsePatchUserByIdTransactionsByTransactionIdKeyFn = (mutationKey?: Array<unknown>) => [usePatchUserByIdTransactionsByTransactionIdKey, ...(mutationKey ?? [])];
export type PatchUserByIdCategoriesByCategoryIdMutationResult = Awaited<ReturnType<typeof patchUserByIdCategoriesByCategoryId>>;
export const usePatchUserByIdCategoriesByCategoryIdKey = "PatchUserByIdCategoriesByCategoryId";
export const UsePatchUserByIdCategoriesByCategoryIdKeyFn = (mutationKey?: Array<unknown>) => [usePatchUserByIdCategoriesByCategoryIdKey, ...(mutationKey ?? [])];
export type PatchUserByIdCategoriesByCategoryIdRulesByRuleIdMutationResult = Awaited<ReturnType<typeof patchUserByIdCategoriesByCategoryIdRulesByRuleId>>;
export const usePatchUserByIdCategoriesByCategoryIdRulesByRuleIdKey = "PatchUserByIdCategoriesByCategoryIdRulesByRuleId";
export const UsePatchUserByIdCategoriesByCategoryIdRulesByRuleIdKeyFn = (mutationKey?: Array<unknown>) => [usePatchUserByIdCategoriesByCategoryIdRulesByRuleIdKey, ...(mutationKey ?? [])];
export type PatchUserByIdBudgetTransactionsByBudgetTransactionIdMutationResult = Awaited<ReturnType<typeof patchUserByIdBudgetTransactionsByBudgetTransactionId>>;
export const usePatchUserByIdBudgetTransactionsByBudgetTransactionIdKey = "PatchUserByIdBudgetTransactionsByBudgetTransactionId";
export const UsePatchUserByIdBudgetTransactionsByBudgetTransactionIdKeyFn = (mutationKey?: Array<unknown>) => [usePatchUserByIdBudgetTransactionsByBudgetTransactionIdKey, ...(mutationKey ?? [])];
export type PatchUserByIdCategoryBudgetsByCategoryBudgetIdMutationResult = Awaited<ReturnType<typeof patchUserByIdCategoryBudgetsByCategoryBudgetId>>;
export const usePatchUserByIdCategoryBudgetsByCategoryBudgetIdKey = "PatchUserByIdCategoryBudgetsByCategoryBudgetId";
export const UsePatchUserByIdCategoryBudgetsByCategoryBudgetIdKeyFn = (mutationKey?: Array<unknown>) => [usePatchUserByIdCategoryBudgetsByCategoryBudgetIdKey, ...(mutationKey ?? [])];
export type DeleteUserByIdAccountsByAccountIdMutationResult = Awaited<ReturnType<typeof deleteUserByIdAccountsByAccountId>>;
export const useDeleteUserByIdAccountsByAccountIdKey = "DeleteUserByIdAccountsByAccountId";
export const UseDeleteUserByIdAccountsByAccountIdKeyFn = (mutationKey?: Array<unknown>) => [useDeleteUserByIdAccountsByAccountIdKey, ...(mutationKey ?? [])];
export type DeleteUserByIdTransactionsByTransactionIdMutationResult = Awaited<ReturnType<typeof deleteUserByIdTransactionsByTransactionId>>;
export const useDeleteUserByIdTransactionsByTransactionIdKey = "DeleteUserByIdTransactionsByTransactionId";
export const UseDeleteUserByIdTransactionsByTransactionIdKeyFn = (mutationKey?: Array<unknown>) => [useDeleteUserByIdTransactionsByTransactionIdKey, ...(mutationKey ?? [])];
export type DeleteUserByIdCategoriesByCategoryIdMutationResult = Awaited<ReturnType<typeof deleteUserByIdCategoriesByCategoryId>>;
export const useDeleteUserByIdCategoriesByCategoryIdKey = "DeleteUserByIdCategoriesByCategoryId";
export const UseDeleteUserByIdCategoriesByCategoryIdKeyFn = (mutationKey?: Array<unknown>) => [useDeleteUserByIdCategoriesByCategoryIdKey, ...(mutationKey ?? [])];
export type DeleteUserByIdCategoriesByCategoryIdRulesByRuleIdMutationResult = Awaited<ReturnType<typeof deleteUserByIdCategoriesByCategoryIdRulesByRuleId>>;
export const useDeleteUserByIdCategoriesByCategoryIdRulesByRuleIdKey = "DeleteUserByIdCategoriesByCategoryIdRulesByRuleId";
export const UseDeleteUserByIdCategoriesByCategoryIdRulesByRuleIdKeyFn = (mutationKey?: Array<unknown>) => [useDeleteUserByIdCategoriesByCategoryIdRulesByRuleIdKey, ...(mutationKey ?? [])];
export type DeleteUserByIdBudgetTransactionsByBudgetTransactionIdMutationResult = Awaited<ReturnType<typeof deleteUserByIdBudgetTransactionsByBudgetTransactionId>>;
export const useDeleteUserByIdBudgetTransactionsByBudgetTransactionIdKey = "DeleteUserByIdBudgetTransactionsByBudgetTransactionId";
export const UseDeleteUserByIdBudgetTransactionsByBudgetTransactionIdKeyFn = (mutationKey?: Array<unknown>) => [useDeleteUserByIdBudgetTransactionsByBudgetTransactionIdKey, ...(mutationKey ?? [])];
export type DeleteUserByIdCategoryBudgetsByCategoryBudgetIdMutationResult = Awaited<ReturnType<typeof deleteUserByIdCategoryBudgetsByCategoryBudgetId>>;
export const useDeleteUserByIdCategoryBudgetsByCategoryBudgetIdKey = "DeleteUserByIdCategoryBudgetsByCategoryBudgetId";
export const UseDeleteUserByIdCategoryBudgetsByCategoryBudgetIdKeyFn = (mutationKey?: Array<unknown>) => [useDeleteUserByIdCategoryBudgetsByCategoryBudgetIdKey, ...(mutationKey ?? [])];
