// generated with @7nohe/openapi-react-query-codegen@2.0.0-beta.3 

import { type Options } from "@hey-api/client-fetch";
import { UseQueryResult } from "@tanstack/react-query";
import { deleteUserByIdAccountsByAccountId, deleteUserByIdAccountsByAccountIdTransactionsByTransactionId, deleteUserByIdCategoriesByCategoryId, getUserById, getUserByIdAccounts, getUserByIdAccountsByAccountId, getUserByIdAccountsByAccountIdTransactions, getUserByIdCategories, getUserByIdCategoriesByCategoryId, postLogin, postSignup, postUserByIdAccounts, postUserByIdAccountsByAccountIdTransactions, postUserByIdCategories } from "../requests/services.gen";
export type GetUserByIdDefaultResponse = Awaited<ReturnType<typeof getUserById>>["data"];
export type GetUserByIdQueryResult<TData = GetUserByIdDefaultResponse, TError = unknown> = UseQueryResult<TData, TError>;
export const useGetUserByIdKey = "GetUserById";
export const UseGetUserByIdKeyFn = (clientOptions: Options<unknown, true>, queryKey?: Array<unknown>) => [useGetUserByIdKey, ...(queryKey ?? [clientOptions])];
export type GetUserByIdAccountsDefaultResponse = Awaited<ReturnType<typeof getUserByIdAccounts>>["data"];
export type GetUserByIdAccountsQueryResult<TData = GetUserByIdAccountsDefaultResponse, TError = unknown> = UseQueryResult<TData, TError>;
export const useGetUserByIdAccountsKey = "GetUserByIdAccounts";
export const UseGetUserByIdAccountsKeyFn = (clientOptions: Options<unknown, true>, queryKey?: Array<unknown>) => [useGetUserByIdAccountsKey, ...(queryKey ?? [clientOptions])];
export type GetUserByIdAccountsByAccountIdDefaultResponse = Awaited<ReturnType<typeof getUserByIdAccountsByAccountId>>["data"];
export type GetUserByIdAccountsByAccountIdQueryResult<TData = GetUserByIdAccountsByAccountIdDefaultResponse, TError = unknown> = UseQueryResult<TData, TError>;
export const useGetUserByIdAccountsByAccountIdKey = "GetUserByIdAccountsByAccountId";
export const UseGetUserByIdAccountsByAccountIdKeyFn = (clientOptions: Options<unknown, true>, queryKey?: Array<unknown>) => [useGetUserByIdAccountsByAccountIdKey, ...(queryKey ?? [clientOptions])];
export type GetUserByIdAccountsByAccountIdTransactionsDefaultResponse = Awaited<ReturnType<typeof getUserByIdAccountsByAccountIdTransactions>>["data"];
export type GetUserByIdAccountsByAccountIdTransactionsQueryResult<TData = GetUserByIdAccountsByAccountIdTransactionsDefaultResponse, TError = unknown> = UseQueryResult<TData, TError>;
export const useGetUserByIdAccountsByAccountIdTransactionsKey = "GetUserByIdAccountsByAccountIdTransactions";
export const UseGetUserByIdAccountsByAccountIdTransactionsKeyFn = (clientOptions: Options<unknown, true>, queryKey?: Array<unknown>) => [useGetUserByIdAccountsByAccountIdTransactionsKey, ...(queryKey ?? [clientOptions])];
export type GetUserByIdCategoriesDefaultResponse = Awaited<ReturnType<typeof getUserByIdCategories>>["data"];
export type GetUserByIdCategoriesQueryResult<TData = GetUserByIdCategoriesDefaultResponse, TError = unknown> = UseQueryResult<TData, TError>;
export const useGetUserByIdCategoriesKey = "GetUserByIdCategories";
export const UseGetUserByIdCategoriesKeyFn = (clientOptions: Options<unknown, true>, queryKey?: Array<unknown>) => [useGetUserByIdCategoriesKey, ...(queryKey ?? [clientOptions])];
export type GetUserByIdCategoriesByCategoryIdDefaultResponse = Awaited<ReturnType<typeof getUserByIdCategoriesByCategoryId>>["data"];
export type GetUserByIdCategoriesByCategoryIdQueryResult<TData = GetUserByIdCategoriesByCategoryIdDefaultResponse, TError = unknown> = UseQueryResult<TData, TError>;
export const useGetUserByIdCategoriesByCategoryIdKey = "GetUserByIdCategoriesByCategoryId";
export const UseGetUserByIdCategoriesByCategoryIdKeyFn = (clientOptions: Options<unknown, true>, queryKey?: Array<unknown>) => [useGetUserByIdCategoriesByCategoryIdKey, ...(queryKey ?? [clientOptions])];
export type PostLoginMutationResult = Awaited<ReturnType<typeof postLogin>>;
export const usePostLoginKey = "PostLogin";
export const UsePostLoginKeyFn = (mutationKey?: Array<unknown>) => [usePostLoginKey, ...(mutationKey ?? [])];
export type PostSignupMutationResult = Awaited<ReturnType<typeof postSignup>>;
export const usePostSignupKey = "PostSignup";
export const UsePostSignupKeyFn = (mutationKey?: Array<unknown>) => [usePostSignupKey, ...(mutationKey ?? [])];
export type PostUserByIdAccountsMutationResult = Awaited<ReturnType<typeof postUserByIdAccounts>>;
export const usePostUserByIdAccountsKey = "PostUserByIdAccounts";
export const UsePostUserByIdAccountsKeyFn = (mutationKey?: Array<unknown>) => [usePostUserByIdAccountsKey, ...(mutationKey ?? [])];
export type PostUserByIdAccountsByAccountIdTransactionsMutationResult = Awaited<ReturnType<typeof postUserByIdAccountsByAccountIdTransactions>>;
export const usePostUserByIdAccountsByAccountIdTransactionsKey = "PostUserByIdAccountsByAccountIdTransactions";
export const UsePostUserByIdAccountsByAccountIdTransactionsKeyFn = (mutationKey?: Array<unknown>) => [usePostUserByIdAccountsByAccountIdTransactionsKey, ...(mutationKey ?? [])];
export type PostUserByIdCategoriesMutationResult = Awaited<ReturnType<typeof postUserByIdCategories>>;
export const usePostUserByIdCategoriesKey = "PostUserByIdCategories";
export const UsePostUserByIdCategoriesKeyFn = (mutationKey?: Array<unknown>) => [usePostUserByIdCategoriesKey, ...(mutationKey ?? [])];
export type DeleteUserByIdAccountsByAccountIdMutationResult = Awaited<ReturnType<typeof deleteUserByIdAccountsByAccountId>>;
export const useDeleteUserByIdAccountsByAccountIdKey = "DeleteUserByIdAccountsByAccountId";
export const UseDeleteUserByIdAccountsByAccountIdKeyFn = (mutationKey?: Array<unknown>) => [useDeleteUserByIdAccountsByAccountIdKey, ...(mutationKey ?? [])];
export type DeleteUserByIdAccountsByAccountIdTransactionsByTransactionIdMutationResult = Awaited<ReturnType<typeof deleteUserByIdAccountsByAccountIdTransactionsByTransactionId>>;
export const useDeleteUserByIdAccountsByAccountIdTransactionsByTransactionIdKey = "DeleteUserByIdAccountsByAccountIdTransactionsByTransactionId";
export const UseDeleteUserByIdAccountsByAccountIdTransactionsByTransactionIdKeyFn = (mutationKey?: Array<unknown>) => [useDeleteUserByIdAccountsByAccountIdTransactionsByTransactionIdKey, ...(mutationKey ?? [])];
export type DeleteUserByIdCategoriesByCategoryIdMutationResult = Awaited<ReturnType<typeof deleteUserByIdCategoriesByCategoryId>>;
export const useDeleteUserByIdCategoriesByCategoryIdKey = "DeleteUserByIdCategoriesByCategoryId";
export const UseDeleteUserByIdCategoriesByCategoryIdKeyFn = (mutationKey?: Array<unknown>) => [useDeleteUserByIdCategoriesByCategoryIdKey, ...(mutationKey ?? [])];
