// generated with @7nohe/openapi-react-query-codegen@2.0.0-beta.3 

import { type Options } from "@hey-api/client-fetch";
import { type QueryClient } from "@tanstack/react-query";
import { getBanks, getUserById, getUserByIdAccounts, getUserByIdAccountsByAccountId, getUserByIdBudgetTransactions, getUserByIdBudgetTransactionsByBudgetTransactionId, getUserByIdCategories, getUserByIdCategoriesByCategoryId, getUserByIdSummaryAccounts, getUserByIdSummaryBalance, getUserByIdSummaryCategories, getUserByIdSummaryTotals, getUserByIdTransactions, getUserByIdTransactionsByTransactionId } from "../requests/services.gen";
import { GetUserByIdAccountsByAccountIdData, GetUserByIdAccountsData, GetUserByIdBudgetTransactionsByBudgetTransactionIdData, GetUserByIdBudgetTransactionsData, GetUserByIdCategoriesByCategoryIdData, GetUserByIdCategoriesData, GetUserByIdData, GetUserByIdSummaryAccountsData, GetUserByIdSummaryBalanceData, GetUserByIdSummaryCategoriesData, GetUserByIdSummaryTotalsData, GetUserByIdTransactionsByTransactionIdData, GetUserByIdTransactionsData } from "../requests/types.gen";
import * as Common from "./common";
export const ensureUseGetBanksData = (queryClient: QueryClient, clientOptions: Options<unknown, true> = {}) => queryClient.ensureQueryData({ queryKey: Common.UseGetBanksKeyFn(clientOptions), queryFn: () => getBanks({ ...clientOptions }).then(response => response.data) });
export const ensureUseGetUserByIdData = (queryClient: QueryClient, clientOptions: Options<GetUserByIdData, true>) => queryClient.ensureQueryData({ queryKey: Common.UseGetUserByIdKeyFn(clientOptions), queryFn: () => getUserById({ ...clientOptions }).then(response => response.data) });
export const ensureUseGetUserByIdAccountsData = (queryClient: QueryClient, clientOptions: Options<GetUserByIdAccountsData, true>) => queryClient.ensureQueryData({ queryKey: Common.UseGetUserByIdAccountsKeyFn(clientOptions), queryFn: () => getUserByIdAccounts({ ...clientOptions }).then(response => response.data) });
export const ensureUseGetUserByIdAccountsByAccountIdData = (queryClient: QueryClient, clientOptions: Options<GetUserByIdAccountsByAccountIdData, true>) => queryClient.ensureQueryData({ queryKey: Common.UseGetUserByIdAccountsByAccountIdKeyFn(clientOptions), queryFn: () => getUserByIdAccountsByAccountId({ ...clientOptions }).then(response => response.data) });
export const ensureUseGetUserByIdTransactionsData = (queryClient: QueryClient, clientOptions: Options<GetUserByIdTransactionsData, true>) => queryClient.ensureQueryData({ queryKey: Common.UseGetUserByIdTransactionsKeyFn(clientOptions), queryFn: () => getUserByIdTransactions({ ...clientOptions }).then(response => response.data) });
export const ensureUseGetUserByIdTransactionsByTransactionIdData = (queryClient: QueryClient, clientOptions: Options<GetUserByIdTransactionsByTransactionIdData, true>) => queryClient.ensureQueryData({ queryKey: Common.UseGetUserByIdTransactionsByTransactionIdKeyFn(clientOptions), queryFn: () => getUserByIdTransactionsByTransactionId({ ...clientOptions }).then(response => response.data) });
export const ensureUseGetUserByIdCategoriesData = (queryClient: QueryClient, clientOptions: Options<GetUserByIdCategoriesData, true>) => queryClient.ensureQueryData({ queryKey: Common.UseGetUserByIdCategoriesKeyFn(clientOptions), queryFn: () => getUserByIdCategories({ ...clientOptions }).then(response => response.data) });
export const ensureUseGetUserByIdCategoriesByCategoryIdData = (queryClient: QueryClient, clientOptions: Options<GetUserByIdCategoriesByCategoryIdData, true>) => queryClient.ensureQueryData({ queryKey: Common.UseGetUserByIdCategoriesByCategoryIdKeyFn(clientOptions), queryFn: () => getUserByIdCategoriesByCategoryId({ ...clientOptions }).then(response => response.data) });
export const ensureUseGetUserByIdSummaryAccountsData = (queryClient: QueryClient, clientOptions: Options<GetUserByIdSummaryAccountsData, true>) => queryClient.ensureQueryData({ queryKey: Common.UseGetUserByIdSummaryAccountsKeyFn(clientOptions), queryFn: () => getUserByIdSummaryAccounts({ ...clientOptions }).then(response => response.data) });
export const ensureUseGetUserByIdSummaryCategoriesData = (queryClient: QueryClient, clientOptions: Options<GetUserByIdSummaryCategoriesData, true>) => queryClient.ensureQueryData({ queryKey: Common.UseGetUserByIdSummaryCategoriesKeyFn(clientOptions), queryFn: () => getUserByIdSummaryCategories({ ...clientOptions }).then(response => response.data) });
export const ensureUseGetUserByIdSummaryBalanceData = (queryClient: QueryClient, clientOptions: Options<GetUserByIdSummaryBalanceData, true>) => queryClient.ensureQueryData({ queryKey: Common.UseGetUserByIdSummaryBalanceKeyFn(clientOptions), queryFn: () => getUserByIdSummaryBalance({ ...clientOptions }).then(response => response.data) });
export const ensureUseGetUserByIdSummaryTotalsData = (queryClient: QueryClient, clientOptions: Options<GetUserByIdSummaryTotalsData, true>) => queryClient.ensureQueryData({ queryKey: Common.UseGetUserByIdSummaryTotalsKeyFn(clientOptions), queryFn: () => getUserByIdSummaryTotals({ ...clientOptions }).then(response => response.data) });
export const ensureUseGetUserByIdBudgetTransactionsData = (queryClient: QueryClient, clientOptions: Options<GetUserByIdBudgetTransactionsData, true>) => queryClient.ensureQueryData({ queryKey: Common.UseGetUserByIdBudgetTransactionsKeyFn(clientOptions), queryFn: () => getUserByIdBudgetTransactions({ ...clientOptions }).then(response => response.data) });
export const ensureUseGetUserByIdBudgetTransactionsByBudgetTransactionIdData = (queryClient: QueryClient, clientOptions: Options<GetUserByIdBudgetTransactionsByBudgetTransactionIdData, true>) => queryClient.ensureQueryData({ queryKey: Common.UseGetUserByIdBudgetTransactionsByBudgetTransactionIdKeyFn(clientOptions), queryFn: () => getUserByIdBudgetTransactionsByBudgetTransactionId({ ...clientOptions }).then(response => response.data) });
