// generated with @7nohe/openapi-react-query-codegen@2.0.0-beta.3 

import { type Options } from "@hey-api/client-fetch";
import { type QueryClient } from "@tanstack/react-query";
import { getBanks, getUserById, getUserByIdAccounts, getUserByIdAccountsByAccountId, getUserByIdCategories, getUserByIdCategoriesByCategoryId, getUserByIdTransactions } from "../requests/services.gen";
import { GetUserByIdAccountsByAccountIdData, GetUserByIdAccountsData, GetUserByIdCategoriesByCategoryIdData, GetUserByIdCategoriesData, GetUserByIdData, GetUserByIdTransactionsData } from "../requests/types.gen";
import * as Common from "./common";
export const prefetchUseGetBanks = (queryClient: QueryClient, clientOptions: Options<unknown, true> = {}) => queryClient.prefetchQuery({ queryKey: Common.UseGetBanksKeyFn(clientOptions), queryFn: () => getBanks({ ...clientOptions }).then(response => response.data) });
export const prefetchUseGetUserById = (queryClient: QueryClient, clientOptions: Options<GetUserByIdData, true>) => queryClient.prefetchQuery({ queryKey: Common.UseGetUserByIdKeyFn(clientOptions), queryFn: () => getUserById({ ...clientOptions }).then(response => response.data) });
export const prefetchUseGetUserByIdAccounts = (queryClient: QueryClient, clientOptions: Options<GetUserByIdAccountsData, true>) => queryClient.prefetchQuery({ queryKey: Common.UseGetUserByIdAccountsKeyFn(clientOptions), queryFn: () => getUserByIdAccounts({ ...clientOptions }).then(response => response.data) });
export const prefetchUseGetUserByIdAccountsByAccountId = (queryClient: QueryClient, clientOptions: Options<GetUserByIdAccountsByAccountIdData, true>) => queryClient.prefetchQuery({ queryKey: Common.UseGetUserByIdAccountsByAccountIdKeyFn(clientOptions), queryFn: () => getUserByIdAccountsByAccountId({ ...clientOptions }).then(response => response.data) });
export const prefetchUseGetUserByIdTransactions = (queryClient: QueryClient, clientOptions: Options<GetUserByIdTransactionsData, true>) => queryClient.prefetchQuery({ queryKey: Common.UseGetUserByIdTransactionsKeyFn(clientOptions), queryFn: () => getUserByIdTransactions({ ...clientOptions }).then(response => response.data) });
export const prefetchUseGetUserByIdCategories = (queryClient: QueryClient, clientOptions: Options<GetUserByIdCategoriesData, true>) => queryClient.prefetchQuery({ queryKey: Common.UseGetUserByIdCategoriesKeyFn(clientOptions), queryFn: () => getUserByIdCategories({ ...clientOptions }).then(response => response.data) });
export const prefetchUseGetUserByIdCategoriesByCategoryId = (queryClient: QueryClient, clientOptions: Options<GetUserByIdCategoriesByCategoryIdData, true>) => queryClient.prefetchQuery({ queryKey: Common.UseGetUserByIdCategoriesByCategoryIdKeyFn(clientOptions), queryFn: () => getUserByIdCategoriesByCategoryId({ ...clientOptions }).then(response => response.data) });
