// generated with @7nohe/openapi-react-query-codegen@2.0.0-beta.3 

import { type Options } from "@hey-api/client-fetch";
import { type QueryClient } from "@tanstack/react-query";
import { getBanks, getUserById, getUserByIdAccounts, getUserByIdAccountsByAccountId, getUserByIdBudgetTransactions, getUserByIdBudgetTransactionsByBudgetTransactionId, getUserByIdCategories, getUserByIdCategoriesByCategoryId, getUserByIdCategoryBudgets, getUserByIdCategoryBudgetsByCategoryBudgetId, getUserByIdSummaryAccounts, getUserByIdSummaryBalance, getUserByIdSummaryCategories, getUserByIdSummaryCategoriesSpending, getUserByIdSummaryTotals, getUserByIdTransactions, getUserByIdTransactionsByTransactionId } from "../requests/services.gen";
import { GetUserByIdAccountsByAccountIdData, GetUserByIdAccountsData, GetUserByIdBudgetTransactionsByBudgetTransactionIdData, GetUserByIdBudgetTransactionsData, GetUserByIdCategoriesByCategoryIdData, GetUserByIdCategoriesData, GetUserByIdCategoryBudgetsByCategoryBudgetIdData, GetUserByIdCategoryBudgetsData, GetUserByIdData, GetUserByIdSummaryAccountsData, GetUserByIdSummaryBalanceData, GetUserByIdSummaryCategoriesData, GetUserByIdSummaryCategoriesSpendingData, GetUserByIdSummaryTotalsData, GetUserByIdTransactionsByTransactionIdData, GetUserByIdTransactionsData } from "../requests/types.gen";
import * as Common from "./common";
export const prefetchUseGetBanks = (queryClient: QueryClient, clientOptions: Options<unknown, true> = {}) => queryClient.prefetchQuery({ queryKey: Common.UseGetBanksKeyFn(clientOptions), queryFn: () => getBanks({ ...clientOptions }).then(response => response.data) });
export const prefetchUseGetUserById = (queryClient: QueryClient, clientOptions: Options<GetUserByIdData, true>) => queryClient.prefetchQuery({ queryKey: Common.UseGetUserByIdKeyFn(clientOptions), queryFn: () => getUserById({ ...clientOptions }).then(response => response.data) });
export const prefetchUseGetUserByIdAccounts = (queryClient: QueryClient, clientOptions: Options<GetUserByIdAccountsData, true>) => queryClient.prefetchQuery({ queryKey: Common.UseGetUserByIdAccountsKeyFn(clientOptions), queryFn: () => getUserByIdAccounts({ ...clientOptions }).then(response => response.data) });
export const prefetchUseGetUserByIdAccountsByAccountId = (queryClient: QueryClient, clientOptions: Options<GetUserByIdAccountsByAccountIdData, true>) => queryClient.prefetchQuery({ queryKey: Common.UseGetUserByIdAccountsByAccountIdKeyFn(clientOptions), queryFn: () => getUserByIdAccountsByAccountId({ ...clientOptions }).then(response => response.data) });
export const prefetchUseGetUserByIdTransactions = (queryClient: QueryClient, clientOptions: Options<GetUserByIdTransactionsData, true>) => queryClient.prefetchQuery({ queryKey: Common.UseGetUserByIdTransactionsKeyFn(clientOptions), queryFn: () => getUserByIdTransactions({ ...clientOptions }).then(response => response.data) });
export const prefetchUseGetUserByIdTransactionsByTransactionId = (queryClient: QueryClient, clientOptions: Options<GetUserByIdTransactionsByTransactionIdData, true>) => queryClient.prefetchQuery({ queryKey: Common.UseGetUserByIdTransactionsByTransactionIdKeyFn(clientOptions), queryFn: () => getUserByIdTransactionsByTransactionId({ ...clientOptions }).then(response => response.data) });
export const prefetchUseGetUserByIdCategories = (queryClient: QueryClient, clientOptions: Options<GetUserByIdCategoriesData, true>) => queryClient.prefetchQuery({ queryKey: Common.UseGetUserByIdCategoriesKeyFn(clientOptions), queryFn: () => getUserByIdCategories({ ...clientOptions }).then(response => response.data) });
export const prefetchUseGetUserByIdCategoriesByCategoryId = (queryClient: QueryClient, clientOptions: Options<GetUserByIdCategoriesByCategoryIdData, true>) => queryClient.prefetchQuery({ queryKey: Common.UseGetUserByIdCategoriesByCategoryIdKeyFn(clientOptions), queryFn: () => getUserByIdCategoriesByCategoryId({ ...clientOptions }).then(response => response.data) });
export const prefetchUseGetUserByIdSummaryAccounts = (queryClient: QueryClient, clientOptions: Options<GetUserByIdSummaryAccountsData, true>) => queryClient.prefetchQuery({ queryKey: Common.UseGetUserByIdSummaryAccountsKeyFn(clientOptions), queryFn: () => getUserByIdSummaryAccounts({ ...clientOptions }).then(response => response.data) });
export const prefetchUseGetUserByIdSummaryCategories = (queryClient: QueryClient, clientOptions: Options<GetUserByIdSummaryCategoriesData, true>) => queryClient.prefetchQuery({ queryKey: Common.UseGetUserByIdSummaryCategoriesKeyFn(clientOptions), queryFn: () => getUserByIdSummaryCategories({ ...clientOptions }).then(response => response.data) });
export const prefetchUseGetUserByIdSummaryCategoriesSpending = (queryClient: QueryClient, clientOptions: Options<GetUserByIdSummaryCategoriesSpendingData, true>) => queryClient.prefetchQuery({ queryKey: Common.UseGetUserByIdSummaryCategoriesSpendingKeyFn(clientOptions), queryFn: () => getUserByIdSummaryCategoriesSpending({ ...clientOptions }).then(response => response.data) });
export const prefetchUseGetUserByIdSummaryBalance = (queryClient: QueryClient, clientOptions: Options<GetUserByIdSummaryBalanceData, true>) => queryClient.prefetchQuery({ queryKey: Common.UseGetUserByIdSummaryBalanceKeyFn(clientOptions), queryFn: () => getUserByIdSummaryBalance({ ...clientOptions }).then(response => response.data) });
export const prefetchUseGetUserByIdSummaryTotals = (queryClient: QueryClient, clientOptions: Options<GetUserByIdSummaryTotalsData, true>) => queryClient.prefetchQuery({ queryKey: Common.UseGetUserByIdSummaryTotalsKeyFn(clientOptions), queryFn: () => getUserByIdSummaryTotals({ ...clientOptions }).then(response => response.data) });
export const prefetchUseGetUserByIdBudgetTransactions = (queryClient: QueryClient, clientOptions: Options<GetUserByIdBudgetTransactionsData, true>) => queryClient.prefetchQuery({ queryKey: Common.UseGetUserByIdBudgetTransactionsKeyFn(clientOptions), queryFn: () => getUserByIdBudgetTransactions({ ...clientOptions }).then(response => response.data) });
export const prefetchUseGetUserByIdBudgetTransactionsByBudgetTransactionId = (queryClient: QueryClient, clientOptions: Options<GetUserByIdBudgetTransactionsByBudgetTransactionIdData, true>) => queryClient.prefetchQuery({ queryKey: Common.UseGetUserByIdBudgetTransactionsByBudgetTransactionIdKeyFn(clientOptions), queryFn: () => getUserByIdBudgetTransactionsByBudgetTransactionId({ ...clientOptions }).then(response => response.data) });
export const prefetchUseGetUserByIdCategoryBudgets = (queryClient: QueryClient, clientOptions: Options<GetUserByIdCategoryBudgetsData, true>) => queryClient.prefetchQuery({ queryKey: Common.UseGetUserByIdCategoryBudgetsKeyFn(clientOptions), queryFn: () => getUserByIdCategoryBudgets({ ...clientOptions }).then(response => response.data) });
export const prefetchUseGetUserByIdCategoryBudgetsByCategoryBudgetId = (queryClient: QueryClient, clientOptions: Options<GetUserByIdCategoryBudgetsByCategoryBudgetIdData, true>) => queryClient.prefetchQuery({ queryKey: Common.UseGetUserByIdCategoryBudgetsByCategoryBudgetIdKeyFn(clientOptions), queryFn: () => getUserByIdCategoryBudgetsByCategoryBudgetId({ ...clientOptions }).then(response => response.data) });
