// generated with @7nohe/openapi-react-query-codegen@2.0.0-beta.3 

import { type Options } from "@hey-api/client-fetch";
import { UseQueryOptions, useSuspenseQuery } from "@tanstack/react-query";
import { getUserById, getUserByIdAccounts, getUserByIdAccountsByAccountId, getUserByIdAccountsByAccountIdTransactions, getUserByIdCategories, getUserByIdCategoriesByCategoryId } from "../requests/services.gen";
import { GetUserByIdAccountsByAccountIdData, GetUserByIdAccountsByAccountIdError, GetUserByIdAccountsByAccountIdTransactionsData, GetUserByIdAccountsByAccountIdTransactionsError, GetUserByIdAccountsData, GetUserByIdAccountsError, GetUserByIdCategoriesByCategoryIdData, GetUserByIdCategoriesByCategoryIdError, GetUserByIdCategoriesData, GetUserByIdCategoriesError, GetUserByIdData, GetUserByIdError } from "../requests/types.gen";
import * as Common from "./common";
export const useGetUserByIdSuspense = <TData = Common.GetUserByIdDefaultResponse, TError = GetUserByIdError, TQueryKey extends Array<unknown> = unknown[]>(clientOptions: Options<GetUserByIdData, true>, queryKey?: TQueryKey, options?: Omit<UseQueryOptions<TData, TError>, "queryKey" | "queryFn">) => useSuspenseQuery<TData, TError>({ queryKey: Common.UseGetUserByIdKeyFn(clientOptions, queryKey), queryFn: () => getUserById({ ...clientOptions }).then(response => response.data as TData) as TData, ...options });
export const useGetUserByIdAccountsSuspense = <TData = Common.GetUserByIdAccountsDefaultResponse, TError = GetUserByIdAccountsError, TQueryKey extends Array<unknown> = unknown[]>(clientOptions: Options<GetUserByIdAccountsData, true>, queryKey?: TQueryKey, options?: Omit<UseQueryOptions<TData, TError>, "queryKey" | "queryFn">) => useSuspenseQuery<TData, TError>({ queryKey: Common.UseGetUserByIdAccountsKeyFn(clientOptions, queryKey), queryFn: () => getUserByIdAccounts({ ...clientOptions }).then(response => response.data as TData) as TData, ...options });
export const useGetUserByIdAccountsByAccountIdSuspense = <TData = Common.GetUserByIdAccountsByAccountIdDefaultResponse, TError = GetUserByIdAccountsByAccountIdError, TQueryKey extends Array<unknown> = unknown[]>(clientOptions: Options<GetUserByIdAccountsByAccountIdData, true>, queryKey?: TQueryKey, options?: Omit<UseQueryOptions<TData, TError>, "queryKey" | "queryFn">) => useSuspenseQuery<TData, TError>({ queryKey: Common.UseGetUserByIdAccountsByAccountIdKeyFn(clientOptions, queryKey), queryFn: () => getUserByIdAccountsByAccountId({ ...clientOptions }).then(response => response.data as TData) as TData, ...options });
export const useGetUserByIdAccountsByAccountIdTransactionsSuspense = <TData = Common.GetUserByIdAccountsByAccountIdTransactionsDefaultResponse, TError = GetUserByIdAccountsByAccountIdTransactionsError, TQueryKey extends Array<unknown> = unknown[]>(clientOptions: Options<GetUserByIdAccountsByAccountIdTransactionsData, true>, queryKey?: TQueryKey, options?: Omit<UseQueryOptions<TData, TError>, "queryKey" | "queryFn">) => useSuspenseQuery<TData, TError>({ queryKey: Common.UseGetUserByIdAccountsByAccountIdTransactionsKeyFn(clientOptions, queryKey), queryFn: () => getUserByIdAccountsByAccountIdTransactions({ ...clientOptions }).then(response => response.data as TData) as TData, ...options });
export const useGetUserByIdCategoriesSuspense = <TData = Common.GetUserByIdCategoriesDefaultResponse, TError = GetUserByIdCategoriesError, TQueryKey extends Array<unknown> = unknown[]>(clientOptions: Options<GetUserByIdCategoriesData, true>, queryKey?: TQueryKey, options?: Omit<UseQueryOptions<TData, TError>, "queryKey" | "queryFn">) => useSuspenseQuery<TData, TError>({ queryKey: Common.UseGetUserByIdCategoriesKeyFn(clientOptions, queryKey), queryFn: () => getUserByIdCategories({ ...clientOptions }).then(response => response.data as TData) as TData, ...options });
export const useGetUserByIdCategoriesByCategoryIdSuspense = <TData = Common.GetUserByIdCategoriesByCategoryIdDefaultResponse, TError = GetUserByIdCategoriesByCategoryIdError, TQueryKey extends Array<unknown> = unknown[]>(clientOptions: Options<GetUserByIdCategoriesByCategoryIdData, true>, queryKey?: TQueryKey, options?: Omit<UseQueryOptions<TData, TError>, "queryKey" | "queryFn">) => useSuspenseQuery<TData, TError>({ queryKey: Common.UseGetUserByIdCategoriesByCategoryIdKeyFn(clientOptions, queryKey), queryFn: () => getUserByIdCategoriesByCategoryId({ ...clientOptions }).then(response => response.data as TData) as TData, ...options });
