// generated with @7nohe/openapi-react-query-codegen@2.0.0-beta.3 

import { type Options } from "@hey-api/client-fetch";
import { UseQueryOptions, useSuspenseQuery } from "@tanstack/react-query";
import { getBanks, getUserById, getUserByIdAccounts, getUserByIdAccountsByAccountId, getUserByIdBudgetTransactions, getUserByIdBudgetTransactionsByBudgetTransactionId, getUserByIdCategories, getUserByIdCategoriesByCategoryId, getUserByIdSummaryAccounts, getUserByIdSummaryBalance, getUserByIdSummaryCategories, getUserByIdTransactions, getUserByIdTransactionsByTransactionId } from "../requests/services.gen";
import { GetBanksError, GetUserByIdAccountsByAccountIdData, GetUserByIdAccountsByAccountIdError, GetUserByIdAccountsData, GetUserByIdAccountsError, GetUserByIdBudgetTransactionsByBudgetTransactionIdData, GetUserByIdBudgetTransactionsByBudgetTransactionIdError, GetUserByIdBudgetTransactionsData, GetUserByIdBudgetTransactionsError, GetUserByIdCategoriesByCategoryIdData, GetUserByIdCategoriesByCategoryIdError, GetUserByIdCategoriesData, GetUserByIdCategoriesError, GetUserByIdData, GetUserByIdError, GetUserByIdSummaryAccountsData, GetUserByIdSummaryAccountsError, GetUserByIdSummaryBalanceData, GetUserByIdSummaryBalanceError, GetUserByIdSummaryCategoriesData, GetUserByIdSummaryCategoriesError, GetUserByIdTransactionsByTransactionIdData, GetUserByIdTransactionsByTransactionIdError, GetUserByIdTransactionsData, GetUserByIdTransactionsError } from "../requests/types.gen";
import * as Common from "./common";
export const useGetBanksSuspense = <TData = Common.GetBanksDefaultResponse, TError = GetBanksError, TQueryKey extends Array<unknown> = unknown[]>(clientOptions: Options<unknown, true> = {}, queryKey?: TQueryKey, options?: Omit<UseQueryOptions<TData, TError>, "queryKey" | "queryFn">) => useSuspenseQuery<TData, TError>({ queryKey: Common.UseGetBanksKeyFn(clientOptions, queryKey), queryFn: () => getBanks({ ...clientOptions }).then(response => response.data as TData) as TData, ...options });
export const useGetUserByIdSuspense = <TData = Common.GetUserByIdDefaultResponse, TError = GetUserByIdError, TQueryKey extends Array<unknown> = unknown[]>(clientOptions: Options<GetUserByIdData, true>, queryKey?: TQueryKey, options?: Omit<UseQueryOptions<TData, TError>, "queryKey" | "queryFn">) => useSuspenseQuery<TData, TError>({ queryKey: Common.UseGetUserByIdKeyFn(clientOptions, queryKey), queryFn: () => getUserById({ ...clientOptions }).then(response => response.data as TData) as TData, ...options });
export const useGetUserByIdAccountsSuspense = <TData = Common.GetUserByIdAccountsDefaultResponse, TError = GetUserByIdAccountsError, TQueryKey extends Array<unknown> = unknown[]>(clientOptions: Options<GetUserByIdAccountsData, true>, queryKey?: TQueryKey, options?: Omit<UseQueryOptions<TData, TError>, "queryKey" | "queryFn">) => useSuspenseQuery<TData, TError>({ queryKey: Common.UseGetUserByIdAccountsKeyFn(clientOptions, queryKey), queryFn: () => getUserByIdAccounts({ ...clientOptions }).then(response => response.data as TData) as TData, ...options });
export const useGetUserByIdAccountsByAccountIdSuspense = <TData = Common.GetUserByIdAccountsByAccountIdDefaultResponse, TError = GetUserByIdAccountsByAccountIdError, TQueryKey extends Array<unknown> = unknown[]>(clientOptions: Options<GetUserByIdAccountsByAccountIdData, true>, queryKey?: TQueryKey, options?: Omit<UseQueryOptions<TData, TError>, "queryKey" | "queryFn">) => useSuspenseQuery<TData, TError>({ queryKey: Common.UseGetUserByIdAccountsByAccountIdKeyFn(clientOptions, queryKey), queryFn: () => getUserByIdAccountsByAccountId({ ...clientOptions }).then(response => response.data as TData) as TData, ...options });
export const useGetUserByIdTransactionsSuspense = <TData = Common.GetUserByIdTransactionsDefaultResponse, TError = GetUserByIdTransactionsError, TQueryKey extends Array<unknown> = unknown[]>(clientOptions: Options<GetUserByIdTransactionsData, true>, queryKey?: TQueryKey, options?: Omit<UseQueryOptions<TData, TError>, "queryKey" | "queryFn">) => useSuspenseQuery<TData, TError>({ queryKey: Common.UseGetUserByIdTransactionsKeyFn(clientOptions, queryKey), queryFn: () => getUserByIdTransactions({ ...clientOptions }).then(response => response.data as TData) as TData, ...options });
export const useGetUserByIdTransactionsByTransactionIdSuspense = <TData = Common.GetUserByIdTransactionsByTransactionIdDefaultResponse, TError = GetUserByIdTransactionsByTransactionIdError, TQueryKey extends Array<unknown> = unknown[]>(clientOptions: Options<GetUserByIdTransactionsByTransactionIdData, true>, queryKey?: TQueryKey, options?: Omit<UseQueryOptions<TData, TError>, "queryKey" | "queryFn">) => useSuspenseQuery<TData, TError>({ queryKey: Common.UseGetUserByIdTransactionsByTransactionIdKeyFn(clientOptions, queryKey), queryFn: () => getUserByIdTransactionsByTransactionId({ ...clientOptions }).then(response => response.data as TData) as TData, ...options });
export const useGetUserByIdCategoriesSuspense = <TData = Common.GetUserByIdCategoriesDefaultResponse, TError = GetUserByIdCategoriesError, TQueryKey extends Array<unknown> = unknown[]>(clientOptions: Options<GetUserByIdCategoriesData, true>, queryKey?: TQueryKey, options?: Omit<UseQueryOptions<TData, TError>, "queryKey" | "queryFn">) => useSuspenseQuery<TData, TError>({ queryKey: Common.UseGetUserByIdCategoriesKeyFn(clientOptions, queryKey), queryFn: () => getUserByIdCategories({ ...clientOptions }).then(response => response.data as TData) as TData, ...options });
export const useGetUserByIdCategoriesByCategoryIdSuspense = <TData = Common.GetUserByIdCategoriesByCategoryIdDefaultResponse, TError = GetUserByIdCategoriesByCategoryIdError, TQueryKey extends Array<unknown> = unknown[]>(clientOptions: Options<GetUserByIdCategoriesByCategoryIdData, true>, queryKey?: TQueryKey, options?: Omit<UseQueryOptions<TData, TError>, "queryKey" | "queryFn">) => useSuspenseQuery<TData, TError>({ queryKey: Common.UseGetUserByIdCategoriesByCategoryIdKeyFn(clientOptions, queryKey), queryFn: () => getUserByIdCategoriesByCategoryId({ ...clientOptions }).then(response => response.data as TData) as TData, ...options });
export const useGetUserByIdSummaryAccountsSuspense = <TData = Common.GetUserByIdSummaryAccountsDefaultResponse, TError = GetUserByIdSummaryAccountsError, TQueryKey extends Array<unknown> = unknown[]>(clientOptions: Options<GetUserByIdSummaryAccountsData, true>, queryKey?: TQueryKey, options?: Omit<UseQueryOptions<TData, TError>, "queryKey" | "queryFn">) => useSuspenseQuery<TData, TError>({ queryKey: Common.UseGetUserByIdSummaryAccountsKeyFn(clientOptions, queryKey), queryFn: () => getUserByIdSummaryAccounts({ ...clientOptions }).then(response => response.data as TData) as TData, ...options });
export const useGetUserByIdSummaryCategoriesSuspense = <TData = Common.GetUserByIdSummaryCategoriesDefaultResponse, TError = GetUserByIdSummaryCategoriesError, TQueryKey extends Array<unknown> = unknown[]>(clientOptions: Options<GetUserByIdSummaryCategoriesData, true>, queryKey?: TQueryKey, options?: Omit<UseQueryOptions<TData, TError>, "queryKey" | "queryFn">) => useSuspenseQuery<TData, TError>({ queryKey: Common.UseGetUserByIdSummaryCategoriesKeyFn(clientOptions, queryKey), queryFn: () => getUserByIdSummaryCategories({ ...clientOptions }).then(response => response.data as TData) as TData, ...options });
export const useGetUserByIdSummaryBalanceSuspense = <TData = Common.GetUserByIdSummaryBalanceDefaultResponse, TError = GetUserByIdSummaryBalanceError, TQueryKey extends Array<unknown> = unknown[]>(clientOptions: Options<GetUserByIdSummaryBalanceData, true>, queryKey?: TQueryKey, options?: Omit<UseQueryOptions<TData, TError>, "queryKey" | "queryFn">) => useSuspenseQuery<TData, TError>({ queryKey: Common.UseGetUserByIdSummaryBalanceKeyFn(clientOptions, queryKey), queryFn: () => getUserByIdSummaryBalance({ ...clientOptions }).then(response => response.data as TData) as TData, ...options });
export const useGetUserByIdBudgetTransactionsSuspense = <TData = Common.GetUserByIdBudgetTransactionsDefaultResponse, TError = GetUserByIdBudgetTransactionsError, TQueryKey extends Array<unknown> = unknown[]>(clientOptions: Options<GetUserByIdBudgetTransactionsData, true>, queryKey?: TQueryKey, options?: Omit<UseQueryOptions<TData, TError>, "queryKey" | "queryFn">) => useSuspenseQuery<TData, TError>({ queryKey: Common.UseGetUserByIdBudgetTransactionsKeyFn(clientOptions, queryKey), queryFn: () => getUserByIdBudgetTransactions({ ...clientOptions }).then(response => response.data as TData) as TData, ...options });
export const useGetUserByIdBudgetTransactionsByBudgetTransactionIdSuspense = <TData = Common.GetUserByIdBudgetTransactionsByBudgetTransactionIdDefaultResponse, TError = GetUserByIdBudgetTransactionsByBudgetTransactionIdError, TQueryKey extends Array<unknown> = unknown[]>(clientOptions: Options<GetUserByIdBudgetTransactionsByBudgetTransactionIdData, true>, queryKey?: TQueryKey, options?: Omit<UseQueryOptions<TData, TError>, "queryKey" | "queryFn">) => useSuspenseQuery<TData, TError>({ queryKey: Common.UseGetUserByIdBudgetTransactionsByBudgetTransactionIdKeyFn(clientOptions, queryKey), queryFn: () => getUserByIdBudgetTransactionsByBudgetTransactionId({ ...clientOptions }).then(response => response.data as TData) as TData, ...options });
