/**
 * Generated by @openapi-codegen
 *
 * @version 1.0.0
 */
export type LoginRequest = {
  email: string;
  password: string;
};

export type LoginResponse = {
  token: string;
  id: number;
};

export type SignupRequest = {
  /**
   * @example user@example.com
   */
  email?: string;
  /**
   * @example password
   */
  password?: string;
};

export type SignupResponse = {
  id: number;
};

export type User = {
  id: number;
  email: string;
  /**
   * @format date-time
   */
  created_at: string;
};

export type AccountCreateRequest = {
  /**
   * @example Checking Account
   */
  name: string;
};

export type AccountCreateResponse = {
  id: number;
};

export type Account = {
  id: number;
  name: string;
  /**
   * @format date-time
   */
  created_at: string;
};

export type AccountDeleteResponse = {
  id: number;
  message: string;
};

export type CategoryCreateRequest = {
  /**
   * @example Groceries
   */
  name: string;
};

export type CategoryCreateResponse = {
  id: number;
};

export type Category = {
  id: number;
  name: string;
  /**
   * @format date-time
   */
  created_at: string;
};

export type CategoryDeleteResponse = {
  id: number;
  message: string;
};

export type TransactionCreateRequest = {
  /**
   * @example 100
   */
  amount: number;
  category_id: number;
  /**
   * @example Milk
   */
  description?: string;
};

export type TransactionCreateResponse = {
  id: number;
};

export type Transaction = {
  id: number;
  amount: number;
  category?: Category;
  description: string;
  /**
   * @format date-time
   */
  date: string;
  /**
   * @format date-time
   */
  created_at: string;
};

export type TransactionDeleteResponse = {
  id: number;
  message: string;
};
