openapi: 3.0.0
info:
  version: 1.0.0
  title: Finance Tracker API
paths:
  /login:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginRequest"
      responses:
        "200":
          description: Login response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LoginResponse"
  /signup:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SignupRequest"
      responses:
        "200":
          description: Sign up response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SignupResponse"
  /user/{id}:
    get:
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: User response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
  /user/{id}/accounts:
    post:
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AccountCreateRequest"
      responses:
        "200":
          description: Account response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AccountCreateResponse"
    get:
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Account response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Account"
  /user/{id}/accounts/{account_id}:
    get:
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
        - name: account_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Account response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Account"
    delete:
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
        - name: account_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Account response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AccountDeleteResponse"
  /user/{id}/accounts/{account_id}/transactions:
    post:
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
        - name: account_id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TransactionCreateRequest"
      responses:
        "200":
          description: Transaction response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TransactionCreateResponse"
    get:
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
        - name: account_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Transaction response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Transaction"
  /user/{id}/accounts/{account_id}/transactions/{transaction_id}:
    delete:
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
        - name: account_id
          in: path
          required: true
          schema:
            type: integer
        - name: transaction_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Transaction response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TransactionDeleteResponse"
  /user/{id}/categories:
    post:
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CategoryCreateRequest"
      responses:
        "200":
          description: Category response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CategoryCreateResponse"
    get:
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Category response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Category"
  /user/{id}/categories/{category_id}:
    get:
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
        - name: category_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Category response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Category"
    delete:
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
        - name: category_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Category response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CategoryDeleteResponse"
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    LoginRequest:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
      required:
        - email
        - password
    LoginResponse:
      type: object
      properties:
        token:
          type: string
        id:
          type: integer
      required:
        - token
        - id
    SignupRequest:
      type: object
      properties:
        email:
          type: string
          example: user@example.com
        password:
          type: string
          example: password
    SignupResponse:
      type: object
      properties:
        id:
          type: integer
      required:
        - id
    User:
      type: object
      properties:
        id:
          type: integer
        email:
          type: string
        created_at:
          type: string
          format: date-time
      required:
        - id
        - email
        - created_at
    AccountCreateRequest:
      type: object
      properties:
        name:
          type: string
          example: "Checking Account"
      required:
        - name
    AccountCreateResponse:
      type: object
      properties:
        id:
          type: integer
      required:
        - id
    Account:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        created_at:
          type: string
          format: date-time
      required:
        - id
        - name
        - created_at
    AccountDeleteResponse:
      type: object
      properties:
        id:
          type: integer
        message:
          type: string
      required:
        - id
        - message
    CategoryCreateRequest:
      type: object
      properties:
        name:
          type: string
          example: "Groceries"
      required:
        - name
    CategoryCreateResponse:
      type: object
      properties:
        id:
          type: integer
      required:
        - id
    Category:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        created_at:
          type: string
          format: date-time
      required:
        - id
        - name
        - created_at
    CategoryDeleteResponse:
      type: object
      properties:
        id:
          type: integer
        message:
          type: string
      required:
        - id
        - message
    TransactionCreateRequest:
      type: object
      properties:
        amount:
          type: number
          example: 100.00
        category_id:
          type: integer
        description:
          type: string
          example: "Milk"
      required:
        - amount
        - category_id
    TransactionCreateResponse:
      type: object
      properties:
        id:
          type: integer
      required:
        - id
    Transaction:
      type: object
      properties:
        id:
          type: integer
        amount:
          type: number
        category:
          $ref: "#/components/schemas/Category"
        description:
          type: string
        date:
          type: string
          format: date-time
        created_at:
          type: string
          format: date-time
      required:
        - id
        - amount
        - description
        - date
        - created_at
    TransactionDeleteResponse:
      type: object
      properties:
        id:
          type: integer
        message:
          type: string
      required:
        - id
        - message
