openapi: 3.0.0
info:
  version: 1.0.0
  title: Finance Tracker API
paths:
  /login:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginRequest"
      responses:
        "200":
          description: Login response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LoginResponse"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NotFound"
        "404":
          description: Not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NotFound"
  /signup:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SignupRequest"
      responses:
        "200":
          description: Sign up response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SignupResponse"
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NotAuthorized"
  /banks:
    get:
      security:
        - BearerAuth: []
      responses:
        "200":
          description: List of banks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Bank"
        "404":
          description: Not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NotFound"
  /user/{id}:
    get:
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: User response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "404":
          description: User not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NotFound"
  /user/{id}/accounts:
    post:
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AccountCreateRequest"
      responses:
        "200":
          description: Account response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AccountCreateResponse"
    get:
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Account response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Account"
        "404":
          description: User not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NotFound"
  /user/{id}/accounts/{account_id}:
    get:
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
        - name: account_id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Account response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Account"
        "404":
          description: Account not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NotFound"
    delete:
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
        - name: account_id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Account response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AccountDeleteResponse"
        "404":
          description: Account not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NotFound"
  /user/{id}/transactions:
    post:
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TransactionCreateRequest"
      responses:
        "200":
          description: Transaction response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TransactionCreateResponse"
    get:
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
        - name: account_id
          in: query
          required: false
          schema:
            type: string
      responses:
        "200":
          description: Transaction response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Transaction"
        "404":
          description: User not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NotFound"
  /user/{id}/transactions/{transaction_id}:
    delete:
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
        - name: transaction_id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Transaction response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TransactionDeleteResponse"
        "404":
          description: Transaction not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NotFound"
  /user/{id}/categories:
    post:
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CategoryCreateRequest"
      responses:
        "200":
          description: Category response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CategoryCreateResponse"
    get:
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Category response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Category"
        "404":
          description: User not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NotFound"
  /user/{id}/categories/{category_id}:
    get:
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
        - name: category_id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Category response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Category"
        "404":
          description: Category not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NotFound"
    delete:
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
        - name: category_id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Category response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CategoryDeleteResponse"
        "404":
          description: Category not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NotFound"
  /user/{id}/categories/{category_id}/rules:
    post:
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
        - name: category_id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CategoryAddRuleRequest"
      responses:
        "200":
          description: Category rule added response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CategoryAddRuleResponse"
  /user/{id}/categories/{category_id}/rules/{rule_id}:
    patch:
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
        - name: category_id
          in: path
          required: true
          schema:
            type: string
        - name: rule_id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CategoryEditRuleRequest"
      responses:
        "200":
          description: Category rule edited response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CategoryEditRuleResponse"
        "404":
          description: Rule not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NotFound"
    delete:
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
        - name: category_id
          in: path
          required: true
          schema:
            type: string
        - name: rule_id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Category rule deleted response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CategoryEditRuleResponse"
        "404":
          description: Rule not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NotFound"
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    # Requests
    LoginRequest:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
      required:
        - email
        - password
    SignupRequest:
      type: object
      properties:
        email:
          type: string
          example: user@example.com
        password:
          type: string
          example: password
    AccountCreateRequest:
      type: object
      properties:
        name:
          type: string
          example: "Checking Account"
        bank_id:
          type: string
        opened_at:
          type: string
          format: date-time
      required:
        - name
        - bank_id
        - opened_at
    CategoryCreateRequest:
      type: object
      properties:
        name:
          type: string
          example: "Groceries"
      required:
        - name
    CategoryAddRuleRequest:
      type: object
      properties:
        category_id:
          type: string
        rule:
          type: string
          example: "Tesco"
    CategoryEditRuleRequest:
      type: object
      properties:
        category_id:
          type: string
        rule_id:
          type: string
        rule:
          type: string
          example: "Tesco"
    TransactionCreateRequest:
      type: object
      properties:
        account_id:
          type: string
        amount:
          type: number
          example: 100.00
        category_id:
          type: string
        description:
          type: string
          example: "Milk"
      required:
        - account_id
        - amount
        - category_id
        - description
    # Responses
    LoginResponse:
      type: object
      properties:
        token:
          type: string
        id:
          type: string
      required:
        - token
        - id
    SignupResponse:
      type: object
      properties:
        message:
          type: string
      required:
        - message
    AccountCreateResponse:
      type: object
      properties:
        ids:
          type: array
          items:
            type: string
      required:
        - ids
    AccountDeleteResponse:
      type: object
      properties:
        id:
          type: string
        message:
          type: string
      required:
        - id
        - message
    CategoryCreateResponse:
      type: object
      properties:
        id:
          type: string
      required:
        - id
    CategoryDeleteResponse:
      type: object
      properties:
        id:
          type: string
        message:
          type: string
      required:
        - id
        - message
    CategoryAddRuleResponse:
      type: object
      properties:
        id:
          type: string
        rule_id:
          type: string
      required:
        - id
        - rule_id
    CategoryEditRuleResponse:
      type: object
      properties:
        id:
          type: string
        rule_id:
          type: string
      required:
        - id
        - rule_id
    CategoryDeleteRuleResponse:
      type: object
      properties:
        id:
          type: string
        rule_id:
          type: string
        message:
          type: string
      required:
        - id
        - rule_id
        - message
    TransactionCreateResponse:
      type: object
      properties:
        id:
          type: string
      required:
        - id
    TransactionDeleteResponse:
      type: object
      properties:
        id:
          type: string
        message:
          type: string
      required:
        - id
        - message
    # Errors
    NotAuthorized:
      type: object
      properties:
        message:
          type: string
          const: "Not authorized"
    NotFound:
      type: object
      properties:
        message:
          type: string
          const: "Not found"
    # Schemas
    User:
      type: object
      properties:
        id:
          type: string
        email:
          type: string
        created_at:
          type: string
          format: date-time
      required:
        - id
        - email
        - created_at
    Account:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        bank:
          $ref: "#/components/schemas/Bank"
        opened_at:
          type: string
          format: date-time
        closed_at:
          type: string
          format: date-time
      required:
        - id
        - name
        - bank
        - opened_at
    Bank:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        fixed_products:
          type: boolean
        csv_import_enabled:
          type: boolean
        api_import_enabled:
          type: boolean
      required:
        - id
        - name
        - csv_import_enabled
        - api_import_enabled
    Category:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        created_at:
          type: string
          format: date-time
        rules:
          type: array
          items:
            $ref: "#/components/schemas/CategoryRule"
      required:
        - id
        - name
        - created_at
        - rules
    CategoryRule:
      type: object
      properties:
        id:
          type: string
        account:
          $ref: "#/components/schemas/Account"
        rule:
          type: string
      required:
        - id
        - account
        - rule
    Transaction:
      type: object
      properties:
        id:
          type: string
        amount:
          type: number
        category:
          $ref: "#/components/schemas/Category"
        account:
          $ref: "#/components/schemas/Account"
        description:
          type: string
        date:
          type: string
          format: date-time
        created_at:
          type: string
          format: date-time
      required:
        - id
        - amount
        - account
        - description
        - date
        - created_at
