// This file is auto-generated by @hey-api/openapi-ts

export const LoginRequestSchema = {
    type: 'object',
    properties: {
        email: {
            type: 'string'
        },
        password: {
            type: 'string'
        }
    },
    required: ['email', 'password']
} as const;

export const SignupRequestSchema = {
    type: 'object',
    properties: {
        email: {
            type: 'string',
            example: 'user@example.com'
        },
        password: {
            type: 'string'
        },
        master_key: {
            type: 'string'
        },
        salt: {
            type: 'string'
        }
    },
    required: ['email', 'password', 'master_key', 'salt']
} as const;

export const AccountCreateRequestSchema = {
    type: 'object',
    properties: {
        name: {
            type: 'string',
            example: 'Checking Account'
        },
        bank_id: {
            type: 'string'
        },
        opened_at: {
            type: 'string',
            format: 'date-time'
        }
    },
    required: ['name', 'bank_id', 'opened_at']
} as const;

export const AccountEditRequestSchema = {
    type: 'object',
    properties: {
        name: {
            type: 'string',
            example: 'Checking Account'
        },
        bank_id: {
            type: 'string'
        },
        opened_at: {
            type: 'string',
            format: 'date-time'
        },
        closed_at: {
            type: 'string',
            format: 'date-time'
        }
    }
} as const;

export const CategoryCreateRequestSchema = {
    type: 'object',
    properties: {
        name: {
            type: 'string'
        }
    },
    required: ['name']
} as const;

export const CategoryEditRequestSchema = {
    type: 'object',
    properties: {
        name: {
            type: 'string'
        }
    },
    required: ['name']
} as const;

export const CategoryAddRuleRequestSchema = {
    type: 'object',
    properties: {
        account_id: {
            type: 'string'
        },
        description: {
            type: 'string'
        },
        rule: {
            type: 'string'
        }
    }
} as const;

export const CategoryEditRuleRequestSchema = {
    type: 'object',
    properties: {
        account_id: {
            type: 'string'
        },
        description: {
            type: 'string'
        },
        rule: {
            type: 'string'
        }
    }
} as const;

export const TransactionCreateRequestSchema = {
    type: 'object',
    properties: {
        account_id: {
            type: 'string'
        },
        amount: {
            type: 'number',
            example: 100
        },
        category_id: {
            type: 'string'
        },
        description: {
            type: 'string'
        },
        date: {
            type: 'string',
            format: 'date'
        }
    },
    required: ['account_id', 'amount', 'description', 'date']
} as const;

export const TransactionEditRequestSchema = {
    type: 'object',
    properties: {
        account_id: {
            type: 'string'
        },
        amount: {
            type: 'number',
            example: 100
        },
        category_id: {
            type: 'string'
        },
        description: {
            type: 'string'
        },
        date: {
            type: 'string',
            format: 'date'
        }
    }
} as const;

export const TransactionBulkCreateRequestSchema = {
    type: 'object',
    properties: {
        hash: {
            type: 'string'
        },
        transactions: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/TransactionCreateRequest'
            }
        }
    },
    required: ['hash', 'transactions']
} as const;

export const TransactionBulkFinaliseRequestSchema = {
    type: 'object',
    properties: {
        hash: {
            type: 'string'
        }
    },
    required: ['hash']
} as const;

export const TransactionBulkDeleteRequestSchema = {
    type: 'object',
    properties: {
        hash: {
            type: 'string'
        },
        cancel: {
            type: 'boolean',
            default: false
        }
    },
    required: ['hash']
} as const;

export const BudgetTransactionCreateRequestSchema = {
    type: 'object',
    properties: {
        category_id: {
            type: 'string'
        },
        amount: {
            type: 'number',
            example: 100
        },
        description: {
            type: 'string'
        },
        repeat_until: {
            '$ref': '#/components/schemas/PeriodUnit'
        },
        repeat_every: {
            type: 'number',
            example: 1
        },
        starts_on: {
            type: 'string',
            format: 'date'
        },
        ends_on: {
            type: 'string',
            format: 'date'
        }
    },
    required: ['amount', 'repeat_until', 'repeat_every', 'starts_on']
} as const;

export const BudgetTransactionEditRequestSchema = {
    type: 'object',
    properties: {
        category_id: {
            type: 'string'
        },
        amount: {
            type: 'number',
            example: 100
        },
        description: {
            type: 'string'
        },
        repeat_until: {
            '$ref': '#/components/schemas/PeriodUnit'
        },
        repeat_every: {
            type: 'number',
            example: 1
        },
        ends_on: {
            type: 'string',
            format: 'date'
        },
        effective_from: {
            type: 'string',
            format: 'date'
        }
    },
    required: ['amount', 'repeat_until', 'repeat_every', 'effective_from']
} as const;

export const CategoryBudgetCreateRequestSchema = {
    type: 'object',
    properties: {
        category_id: {
            type: 'string'
        },
        amount: {
            type: 'number',
            example: 200
        },
        repeat_until: {
            '$ref': '#/components/schemas/PeriodUnit'
        },
        repeat_every: {
            type: 'number',
            example: 1
        },
        starts_on: {
            type: 'string',
            format: 'date'
        },
        ends_on: {
            type: 'string',
            format: 'date'
        }
    },
    required: ['category_id', 'amount', 'repeat_until', 'repeat_every', 'starts_on']
} as const;

export const CategoryBudgetEditRequestSchema = {
    type: 'object',
    properties: {
        category_id: {
            type: 'string'
        },
        amount: {
            type: 'number',
            example: 200
        },
        repeat_until: {
            '$ref': '#/components/schemas/PeriodUnit'
        },
        repeat_every: {
            type: 'number',
            example: 1
        },
        ends_on: {
            type: 'string',
            format: 'date'
        },
        effective_from: {
            type: 'string',
            format: 'date'
        }
    },
    required: ['amount', 'repeat_until', 'repeat_every', 'effective_from']
} as const;

export const LoginResponseSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        token: {
            type: 'string'
        },
        master_key: {
            type: 'string'
        },
        salt: {
            type: 'string'
        }
    },
    required: ['id', 'token', 'master_key', 'salt']
} as const;

export const SignupResponseSchema = {
    type: 'object',
    properties: {
        message: {
            type: 'string'
        }
    },
    required: ['message']
} as const;

export const AccountCreateResponseSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        }
    },
    required: ['id']
} as const;

export const AccountEditResponseSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        }
    },
    required: ['id']
} as const;

export const AccountDeleteResponseSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        message: {
            type: 'string'
        }
    },
    required: ['id', 'message']
} as const;

export const CategoryCreateResponseSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        }
    },
    required: ['id']
} as const;

export const CategoryEditResponseSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        }
    },
    required: ['id']
} as const;

export const CategoryDeleteResponseSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        message: {
            type: 'string'
        }
    },
    required: ['id', 'message']
} as const;

export const CategoryAddRuleResponseSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        }
    },
    required: ['id']
} as const;

export const CategoryEditRuleResponseSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        }
    },
    required: ['id']
} as const;

export const CategoryDeleteRuleResponseSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        message: {
            type: 'string'
        }
    },
    required: ['id', 'message']
} as const;

export const TransactionsResponseSchema = {
    type: 'object',
    properties: {
        transactions: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/Transaction'
            }
        },
        cursor: {
            type: 'string'
        }
    },
    required: ['transactions']
} as const;

export const TransactionCreateResponseSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        }
    },
    required: ['id']
} as const;

export const TransactionEditResponseSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        }
    },
    required: ['id']
} as const;

export const TransactionDeleteResponseSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        message: {
            type: 'string'
        }
    },
    required: ['id', 'message']
} as const;

export const TransactionBulkResponseSchema = {
    type: 'object',
    properties: {
        message: {
            type: 'string'
        }
    },
    required: ['message']
} as const;

export const BudgetTransactionCreateResponseSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        }
    },
    required: ['id']
} as const;

export const BudgetTransactionEditResponseSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        }
    },
    required: ['id']
} as const;

export const BudgetTransactionDeleteResponseSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        message: {
            type: 'string'
        }
    },
    required: ['id', 'message']
} as const;

export const CategoryBudgetCreateResponseSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        }
    },
    required: ['id']
} as const;

export const CategoryBudgetEditResponseSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        }
    },
    required: ['id']
} as const;

export const CategoryBudgetDeleteResponseSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        message: {
            type: 'string'
        }
    },
    required: ['id', 'message']
} as const;

export const NotAuthorizedSchema = {
    type: 'object',
    properties: {
        message: {
            type: 'string',
            const: 'Not authorized'
        }
    }
} as const;

export const NotFoundSchema = {
    type: 'object',
    properties: {
        message: {
            type: 'string',
            const: 'Not found'
        }
    }
} as const;

export const ConflictSchema = {
    type: 'object',
    properties: {
        message: {
            type: 'string'
        }
    },
    required: ['message']
} as const;

export const UserSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        email: {
            type: 'string'
        },
        created_at: {
            type: 'string',
            format: 'date-time'
        }
    },
    required: ['id', 'email', 'created_at']
} as const;

export const AccountSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        name: {
            type: 'string'
        },
        bank: {
            '$ref': '#/components/schemas/Bank'
        },
        opened_at: {
            type: 'string',
            format: 'date-time'
        },
        closed_at: {
            type: 'string',
            format: 'date-time'
        }
    },
    required: ['id', 'name', 'bank', 'opened_at']
} as const;

export const BankSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        name: {
            type: 'string'
        },
        short_name: {
            type: 'string'
        },
        fixed_products: {
            type: 'boolean'
        },
        csv_import_enabled: {
            type: 'boolean'
        },
        api_import_enabled: {
            type: 'boolean'
        }
    },
    required: ['id', 'name', 'short_name', 'csv_import_enabled', 'api_import_enabled']
} as const;

export const CategorySchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        name: {
            type: 'string'
        },
        created_at: {
            type: 'string',
            format: 'date-time'
        },
        rules: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/CategoryRule'
            }
        }
    },
    required: ['id', 'name', 'created_at', 'rules']
} as const;

export const CategoryRuleSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        account: {
            '$ref': '#/components/schemas/Account'
        },
        description: {
            type: 'string'
        },
        rule: {
            type: 'string'
        }
    },
    required: ['id', 'account', 'rule']
} as const;

export const TransactionSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        amount: {
            type: 'number'
        },
        category: {
            '$ref': '#/components/schemas/Category'
        },
        account: {
            '$ref': '#/components/schemas/Account'
        },
        description: {
            type: 'string'
        },
        date: {
            type: 'string',
            format: 'date'
        },
        created_at: {
            type: 'string',
            format: 'date-time'
        }
    },
    required: ['id', 'amount', 'account', 'description', 'date', 'created_at']
} as const;

export const BudgetTransactionSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        category: {
            '$ref': '#/components/schemas/Category'
        },
        amount: {
            type: 'number'
        },
        description: {
            type: 'string'
        },
        repeat_until: {
            '$ref': '#/components/schemas/PeriodUnit'
        },
        repeat_every: {
            type: 'number'
        },
        starts_on: {
            type: 'string',
            format: 'date'
        },
        ends_on: {
            type: 'string',
            format: 'date'
        },
        created_at: {
            type: 'string',
            format: 'date-time'
        },
        deleted_at: {
            type: 'string',
            format: 'date-time'
        }
    },
    required: ['id', 'amount', 'repeat_until', 'repeat_every', 'starts_on', 'created_at']
} as const;

export const CategoryBudgetSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        category: {
            '$ref': '#/components/schemas/Category'
        },
        amount: {
            type: 'number'
        },
        repeat_until: {
            '$ref': '#/components/schemas/PeriodUnit'
        },
        repeat_every: {
            type: 'number'
        },
        starts_on: {
            type: 'string',
            format: 'date'
        },
        ends_on: {
            type: 'string',
            format: 'date'
        },
        created_at: {
            type: 'string',
            format: 'date-time'
        },
        deleted_at: {
            type: 'string',
            format: 'date-time'
        }
    },
    required: ['id', 'category', 'amount', 'repeat_until', 'repeat_every', 'starts_on', 'created_at']
} as const;

export const AllAccountSummarySchema = {
    type: 'object',
    properties: {
        accounts: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/AccountSummary'
            }
        },
        total: {
            type: 'number'
        }
    },
    required: ['accounts', 'total']
} as const;

export const AccountSummarySchema = {
    type: 'object',
    properties: {
        account: {
            '$ref': '#/components/schemas/Account'
        },
        balance: {
            type: 'number'
        }
    },
    required: ['account', 'balance']
} as const;

export const CategorySummarySchema = {
    type: 'object',
    properties: {
        category: {
            '$ref': '#/components/schemas/Category'
        },
        total: {
            type: 'number'
        },
        percentage: {
            type: 'number'
        }
    },
    required: ['total', 'percentage']
} as const;

export const CategorySpendingSummarySchema = {
    type: 'object',
    properties: {
        categories: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/CategorySpendingSeries'
            }
        }
    },
    required: ['categories']
} as const;

export const CategorySpendingSeriesSchema = {
    type: 'object',
    properties: {
        category: {
            '$ref': '#/components/schemas/Category'
        },
        amounts: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/SpendingDatapoint'
            }
        }
    },
    required: ['amounts']
} as const;

export const SpendingDatapointSchema = {
    type: 'object',
    properties: {
        date: {
            type: 'string',
            format: 'date-time'
        },
        amount: {
            type: 'number'
        }
    },
    required: ['date', 'amount']
} as const;

export const BalanceSummarySchema = {
    type: 'object',
    properties: {
        total: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/BalanceDatapoint'
            }
        },
        accounts: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/BalanceSummaryAccount'
            }
        }
    },
    required: ['total', 'accounts']
} as const;

export const BalanceSummaryAccountSchema = {
    type: 'object',
    properties: {
        account: {
            '$ref': '#/components/schemas/Account'
        },
        balance: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/BalanceDatapoint'
            }
        }
    },
    required: ['account', 'balance']
} as const;

export const BalanceDatapointSchema = {
    type: 'object',
    properties: {
        date: {
            type: 'string',
            format: 'date-time'
        },
        balance: {
            type: 'number'
        }
    },
    required: ['date', 'balance']
} as const;

export const TotalsSummarySchema = {
    type: 'object',
    properties: {
        income: {
            type: 'number'
        },
        outgoing: {
            type: 'number'
        },
        net: {
            type: 'number'
        }
    },
    required: ['income', 'outgoing', 'net']
} as const;

export const PeriodUnitSchema = {
    type: 'string',
    enum: ['day', 'week', 'month', 'year'],
    default: 'month'
} as const;

export const SummaryIntervalSchema = {
    type: 'string',
    enum: ['day', 'week', 'month', 'year'],
    default: 'day'
} as const;

export const TimePeriodSchema = {
    type: 'string',
    enum: ['week', 'month', 'year', 'ytd', 'all'],
    default: 'year'
} as const;