// This file is auto-generated by @hey-api/openapi-ts

export const LoginRequestSchema = {
    type: 'object',
    properties: {
        email: {
            type: 'string'
        },
        password: {
            type: 'string'
        }
    },
    required: ['email', 'password']
} as const;

export const SignupRequestSchema = {
    type: 'object',
    properties: {
        email: {
            type: 'string',
            example: 'user@example.com'
        },
        password: {
            type: 'string',
            example: 'password'
        }
    }
} as const;

export const AccountCreateRequestSchema = {
    type: 'object',
    properties: {
        name: {
            type: 'string',
            example: 'Checking Account'
        },
        bank_id: {
            type: 'string'
        },
        opened_at: {
            type: 'string',
            format: 'date-time'
        }
    },
    required: ['name', 'bank_id', 'opened_at']
} as const;

export const CategoryCreateRequestSchema = {
    type: 'object',
    properties: {
        name: {
            type: 'string',
            example: 'Groceries'
        }
    },
    required: ['name']
} as const;

export const CategoryEditRequestSchema = {
    type: 'object',
    properties: {
        name: {
            type: 'string',
            example: 'Groceries'
        }
    },
    required: ['name']
} as const;

export const CategoryAddRuleRequestSchema = {
    type: 'object',
    properties: {
        account_id: {
            type: 'string'
        },
        rule: {
            type: 'string',
            example: 'Tesco'
        }
    }
} as const;

export const CategoryEditRuleRequestSchema = {
    type: 'object',
    properties: {
        account_id: {
            type: 'string'
        },
        rule: {
            type: 'string',
            example: 'Tesco'
        }
    }
} as const;

export const TransactionCreateRequestSchema = {
    type: 'object',
    properties: {
        account_id: {
            type: 'string'
        },
        amount: {
            type: 'number',
            example: 100
        },
        category_id: {
            type: 'string'
        },
        description: {
            type: 'string',
            example: 'Milk'
        }
    },
    required: ['account_id', 'amount', 'category_id', 'description']
} as const;

export const LoginResponseSchema = {
    type: 'object',
    properties: {
        token: {
            type: 'string'
        },
        id: {
            type: 'string'
        }
    },
    required: ['token', 'id']
} as const;

export const SignupResponseSchema = {
    type: 'object',
    properties: {
        message: {
            type: 'string'
        }
    },
    required: ['message']
} as const;

export const AccountCreateResponseSchema = {
    type: 'object',
    properties: {
        ids: {
            type: 'array',
            items: {
                type: 'string'
            }
        }
    },
    required: ['ids']
} as const;

export const AccountDeleteResponseSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        message: {
            type: 'string'
        }
    },
    required: ['id', 'message']
} as const;

export const CategoryCreateResponseSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        }
    },
    required: ['id']
} as const;

export const CategoryEditResponseSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        name: {
            type: 'string'
        }
    },
    required: ['id', 'name']
} as const;

export const CategoryDeleteResponseSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        message: {
            type: 'string'
        }
    },
    required: ['id', 'message']
} as const;

export const CategoryAddRuleResponseSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        rule_id: {
            type: 'string'
        }
    },
    required: ['id', 'rule_id']
} as const;

export const CategoryEditRuleResponseSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        rule_id: {
            type: 'string'
        }
    },
    required: ['id', 'rule_id']
} as const;

export const CategoryDeleteRuleResponseSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        rule_id: {
            type: 'string'
        },
        message: {
            type: 'string'
        }
    },
    required: ['id', 'rule_id', 'message']
} as const;

export const TransactionCreateResponseSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        }
    },
    required: ['id']
} as const;

export const TransactionDeleteResponseSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        message: {
            type: 'string'
        }
    },
    required: ['id', 'message']
} as const;

export const NotAuthorizedSchema = {
    type: 'object',
    properties: {
        message: {
            type: 'string',
            const: 'Not authorized'
        }
    }
} as const;

export const NotFoundSchema = {
    type: 'object',
    properties: {
        message: {
            type: 'string',
            const: 'Not found'
        }
    }
} as const;

export const UserSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        email: {
            type: 'string'
        },
        created_at: {
            type: 'string',
            format: 'date-time'
        }
    },
    required: ['id', 'email', 'created_at']
} as const;

export const AccountSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        name: {
            type: 'string'
        },
        bank: {
            '$ref': '#/components/schemas/Bank'
        },
        opened_at: {
            type: 'string',
            format: 'date-time'
        },
        closed_at: {
            type: 'string',
            format: 'date-time'
        }
    },
    required: ['id', 'name', 'bank', 'opened_at']
} as const;

export const BankSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        name: {
            type: 'string'
        },
        fixed_products: {
            type: 'boolean'
        },
        csv_import_enabled: {
            type: 'boolean'
        },
        api_import_enabled: {
            type: 'boolean'
        }
    },
    required: ['id', 'name', 'csv_import_enabled', 'api_import_enabled']
} as const;

export const CategorySchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        name: {
            type: 'string'
        },
        created_at: {
            type: 'string',
            format: 'date-time'
        },
        rules: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/CategoryRule'
            }
        }
    },
    required: ['id', 'name', 'created_at', 'rules']
} as const;

export const CategoryRuleSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        account: {
            '$ref': '#/components/schemas/Account'
        },
        rule: {
            type: 'string'
        }
    },
    required: ['id', 'account', 'rule']
} as const;

export const TransactionSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string'
        },
        amount: {
            type: 'number'
        },
        category: {
            '$ref': '#/components/schemas/Category'
        },
        account: {
            '$ref': '#/components/schemas/Account'
        },
        description: {
            type: 'string'
        },
        date: {
            type: 'string',
            format: 'date-time'
        },
        created_at: {
            type: 'string',
            format: 'date-time'
        }
    },
    required: ['id', 'amount', 'account', 'description', 'date', 'created_at']
} as const;