// This file is auto-generated by @hey-api/openapi-ts

export const LoginRequestSchema = {
    type: 'object',
    properties: {
        email: {
            type: 'string'
        },
        password: {
            type: 'string'
        }
    },
    required: ['email', 'password']
} as const;

export const LoginResponseSchema = {
    type: 'object',
    properties: {
        token: {
            type: 'string'
        },
        id: {
            type: 'integer'
        }
    },
    required: ['token', 'id']
} as const;

export const SignupRequestSchema = {
    type: 'object',
    properties: {
        email: {
            type: 'string',
            example: 'user@example.com'
        },
        password: {
            type: 'string',
            example: 'password'
        }
    }
} as const;

export const SignupResponseSchema = {
    type: 'object',
    properties: {
        message: {
            type: 'string'
        }
    },
    required: ['message']
} as const;

export const UserSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'integer'
        },
        email: {
            type: 'string'
        },
        created_at: {
            type: 'string',
            format: 'date-time'
        }
    },
    required: ['id', 'email', 'created_at']
} as const;

export const AccountCreateRequestSchema = {
    type: 'object',
    properties: {
        name: {
            type: 'string',
            example: 'Checking Account'
        }
    },
    required: ['name']
} as const;

export const AccountCreateResponseSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'integer'
        }
    },
    required: ['id']
} as const;

export const AccountSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'integer'
        },
        name: {
            type: 'string'
        },
        created_at: {
            type: 'string',
            format: 'date-time'
        }
    },
    required: ['id', 'name', 'created_at']
} as const;

export const AccountDeleteResponseSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'integer'
        },
        message: {
            type: 'string'
        }
    },
    required: ['id', 'message']
} as const;

export const CategoryCreateRequestSchema = {
    type: 'object',
    properties: {
        name: {
            type: 'string',
            example: 'Groceries'
        }
    },
    required: ['name']
} as const;

export const CategoryCreateResponseSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'integer'
        }
    },
    required: ['id']
} as const;

export const CategorySchema = {
    type: 'object',
    properties: {
        id: {
            type: 'integer'
        },
        name: {
            type: 'string'
        },
        created_at: {
            type: 'string',
            format: 'date-time'
        }
    },
    required: ['id', 'name', 'created_at']
} as const;

export const CategoryDeleteResponseSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'integer'
        },
        message: {
            type: 'string'
        }
    },
    required: ['id', 'message']
} as const;

export const TransactionCreateRequestSchema = {
    type: 'object',
    properties: {
        amount: {
            type: 'number',
            example: 100
        },
        category_id: {
            type: 'integer'
        },
        description: {
            type: 'string',
            example: 'Milk'
        }
    },
    required: ['amount', 'category_id']
} as const;

export const TransactionCreateResponseSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'integer'
        }
    },
    required: ['id']
} as const;

export const TransactionSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'integer'
        },
        amount: {
            type: 'number'
        },
        category: {
            '$ref': '#/components/schemas/Category'
        },
        description: {
            type: 'string'
        },
        date: {
            type: 'string',
            format: 'date-time'
        },
        created_at: {
            type: 'string',
            format: 'date-time'
        }
    },
    required: ['id', 'amount', 'description', 'date', 'created_at']
} as const;

export const TransactionDeleteResponseSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'integer'
        },
        message: {
            type: 'string'
        }
    },
    required: ['id', 'message']
} as const;