// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type Options } from '@hey-api/client-fetch';
import type { PostLoginData, PostLoginError, PostLoginResponse, PostSignupData, PostSignupError, PostSignupResponse, GetBanksError, GetBanksResponse, GetUserByIdData, GetUserByIdError, GetUserByIdResponse, PostUserByIdAccountsData, PostUserByIdAccountsError, PostUserByIdAccountsResponse, GetUserByIdAccountsData, GetUserByIdAccountsError, GetUserByIdAccountsResponse, GetUserByIdAccountsByAccountIdData, GetUserByIdAccountsByAccountIdError, GetUserByIdAccountsByAccountIdResponse, DeleteUserByIdAccountsByAccountIdData, DeleteUserByIdAccountsByAccountIdError, DeleteUserByIdAccountsByAccountIdResponse, PostUserByIdTransactionsData, PostUserByIdTransactionsError, PostUserByIdTransactionsResponse, GetUserByIdTransactionsData, GetUserByIdTransactionsError, GetUserByIdTransactionsResponse, DeleteUserByIdTransactionsByTransactionIdData, DeleteUserByIdTransactionsByTransactionIdError, DeleteUserByIdTransactionsByTransactionIdResponse, PostUserByIdCategoriesData, PostUserByIdCategoriesError, PostUserByIdCategoriesResponse, GetUserByIdCategoriesData, GetUserByIdCategoriesError, GetUserByIdCategoriesResponse, GetUserByIdCategoriesByCategoryIdData, GetUserByIdCategoriesByCategoryIdError, GetUserByIdCategoriesByCategoryIdResponse, PatchUserByIdCategoriesByCategoryIdData, PatchUserByIdCategoriesByCategoryIdError, PatchUserByIdCategoriesByCategoryIdResponse, DeleteUserByIdCategoriesByCategoryIdData, DeleteUserByIdCategoriesByCategoryIdError, DeleteUserByIdCategoriesByCategoryIdResponse, PostUserByIdCategoriesByCategoryIdRulesData, PostUserByIdCategoriesByCategoryIdRulesError, PostUserByIdCategoriesByCategoryIdRulesResponse, PatchUserByIdCategoriesByCategoryIdRulesByRuleIdData, PatchUserByIdCategoriesByCategoryIdRulesByRuleIdError, PatchUserByIdCategoriesByCategoryIdRulesByRuleIdResponse, DeleteUserByIdCategoriesByCategoryIdRulesByRuleIdData, DeleteUserByIdCategoriesByCategoryIdRulesByRuleIdError, DeleteUserByIdCategoriesByCategoryIdRulesByRuleIdResponse } from './types.gen';

export const client = createClient(createConfig());

export const postLogin = <ThrowOnError extends boolean = false>(options?: Options<PostLoginData, ThrowOnError>) => { return (options?.client ?? client).post<PostLoginResponse, PostLoginError, ThrowOnError>({
    ...options,
    url: '/login'
}); };

export const postSignup = <ThrowOnError extends boolean = false>(options?: Options<PostSignupData, ThrowOnError>) => { return (options?.client ?? client).post<PostSignupResponse, PostSignupError, ThrowOnError>({
    ...options,
    url: '/signup'
}); };

export const getBanks = <ThrowOnError extends boolean = false>(options?: Options<unknown, ThrowOnError>) => { return (options?.client ?? client).get<GetBanksResponse, GetBanksError, ThrowOnError>({
    ...options,
    url: '/banks'
}); };

export const getUserById = <ThrowOnError extends boolean = false>(options: Options<GetUserByIdData, ThrowOnError>) => { return (options?.client ?? client).get<GetUserByIdResponse, GetUserByIdError, ThrowOnError>({
    ...options,
    url: '/user/{id}'
}); };

export const postUserByIdAccounts = <ThrowOnError extends boolean = false>(options: Options<PostUserByIdAccountsData, ThrowOnError>) => { return (options?.client ?? client).post<PostUserByIdAccountsResponse, PostUserByIdAccountsError, ThrowOnError>({
    ...options,
    url: '/user/{id}/accounts'
}); };

export const getUserByIdAccounts = <ThrowOnError extends boolean = false>(options: Options<GetUserByIdAccountsData, ThrowOnError>) => { return (options?.client ?? client).get<GetUserByIdAccountsResponse, GetUserByIdAccountsError, ThrowOnError>({
    ...options,
    url: '/user/{id}/accounts'
}); };

export const getUserByIdAccountsByAccountId = <ThrowOnError extends boolean = false>(options: Options<GetUserByIdAccountsByAccountIdData, ThrowOnError>) => { return (options?.client ?? client).get<GetUserByIdAccountsByAccountIdResponse, GetUserByIdAccountsByAccountIdError, ThrowOnError>({
    ...options,
    url: '/user/{id}/accounts/{account_id}'
}); };

export const deleteUserByIdAccountsByAccountId = <ThrowOnError extends boolean = false>(options: Options<DeleteUserByIdAccountsByAccountIdData, ThrowOnError>) => { return (options?.client ?? client).delete<DeleteUserByIdAccountsByAccountIdResponse, DeleteUserByIdAccountsByAccountIdError, ThrowOnError>({
    ...options,
    url: '/user/{id}/accounts/{account_id}'
}); };

export const postUserByIdTransactions = <ThrowOnError extends boolean = false>(options: Options<PostUserByIdTransactionsData, ThrowOnError>) => { return (options?.client ?? client).post<PostUserByIdTransactionsResponse, PostUserByIdTransactionsError, ThrowOnError>({
    ...options,
    url: '/user/{id}/transactions'
}); };

export const getUserByIdTransactions = <ThrowOnError extends boolean = false>(options: Options<GetUserByIdTransactionsData, ThrowOnError>) => { return (options?.client ?? client).get<GetUserByIdTransactionsResponse, GetUserByIdTransactionsError, ThrowOnError>({
    ...options,
    url: '/user/{id}/transactions'
}); };

export const deleteUserByIdTransactionsByTransactionId = <ThrowOnError extends boolean = false>(options: Options<DeleteUserByIdTransactionsByTransactionIdData, ThrowOnError>) => { return (options?.client ?? client).delete<DeleteUserByIdTransactionsByTransactionIdResponse, DeleteUserByIdTransactionsByTransactionIdError, ThrowOnError>({
    ...options,
    url: '/user/{id}/transactions/{transaction_id}'
}); };

export const postUserByIdCategories = <ThrowOnError extends boolean = false>(options: Options<PostUserByIdCategoriesData, ThrowOnError>) => { return (options?.client ?? client).post<PostUserByIdCategoriesResponse, PostUserByIdCategoriesError, ThrowOnError>({
    ...options,
    url: '/user/{id}/categories'
}); };

export const getUserByIdCategories = <ThrowOnError extends boolean = false>(options: Options<GetUserByIdCategoriesData, ThrowOnError>) => { return (options?.client ?? client).get<GetUserByIdCategoriesResponse, GetUserByIdCategoriesError, ThrowOnError>({
    ...options,
    url: '/user/{id}/categories'
}); };

export const getUserByIdCategoriesByCategoryId = <ThrowOnError extends boolean = false>(options: Options<GetUserByIdCategoriesByCategoryIdData, ThrowOnError>) => { return (options?.client ?? client).get<GetUserByIdCategoriesByCategoryIdResponse, GetUserByIdCategoriesByCategoryIdError, ThrowOnError>({
    ...options,
    url: '/user/{id}/categories/{category_id}'
}); };

export const patchUserByIdCategoriesByCategoryId = <ThrowOnError extends boolean = false>(options: Options<PatchUserByIdCategoriesByCategoryIdData, ThrowOnError>) => { return (options?.client ?? client).patch<PatchUserByIdCategoriesByCategoryIdResponse, PatchUserByIdCategoriesByCategoryIdError, ThrowOnError>({
    ...options,
    url: '/user/{id}/categories/{category_id}'
}); };

export const deleteUserByIdCategoriesByCategoryId = <ThrowOnError extends boolean = false>(options: Options<DeleteUserByIdCategoriesByCategoryIdData, ThrowOnError>) => { return (options?.client ?? client).delete<DeleteUserByIdCategoriesByCategoryIdResponse, DeleteUserByIdCategoriesByCategoryIdError, ThrowOnError>({
    ...options,
    url: '/user/{id}/categories/{category_id}'
}); };

export const postUserByIdCategoriesByCategoryIdRules = <ThrowOnError extends boolean = false>(options: Options<PostUserByIdCategoriesByCategoryIdRulesData, ThrowOnError>) => { return (options?.client ?? client).post<PostUserByIdCategoriesByCategoryIdRulesResponse, PostUserByIdCategoriesByCategoryIdRulesError, ThrowOnError>({
    ...options,
    url: '/user/{id}/categories/{category_id}/rules'
}); };

export const patchUserByIdCategoriesByCategoryIdRulesByRuleId = <ThrowOnError extends boolean = false>(options: Options<PatchUserByIdCategoriesByCategoryIdRulesByRuleIdData, ThrowOnError>) => { return (options?.client ?? client).patch<PatchUserByIdCategoriesByCategoryIdRulesByRuleIdResponse, PatchUserByIdCategoriesByCategoryIdRulesByRuleIdError, ThrowOnError>({
    ...options,
    url: '/user/{id}/categories/{category_id}/rules/{rule_id}'
}); };

export const deleteUserByIdCategoriesByCategoryIdRulesByRuleId = <ThrowOnError extends boolean = false>(options: Options<DeleteUserByIdCategoriesByCategoryIdRulesByRuleIdData, ThrowOnError>) => { return (options?.client ?? client).delete<DeleteUserByIdCategoriesByCategoryIdRulesByRuleIdResponse, DeleteUserByIdCategoriesByCategoryIdRulesByRuleIdError, ThrowOnError>({
    ...options,
    url: '/user/{id}/categories/{category_id}/rules/{rule_id}'
}); };