// This file is auto-generated by @hey-api/openapi-ts

export type LoginRequest = {
    email: string;
    password: string;
};

export type LoginResponse = {
    token: string;
    id: number;
};

export type SignupRequest = {
    email?: string;
    password?: string;
};

export type SignupResponse = {
    message: string;
};

export type User = {
    id: number;
    email: string;
    created_at: string;
};

export type AccountCreateRequest = {
    name: string;
};

export type AccountCreateResponse = {
    id: number;
};

export type Account = {
    id: number;
    name: string;
    created_at: string;
};

export type AccountDeleteResponse = {
    id: number;
    message: string;
};

export type CategoryCreateRequest = {
    name: string;
};

export type CategoryCreateResponse = {
    id: number;
};

export type Category = {
    id: number;
    name: string;
    created_at: string;
};

export type CategoryDeleteResponse = {
    id: number;
    message: string;
};

export type TransactionCreateRequest = {
    amount: number;
    category_id: number;
    description?: string;
};

export type TransactionCreateResponse = {
    id: number;
};

export type Transaction = {
    id: number;
    amount: number;
    category?: Category;
    description: string;
    date: string;
    created_at: string;
};

export type TransactionDeleteResponse = {
    id: number;
    message: string;
};

export type PostLoginData = {
    body?: LoginRequest;
};

export type PostLoginResponse = (LoginResponse);

export type PostLoginError = unknown;

export type PostSignupData = {
    body?: SignupRequest;
};

export type PostSignupResponse = (SignupResponse);

export type PostSignupError = unknown;

export type GetUserByIdData = {
    path: {
        id: number;
    };
};

export type GetUserByIdResponse = (User);

export type GetUserByIdError = unknown;

export type PostUserByIdAccountsData = {
    body?: AccountCreateRequest;
    path: {
        id: number;
    };
};

export type PostUserByIdAccountsResponse = (AccountCreateResponse);

export type PostUserByIdAccountsError = unknown;

export type GetUserByIdAccountsData = {
    path: {
        id: number;
    };
};

export type GetUserByIdAccountsResponse = (Array<Account>);

export type GetUserByIdAccountsError = unknown;

export type GetUserByIdAccountsByAccountIdData = {
    path: {
        account_id: number;
        id: number;
    };
};

export type GetUserByIdAccountsByAccountIdResponse = (Account);

export type GetUserByIdAccountsByAccountIdError = unknown;

export type DeleteUserByIdAccountsByAccountIdData = {
    path: {
        account_id: number;
        id: number;
    };
};

export type DeleteUserByIdAccountsByAccountIdResponse = (AccountDeleteResponse);

export type DeleteUserByIdAccountsByAccountIdError = unknown;

export type PostUserByIdAccountsByAccountIdTransactionsData = {
    body?: TransactionCreateRequest;
    path: {
        account_id: number;
        id: number;
    };
};

export type PostUserByIdAccountsByAccountIdTransactionsResponse = (TransactionCreateResponse);

export type PostUserByIdAccountsByAccountIdTransactionsError = unknown;

export type GetUserByIdAccountsByAccountIdTransactionsData = {
    path: {
        account_id: number;
        id: number;
    };
};

export type GetUserByIdAccountsByAccountIdTransactionsResponse = (Array<Transaction>);

export type GetUserByIdAccountsByAccountIdTransactionsError = unknown;

export type DeleteUserByIdAccountsByAccountIdTransactionsByTransactionIdData = {
    path: {
        account_id: number;
        id: number;
        transaction_id: number;
    };
};

export type DeleteUserByIdAccountsByAccountIdTransactionsByTransactionIdResponse = (TransactionDeleteResponse);

export type DeleteUserByIdAccountsByAccountIdTransactionsByTransactionIdError = unknown;

export type PostUserByIdCategoriesData = {
    body?: CategoryCreateRequest;
    path: {
        id: number;
    };
};

export type PostUserByIdCategoriesResponse = (CategoryCreateResponse);

export type PostUserByIdCategoriesError = unknown;

export type GetUserByIdCategoriesData = {
    path: {
        id: number;
    };
};

export type GetUserByIdCategoriesResponse = (Array<Category>);

export type GetUserByIdCategoriesError = unknown;

export type GetUserByIdCategoriesByCategoryIdData = {
    path: {
        category_id: number;
        id: number;
    };
};

export type GetUserByIdCategoriesByCategoryIdResponse = (Category);

export type GetUserByIdCategoriesByCategoryIdError = unknown;

export type DeleteUserByIdCategoriesByCategoryIdData = {
    path: {
        category_id: number;
        id: number;
    };
};

export type DeleteUserByIdCategoriesByCategoryIdResponse = (CategoryDeleteResponse);

export type DeleteUserByIdCategoriesByCategoryIdError = unknown;