// This file is auto-generated by @hey-api/openapi-ts

export type LoginRequest = {
    email: string;
    password: string;
};

export type SignupRequest = {
    email: string;
    password: string;
    master_key: string;
    salt: string;
};

export type AccountCreateRequest = {
    name: string;
    bank_id: string;
    opened_at: string;
};

export type AccountEditRequest = {
    name?: string;
    bank_id?: string;
    opened_at?: string;
    closed_at?: string;
};

export type CategoryCreateRequest = {
    name: string;
};

export type CategoryEditRequest = {
    name: string;
};

export type CategoryAddRuleRequest = {
    account_id?: string;
    description?: string;
    rule?: string;
};

export type CategoryEditRuleRequest = {
    account_id?: string;
    description?: string;
    rule?: string;
};

export type TransactionCreateRequest = {
    account_id: string;
    amount: number;
    category_id?: string;
    description: string;
    date: string;
};

export type TransactionEditRequest = {
    account_id?: string;
    amount?: number;
    category_id?: string;
    description?: string;
    date?: string;
};

export type TransactionBulkCreateRequest = {
    hash: string;
    transactions: Array<TransactionCreateRequest>;
};

export type TransactionBulkFinaliseRequest = {
    hash: string;
};

export type TransactionBulkDeleteRequest = {
    hash: string;
    cancel?: boolean;
};

export type BudgetTransactionCreateRequest = {
    category_id?: string;
    amount: number;
    description?: string;
    repeat_until: PeriodUnit;
    repeat_every: number;
};

export type BudgetTransactionEditRequest = {
    category_id?: string;
    amount?: number;
    description?: string;
    repeat_until?: PeriodUnit;
    repeat_every?: number;
};

export type LoginResponse = {
    id: string;
    token: string;
    master_key: string;
    salt: string;
};

export type SignupResponse = {
    message: string;
};

export type AccountCreateResponse = {
    id: string;
};

export type AccountEditResponse = {
    id: string;
};

export type AccountDeleteResponse = {
    id: string;
    message: string;
};

export type CategoryCreateResponse = {
    id: string;
};

export type CategoryEditResponse = {
    id: string;
};

export type CategoryDeleteResponse = {
    id: string;
    message: string;
};

export type CategoryAddRuleResponse = {
    id: string;
};

export type CategoryEditRuleResponse = {
    id: string;
};

export type CategoryDeleteRuleResponse = {
    id: string;
    message: string;
};

export type TransactionsResponse = {
    transactions: Array<Transaction>;
    cursor?: string;
};

export type TransactionCreateResponse = {
    id: string;
};

export type TransactionEditResponse = {
    id: string;
};

export type TransactionDeleteResponse = {
    id: string;
    message: string;
};

export type TransactionBulkResponse = {
    message: string;
};

export type BudgetTransactionCreateResponse = {
    id: string;
};

export type BudgetTransactionEditResponse = {
    id: string;
};

export type BudgetTransactionDeleteResponse = {
    id: string;
    message: string;
};

export type NotAuthorized = {
    message?: "Not authorized";
};

export type NotFound = {
    message?: "Not found";
};

export type User = {
    id: string;
    email: string;
    created_at: string;
};

export type Account = {
    id: string;
    name: string;
    bank: Bank;
    opened_at: string;
    closed_at?: string;
};

export type Bank = {
    id: string;
    name: string;
    short_name: string;
    fixed_products?: boolean;
    csv_import_enabled: boolean;
    api_import_enabled: boolean;
};

export type Category = {
    id: string;
    name: string;
    created_at: string;
    rules: Array<CategoryRule>;
};

export type CategoryRule = {
    id: string;
    account: Account;
    description?: string;
    rule: string;
};

export type Transaction = {
    id: string;
    amount: number;
    category?: Category;
    account: Account;
    description: string;
    date: string;
    created_at: string;
};

export type BudgetTransaction = {
    id: string;
    category?: Category;
    amount: number;
    description?: string;
    repeat_until: PeriodUnit;
    repeat_every: number;
    created_at: string;
    deleted_at?: string;
};

export type AllAccountSummary = {
    accounts: Array<AccountSummary>;
    total: number;
};

export type AccountSummary = {
    account: Account;
    balance: number;
};

export type CategorySummary = {
    category?: Category;
    total: number;
    percentage: number;
};

export type BalanceSummary = {
    total: Array<BalanceDatapoint>;
    accounts: Array<BalanceSummaryAccount>;
};

export type BalanceSummaryAccount = {
    account: Account;
    balance: Array<BalanceDatapoint>;
};

export type BalanceDatapoint = {
    date: string;
    balance: number;
};

export type TotalsSummary = {
    income: number;
    outgoing: number;
    net: number;
};

export type PeriodUnit = 'day' | 'week' | 'month' | 'year';

export type SummaryGroupBy = 'day' | 'week' | 'month';

export type TimePeriod = 'week' | 'month' | 'year' | 'ytd' | 'all';

export type PostLoginData = {
    body?: LoginRequest;
};

export type PostLoginResponse = (LoginResponse);

export type PostLoginError = (NotFound);

export type PostSignupData = {
    body?: SignupRequest;
};

export type PostSignupResponse = (SignupResponse);

export type PostSignupError = (NotAuthorized);

export type GetBanksResponse = (Array<Bank>);

export type GetBanksError = (NotFound);

export type GetUserByIdData = {
    path: {
        id: string;
    };
};

export type GetUserByIdResponse = (User);

export type GetUserByIdError = (NotFound);

export type PostUserByIdAccountsData = {
    body?: AccountCreateRequest;
    path: {
        id: string;
    };
};

export type PostUserByIdAccountsResponse = (AccountCreateResponse);

export type PostUserByIdAccountsError = unknown;

export type GetUserByIdAccountsData = {
    path: {
        id: string;
    };
};

export type GetUserByIdAccountsResponse = (Array<Account>);

export type GetUserByIdAccountsError = (NotFound);

export type GetUserByIdAccountsByAccountIdData = {
    path: {
        account_id: string;
        id: string;
    };
};

export type GetUserByIdAccountsByAccountIdResponse = (Account);

export type GetUserByIdAccountsByAccountIdError = (NotFound);

export type PatchUserByIdAccountsByAccountIdData = {
    body?: AccountEditRequest;
    path: {
        account_id: string;
        id: string;
    };
};

export type PatchUserByIdAccountsByAccountIdResponse = (AccountEditResponse);

export type PatchUserByIdAccountsByAccountIdError = (NotFound);

export type DeleteUserByIdAccountsByAccountIdData = {
    path: {
        account_id: string;
        id: string;
    };
};

export type DeleteUserByIdAccountsByAccountIdResponse = (AccountDeleteResponse);

export type DeleteUserByIdAccountsByAccountIdError = (NotFound);

export type PostUserByIdTransactionsData = {
    body?: TransactionCreateRequest;
    path: {
        id: string;
    };
};

export type PostUserByIdTransactionsResponse = (TransactionCreateResponse);

export type PostUserByIdTransactionsError = unknown;

export type GetUserByIdTransactionsData = {
    path: {
        id: string;
    };
    query?: {
        account_id?: string;
        category_id?: string;
        cursor?: string;
        limit?: number;
        period?: TimePeriod;
    };
};

export type GetUserByIdTransactionsResponse = (TransactionsResponse);

export type GetUserByIdTransactionsError = (NotFound);

export type GetUserByIdTransactionsByTransactionIdData = {
    path: {
        id: string;
        transaction_id: string;
    };
};

export type GetUserByIdTransactionsByTransactionIdResponse = (Transaction);

export type GetUserByIdTransactionsByTransactionIdError = (NotFound);

export type PatchUserByIdTransactionsByTransactionIdData = {
    body?: TransactionEditRequest;
    path: {
        id: string;
        transaction_id: string;
    };
};

export type PatchUserByIdTransactionsByTransactionIdResponse = (TransactionEditResponse);

export type PatchUserByIdTransactionsByTransactionIdError = (NotFound);

export type DeleteUserByIdTransactionsByTransactionIdData = {
    path: {
        id: string;
        transaction_id: string;
    };
};

export type DeleteUserByIdTransactionsByTransactionIdResponse = (TransactionDeleteResponse);

export type DeleteUserByIdTransactionsByTransactionIdError = (NotFound);

export type PostUserByIdTransactionsBulkData = {
    body?: TransactionBulkCreateRequest;
    path: {
        id: string;
    };
};

export type PostUserByIdTransactionsBulkResponse = (TransactionBulkResponse);

export type PostUserByIdTransactionsBulkError = unknown;

export type PostUserByIdTransactionsBulkFinaliseData = {
    body?: TransactionBulkFinaliseRequest;
    path: {
        id: string;
    };
};

export type PostUserByIdTransactionsBulkFinaliseResponse = (TransactionBulkResponse);

export type PostUserByIdTransactionsBulkFinaliseError = unknown;

export type PostUserByIdTransactionsBulkDeleteData = {
    body?: TransactionBulkDeleteRequest;
    path: {
        id: string;
    };
};

export type PostUserByIdTransactionsBulkDeleteResponse = (TransactionBulkResponse);

export type PostUserByIdTransactionsBulkDeleteError = unknown;

export type PostUserByIdCategoriesData = {
    body?: CategoryCreateRequest;
    path: {
        id: string;
    };
};

export type PostUserByIdCategoriesResponse = (CategoryCreateResponse);

export type PostUserByIdCategoriesError = unknown;

export type GetUserByIdCategoriesData = {
    path: {
        id: string;
    };
};

export type GetUserByIdCategoriesResponse = (Array<Category>);

export type GetUserByIdCategoriesError = (NotFound);

export type GetUserByIdCategoriesByCategoryIdData = {
    path: {
        category_id: string;
        id: string;
    };
};

export type GetUserByIdCategoriesByCategoryIdResponse = (Category);

export type GetUserByIdCategoriesByCategoryIdError = (NotFound);

export type PatchUserByIdCategoriesByCategoryIdData = {
    body?: CategoryEditRequest;
    path: {
        category_id: string;
        id: string;
    };
};

export type PatchUserByIdCategoriesByCategoryIdResponse = (CategoryEditResponse);

export type PatchUserByIdCategoriesByCategoryIdError = (NotFound);

export type DeleteUserByIdCategoriesByCategoryIdData = {
    path: {
        category_id: string;
        id: string;
    };
};

export type DeleteUserByIdCategoriesByCategoryIdResponse = (CategoryDeleteResponse);

export type DeleteUserByIdCategoriesByCategoryIdError = (NotFound);

export type PostUserByIdCategoriesByCategoryIdRulesData = {
    body?: CategoryAddRuleRequest;
    path: {
        category_id: string;
        id: string;
    };
};

export type PostUserByIdCategoriesByCategoryIdRulesResponse = (CategoryAddRuleResponse);

export type PostUserByIdCategoriesByCategoryIdRulesError = unknown;

export type PatchUserByIdCategoriesByCategoryIdRulesByRuleIdData = {
    body?: CategoryEditRuleRequest;
    path: {
        category_id: string;
        id: string;
        rule_id: string;
    };
};

export type PatchUserByIdCategoriesByCategoryIdRulesByRuleIdResponse = (CategoryEditRuleResponse);

export type PatchUserByIdCategoriesByCategoryIdRulesByRuleIdError = (NotFound);

export type DeleteUserByIdCategoriesByCategoryIdRulesByRuleIdData = {
    path: {
        category_id: string;
        id: string;
        rule_id: string;
    };
};

export type DeleteUserByIdCategoriesByCategoryIdRulesByRuleIdResponse = (CategoryEditRuleResponse);

export type DeleteUserByIdCategoriesByCategoryIdRulesByRuleIdError = (NotFound);

export type GetUserByIdSummaryAccountsData = {
    path: {
        id: string;
    };
};

export type GetUserByIdSummaryAccountsResponse = (AllAccountSummary);

export type GetUserByIdSummaryAccountsError = unknown;

export type GetUserByIdSummaryCategoriesData = {
    path: {
        id: string;
    };
    query?: {
        period?: TimePeriod;
    };
};

export type GetUserByIdSummaryCategoriesResponse = (Array<CategorySummary>);

export type GetUserByIdSummaryCategoriesError = unknown;

export type GetUserByIdSummaryBalanceData = {
    path: {
        id: string;
    };
    query?: {
        group_by?: TimePeriod;
        period?: TimePeriod;
    };
};

export type GetUserByIdSummaryBalanceResponse = (BalanceSummary);

export type GetUserByIdSummaryBalanceError = unknown;

export type GetUserByIdSummaryTotalsData = {
    path: {
        id: string;
    };
    query?: {
        period?: TimePeriod;
    };
};

export type GetUserByIdSummaryTotalsResponse = (TotalsSummary);

export type GetUserByIdSummaryTotalsError = unknown;

export type PostUserByIdBudgetTransactionsData = {
    body?: BudgetTransactionCreateRequest;
    path: {
        id: string;
    };
};

export type PostUserByIdBudgetTransactionsResponse = (BudgetTransactionCreateResponse);

export type PostUserByIdBudgetTransactionsError = unknown;

export type GetUserByIdBudgetTransactionsData = {
    path: {
        id: string;
    };
};

export type GetUserByIdBudgetTransactionsResponse = (Array<BudgetTransaction>);

export type GetUserByIdBudgetTransactionsError = (NotFound);

export type GetUserByIdBudgetTransactionsByBudgetTransactionIdData = {
    path: {
        budget_transaction_id: string;
        id: string;
    };
};

export type GetUserByIdBudgetTransactionsByBudgetTransactionIdResponse = (BudgetTransaction);

export type GetUserByIdBudgetTransactionsByBudgetTransactionIdError = (NotFound);

export type PatchUserByIdBudgetTransactionsByBudgetTransactionIdData = {
    body?: BudgetTransactionEditRequest;
    path: {
        budget_transaction_id: string;
        id: string;
    };
};

export type PatchUserByIdBudgetTransactionsByBudgetTransactionIdResponse = (BudgetTransactionEditResponse);

export type PatchUserByIdBudgetTransactionsByBudgetTransactionIdError = (NotFound);

export type DeleteUserByIdBudgetTransactionsByBudgetTransactionIdData = {
    path: {
        budget_transaction_id: string;
        id: string;
    };
};

export type DeleteUserByIdBudgetTransactionsByBudgetTransactionIdResponse = (BudgetTransactionDeleteResponse);

export type DeleteUserByIdBudgetTransactionsByBudgetTransactionIdError = (NotFound);