// This file is auto-generated by @hey-api/openapi-ts

export type LoginRequest = {
    email: string;
    password: string;
};

export type SignupRequest = {
    email?: string;
    password?: string;
};

export type AccountCreateRequest = {
    name: string;
    bank_id: string;
};

export type CategoryCreateRequest = {
    name: string;
};

export type TransactionCreateRequest = {
    account_id: string;
    amount: number;
    category_id: number;
    description: string;
};

export type LoginResponse = {
    token: string;
    id: string;
};

export type SignupResponse = {
    message: string;
};

export type AccountCreateResponse = {
    ids: Array<(string)>;
};

export type AccountDeleteResponse = {
    id: string;
    message: string;
};

export type CategoryCreateResponse = {
    id: string;
};

export type CategoryDeleteResponse = {
    id: string;
    message: string;
};

export type TransactionCreateResponse = {
    id: string;
};

export type TransactionDeleteResponse = {
    id: string;
    message: string;
};

export type NotAuthorized = {
    message?: "Not authorized";
};

export type NotFound = {
    message?: "Not found";
};

export type User = {
    id: string;
    email: string;
    created_at: string;
};

export type Account = {
    id: string;
    name: string;
    bank: Bank;
    created_at: string;
};

export type Bank = {
    id: string;
    name: string;
    fixed_products?: boolean;
    csv_import_enabled: boolean;
    api_import_enabled: boolean;
};

export type Category = {
    id: string;
    name: string;
    created_at: string;
};

export type Transaction = {
    id: string;
    amount: number;
    category?: Category;
    description: string;
    date: string;
    created_at: string;
};

export type PostLoginData = {
    body?: LoginRequest;
};

export type PostLoginResponse = (LoginResponse);

export type PostLoginError = (NotFound);

export type PostSignupData = {
    body?: SignupRequest;
};

export type PostSignupResponse = (SignupResponse);

export type PostSignupError = (NotAuthorized);

export type GetBanksResponse = (Array<Bank>);

export type GetBanksError = (NotFound);

export type GetUserByIdData = {
    path: {
        id: string;
    };
};

export type GetUserByIdResponse = (User);

export type GetUserByIdError = (NotFound);

export type PostUserByIdAccountsData = {
    body?: AccountCreateRequest;
    path: {
        id: string;
    };
};

export type PostUserByIdAccountsResponse = (AccountCreateResponse);

export type PostUserByIdAccountsError = unknown;

export type GetUserByIdAccountsData = {
    path: {
        id: string;
    };
};

export type GetUserByIdAccountsResponse = (Array<Account>);

export type GetUserByIdAccountsError = (NotFound);

export type GetUserByIdAccountsByAccountIdData = {
    path: {
        account_id: string;
        id: string;
    };
};

export type GetUserByIdAccountsByAccountIdResponse = (Account);

export type GetUserByIdAccountsByAccountIdError = (NotFound);

export type DeleteUserByIdAccountsByAccountIdData = {
    path: {
        account_id: string;
        id: string;
    };
};

export type DeleteUserByIdAccountsByAccountIdResponse = (AccountDeleteResponse);

export type DeleteUserByIdAccountsByAccountIdError = (NotFound);

export type PostUserByIdTransactionsData = {
    body?: TransactionCreateRequest;
    path: {
        id: string;
    };
};

export type PostUserByIdTransactionsResponse = (TransactionCreateResponse);

export type PostUserByIdTransactionsError = unknown;

export type GetUserByIdTransactionsData = {
    path: {
        id: string;
    };
    query?: {
        account_id?: string;
    };
};

export type GetUserByIdTransactionsResponse = (Array<Transaction>);

export type GetUserByIdTransactionsError = (NotFound);

export type DeleteUserByIdTransactionsByTransactionIdData = {
    path: {
        id: string;
        transaction_id: string;
    };
};

export type DeleteUserByIdTransactionsByTransactionIdResponse = (TransactionDeleteResponse);

export type DeleteUserByIdTransactionsByTransactionIdError = (NotFound);

export type PostUserByIdCategoriesData = {
    body?: CategoryCreateRequest;
    path: {
        id: string;
    };
};

export type PostUserByIdCategoriesResponse = (CategoryCreateResponse);

export type PostUserByIdCategoriesError = unknown;

export type GetUserByIdCategoriesData = {
    path: {
        id: string;
    };
};

export type GetUserByIdCategoriesResponse = (Array<Category>);

export type GetUserByIdCategoriesError = (NotFound);

export type GetUserByIdCategoriesByCategoryIdData = {
    path: {
        category_id: string;
        id: string;
    };
};

export type GetUserByIdCategoriesByCategoryIdResponse = (Category);

export type GetUserByIdCategoriesByCategoryIdError = (NotFound);

export type DeleteUserByIdCategoriesByCategoryIdData = {
    path: {
        category_id: string;
        id: string;
    };
};

export type DeleteUserByIdCategoriesByCategoryIdResponse = (CategoryDeleteResponse);

export type DeleteUserByIdCategoriesByCategoryIdError = (NotFound);